image: zaoqi/the-language-builder

before_script:
  - echo before_script

stages:
  - all

all:
  stage: all
  script:
    - ./make.sh
    - ./test.sh
    - git add .
    - git diff --cached | cat
    - sh -c '[ "$(git diff --cached)" = "" ]'
  retry: 2
