
pages:
  image: zaoqi/the-language-builder
  stage: test
  script:
  - cd docs && ./build.sh && cd ..
  - mv docs public
  artifacts:
    paths:
    - public
  only:
  - master
  retry: 2

all:
  image: zaoqi/the-language-builder
  stage: test
  script:
  - ./make.sh
  - ./test.sh
  - git add .
  - git diff --cached | cat
  - sh -c '[ "$(git diff --cached)" = "" ]'
  retry: 2
