image: archlinux/base

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/namespace/project

before_script:
  - pacman -Sy
  - pacman -S --noconfirm yarn nodejs npm dos2unix racket jdk11-openjdk clang make wget git python2 gawk luarocks php
  - archlinux-java set java-11-openjdk
  - raco pkg install --batch --user --auto rash
  - luarocks install luasrcdiet --local

stages:
    - all

all:
    stage: all
    script:
      - racket make.rkt
      - racket test.rkt
    retry: 2
