image: archlinux/base

pages:
  image: python:3-alpine
  stage: test
  before_script:
  - pip install mkdocs
  # Add your custom theme if not inside a theme_dir
  # (https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
  - pip install mkdocs-material
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  retry: 2

all:
  image: zaoqi/the-language-builder
  stage: test
  script:
  - ./make.sh
  - ./test.sh
  - git add .
  - git diff --cached | cat
  - sh -c '[ "$(git diff --cached)" = "" ]'
  retry: 2
