image: archlinux/base

before_script:
  - pacman -Syu --noconfirm yarn nodejs npm dos2unix racket jdk11-openjdk clang make curl git python2 gawk php base
  - archlinux-java set java-11-openjdk
  - raco pkg install --batch --installation --auto rash

stages:
    - all

all:
    stage: all
    script:
      - ./make.sh
      - ./test.sh
      - git add .
      - git diff --cached | cat
      - sh -c '[ "$(git diff --cached)" = "" ]'
    retry: 2
