function h(){throw"TheLanguage PANIC";}function aa(a){return function(){return[!1,a]}}function m(a){return function(){return[!0,a()]}}function ba(a){for(a=a();a[0];)a=a[1]();return a[1]}function ca(a,b){return[10,a,b]}function n(a){return 10===a[0]}function da(a){for(;n(a);)a=a[2];return a}function q(a){return 0===a[0]}function r(a,b){return a===b?!0:a[1]===b[1]?(t(a,b),!0):!1}function fa(a,b){return[1,a,b]}function u(a){return 1===a[0]}function v(a){return a[1]}function w(a){return a[2]}
function x(a){return 2===a[0]}function ha(a,b){return[3,a,b]}function y(a){return 3===a[0]}function ia(a){return a[1]}function ka(a){return a[2]}function la(a){return 4===a[0]}function ma(a){return a[2]}function z(a,b){return[6,a,b]}function na(a,b){return[8,a,b]}function pa(a){a=A(a);if(y(a)||u(a)||n(a))a[1]=pa(a[1]),a[2]=pa(a[2]);return a}
function qa(a){var b=ra(a);if(y(b)||u(b))if(b[1]=pa(b[1]),b[2]=pa(b[2]),n(b[1])||n(b[2])){a=[9];sa(a,b);var c=b[2];b=qa(b[1]);c=qa(c);a[1]=b;a[2]=c}else a=b;else a=b;return a}function t(a,b){a!==b&&(a===B&&(a=b,b=B),a[0]=4,a[1]=b,a[2]=!1,a[3]=!1)}function sa(a,b){9===a[0]||h();9!==b[0]||h();a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3]}function ta(a){return[3,ua,[1,C,[1,a,B]]]}function D(a){for(var b=B,c=a.length-1;0<=c;c--)b=[1,a[c],b];return b}
function va(a,b,c){for(var e=[];u(a);)e.push(a[1]),a=a[2];return x(a)?b(e):c(e,a)}function E(a){return va(a,function(a){return a},function(){return!1})}function G(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return D(a)}function H(a){if(!la(a))return a;for(var b=[];la(a);)b.push(a),a=a[1];for(var c=0;c<b.length;c++)t(b[c],a);return a}function wa(a){return 5===a[0]||7===a[0]||6===a[0]||8===a[0]}function I(a){return la(a)||wa(a)}function xa(a){return I(a)||n(a)}
function ya(a){if(5===a[0])return a;if(7===a[0])throw"WIP";if(6===a[0])throw"WIP";if(8===a[0])throw"WIP";return h()}
function A(a,b,c,e){function d(a){t(l,a);for(var b=0;b<e.length;b++)t(e[b],a);return a}function f(){c[1]=!0;return g(za)}function g(a){d(a);return I(a)?(e.push(l),A(a,b,[!1,!1],e)):a}function k(){var a={},c;for(c in p)a[c]=!0;for(c in b)a[c]=!0;return a}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);void 0===e&&(e=[]);var p={},l=a;for(a=0;I(l)&&32>a;a++)e.push(l),l=J(l);for(;I(l);){a=K(l);if(!0===b[a])return f();if(!0===p[a]){c[0]=!0;if(5===l[0])return f();if(6===l[0]){a=l[1];for(var F=l[2],ea=!1,U=0,
V=[Aa,Ba,Ca,Da,Ea,Fa,Ga,Ha];U<V.length;U++)if(M(V[U],a)){ea=!0;break}if(ea)return 1===F.length||h(),!1===c[1]||h(),F=A(F[0],k(),c),c[1]?g(z(a,[F])):h();if(M(a,Ia)||M(a,Ja)||M(a,Ka))return f();if(M(a,La)&&(3===F.length||h(),!1===c[1]||h(),a=A(F[0],k(),c),c[1]))return g(z(La,[a,F[1],F[2]]))}else if(7===l[0]||8===l[0])return f();return h()}p[a]=!0;e.push(l);l=J(l)}return d(l)}
function J(a){var b=H(a);!la(b)||h();a=5===b[0]?Ma(b[1],b[2],a):7===b[0]?Na(b[1],b[2],b[3]):6===b[0]?Oa(b[1],b[2],a):8===b[0]?Pa(b[1],b[2],a):b;a=H(a);t(b,a);return a}function ra(a){for(;I(a)||n(a);)a=A(da(a));return a}function Qa(a){for(;n(a);)a=a[2];for(a=J(a);n(a);)a=a[2];return a}function Ra(a,b,c,e){var d=[],f=[];a=H(a);for(var g=!0;;){if(x(a))return e(f,d);if(n(a))f.push(a[1]),a=a[2];else if(u(a))d.push(a[1]),a=a[2];else if(I(a))if(g)g=!1,a=J(a);else return c();else return b()}}
function Sa(a){xa(a)&&(a=Qa(a));if(xa(a))return null;if(q(a))return!0;if(!y(a))return!1;a=a[1];xa(a)&&(a=Qa(a));return xa(a)?null:q(a)?r(a,N):!1}function Ta(a,b,c){for(var e=[],d=0;d<a.length;d+=2){if(M(a[d],b)){e[d]=b;e[d+1]=c;for(d+=2;d<a.length;d+=2)e[d]=a[d],e[d+1]=a[d+1];return e}e[d]=a[d];e[d+1]=a[d+1]}e[a.length]=b;e[a.length+1]=c;return e}function Ua(a,b,c){for(var e=0;e<a.length;e+=2)if(M(a[e],b))return a[e+1];return c}
function ab(a,b){for(var c=0;c<a.length;c+=2)if(M(a[c],b))return a[c+1];return h()}function O(a){for(var b=B,c=0;c<a.length;c+=2)b=[1,G(a[c],a[c+1]),b];return[3,bb,G(b)]}function cb(a,b){for(var c=0;c<a.length;c+=2)b(a[c],a[c+1])}
function db(a){a=A(a);if(!y(a))return!1;var b=A(a[1]);if(!q(b)||!r(b,bb))return!1;b=A(a[2]);if(!u(b)||!x(A(b[2])))return!1;a=[];for(b=A(b[1]);!x(b);){if(!u(b))return!1;var c=A(b[1]);b=A(b[2]);if(!u(c))return!1;var e=c[1];c=A(c[2]);if(!u(c))return!1;var d=c[1];if(!x(A(c[2])))return!1;c=!0;for(var f=0;f<a.length;f+=2)if(M(a[f],e)){a[f+1]=d;c=!1;break}c&&a.push(e,d)}return a}
function Ma(a,b,c){function e(){return ta(G(eb,G(Ka,G(O(a),d))))}var d=J(b);if(I(d))return c;if(u(d))return Ra(d,e,function(){return c},function(b,d){if(0!==b.length)throw"WIP";if(M(d[0],fb)){if(1===d.length)return e();for(var k=d[1],f=[],g=2;g<d.length;g++)f.push(d[g]);return[7,a,k,f]}if(M(d[0],gb)){if(1===d.length)return e();k=A([5,a,d[1]]);if(!y(k))return e();f=J(k[1]);if(I(f))return c;if(!q(f)||!r(f,P))return e();f=J(k[2]);if(I(f))return c;if(!u(f))return e();k=f[1];f=J(f[2]);if(I(f))return c;
if(!x(f))return e();f=[O(a)];for(g=2;g<d.length;g++)f.push(d[g]);return[8,k,f]}if(M(d[0],eb)){if(1===d.length)return e();k=d[1];f=[];for(g=2;g<d.length;g++)f.push([5,a,d[g]]);return[6,k,f]}k=[5,a,d[0]];f=[];for(g=1;g<d.length;g++)f.push([5,a,d[g]]);return[8,k,f]});if(x(d))return d;b=Sa(d);return null===b?c:!0===b?Ua(a,d,e()):e()}
function Pa(a,b,c){function e(){return ta(G(eb,G(Ja,G(a,D(b)))))}a=J(a);if(I(a))return c;if(!y(a))return e();var d=A(a[1]);if(!q(d)||!r(d,Q))return e();var f=A(a[2]);if(!u(f))return e();d=pa(f[1]);f=A(f[2]);if(!u(f)||!x(A(f[2])))return e();f=f[1];for(var g=hb,k=0;!x(d);){var p=Sa(d);if(null===p)return c;if(!0===p){p=B;for(var l=b.length-1;l>=k;l--)p=[1,b[l],p];g=Ta(g,d,p);k=b.length;d=B}else if(u(d))if(k<b.length)p=b[k],k++,g=Ta(g,d[1],p),d=d[2];else return e();else return e()}return b.length!==k?
e():[5,g,f]}function Oa(a,b,c){function e(){return ta(G(eb,G(a,D(b))))}for(var d=0;d<ib.length;d++){var f=ib[d];if(M(a,f[0])){if(b.length!==f[1])break;return 1===f[1]?f[2](b[0],e,c):2===f[1]?f[2](b[0],b[1],e,c):3===f[1]?f[2](b[0],b[1],b[2],e,c):h()}}return e()}function Na(a,b,c){function e(){return ta(G(fb,G(O(a),b,D(c))))}return M(b,jb)?1!==c.length?e():c[0]:M(b,kb)?2!==c.length?e():lb(a,c[0],c[1],e):M(b,ob)?2!==c.length?e():[10,c[0],[5,a,c[1]]]:e()}
function lb(a,b,c,e){b=qa(b);for(var d=[],f=!1,g=b;!x(g);){var k=Sa(g);null!==k||h();if(k)d.push(g),f=!0,g=B;else if(u(g))d.push(g[1]),g=g[2];else return e()}g=f?D(d):b;var p=[];cb(a,function(a){for(var b=0;b<d.length;b++)if(M(d[b],a))return;p.push(a)});e=g;for(f=p.length-1;0<=f;f--)e=[1,p[f],e];for(f=p.length-1;0<=f;f--)g=fa(G(fb,jb,ab(a,p[f])),g);return[3,Q,G(b,[1,G(fb,jb,[3,Q,G(e,c)]),g])]}
function pb(a,b){function c(a,b,c,e){c=pb(c(a),c(b));e=pb(e(a),e(b));return!0===c&&!0===e?(t(a,b),!0):!1!==c&&!1!==e?null:!1}if(a===b)return!0;a=A(a);b=A(b);if(a===b)return!0;if(n(a)){var e=pb(da(a),b);!0===e&&(e=null);return e}if(n(b))return e=pb(a,da(b)),!0===e&&(e=null),e;if(x(a)){if(!x(b))return!1;t(a,b);return!0}return q(a)?q(b)?r(a,b):!1:u(a)?u(b)?c(a,b,v,w):!1:y(a)?y(b)?c(a,b,ia,ka):!1:h()}function M(a,b){return!1!==pb(a,b)}
function R(a,b){function c(a,b,c,g){return R(c(a),c(b))&&R(g(a),g(b))?(t(a,b),!0):!1}if(a===b)return!0;a=H(a);b=H(b);if(a===b)return!0;if(x(a)){if(!x(b))return!1;t(a,B);t(b,B);return!0}return q(a)?q(b)?r(a,b):!1:u(a)?u(b)?c(a,b,v,w):!1:y(a)?y(b)?c(a,b,ia,ka):!1:wa(a)?!1:h()}
function K(a){a=H(a);var b;if(x(a))return"()";if(u(a)){var c="(";for(b="";u(a);)c+=b+K(a[1]),b=" ",a=H(a[2]);return x(a)?c+")":c+(" . "+K(a)+")")}return y(a)?"#"+K([1,a[1],a[2]]):q(a)?a[1]:n(a)?";("+K(a[1])+" "+K(a[2])+")":5===a[0]?"$("+K(O(a[1]))+" "+K(a[2])+")":6===a[0]?"%("+K(a[1])+" "+K(D(a[2]))+")":7===a[0]?"@("+K(O(a[1]))+" "+K(a[2])+" "+K(D(a[3]))+")":8===a[0]?"^("+K(a[1])+" "+K(D(a[2]))+")":h()}
function qb(a){function b(){return Va.length===oa}function c(){!b()||h();var a=Va[oa];oa++;return a}function e(a){Va[oa-1]===a||h();oa--}function d(a){void 0===a&&(a="");throw"TheLanguage parse ERROR!"+a;}function f(a){return" "===a||"\n"===a||"\t"===a||"\r"===a}function g(){if(b())return!1;var a=c();if(!f(a))return e(a),!1;for(;f(a)&&!b();)a=c();f(a)||e(a);return!0}function k(){if(b())return!1;var a=c(),d="";if(!ea(a))return e(a),!1;for(;ea(a)&&!b();)d+=a,a=c();ea(a)?d+=a:e(a);return[0,d]}function p(){if(b())return!1;
var a=c();if("("!==a)return e(a),!1;for(var f=[9],k=f;;){g();if(b())return d();a=c();if(")"===a)return sa(f,B),k;if("."===a){g();a=U();sa(f,a);g();if(b())return d();a=c();return")"!==a?d():k}e(a);a=U();var p=[9];sa(f,[1,a,p]);f=p}}function l(){if(b())return!1;var a=c();if("#"!==a)return e(a),!1;a=p();return!1!==a&&u(a)?[3,a[1],a[2]]:d()}function F(a,f){return function(){if(b())return!1;var g=c();if(g!==a)return e(g),!1;g=p();if(!1===g||!u(g))return d();var k=g[2];return u(k)&&x(k[2])?f(g[1],k[1]):
d()}}function ea(a){if(f(a))return!1;for(var b=0,c="()!#.$%^@~/->_:?[]&;".split("");b<c.length;b++)if(c[b]===a)return!1;return!0}function U(){g();for(var a=0,b=[p,Hb,l,Wa,Xa,Ya,Za,$a];a<b.length;a++){var c=(0,b[a])();if(!1!==c)return c}return d()}function V(a){return!1===a?d():a}function ja(a){V(!b());V(c()===a)}function L(a){function b(){ja("[");var a=L();ja("]");return a}void 0===a&&(a=!1);var c=0;for(a=a?[p,k,b,l,Wa,Xa,Ya,Za,$a]:[p,mb,l,Wa,Xa,Ya,Za,$a];c<a.length;c++){var e=(0,a[c])();if(!1!==
e)return e}return d()}function nb(a){if(b())return a;var d=c();if("."===d)return d=L(),G(S,G(Q,G(a),T),d);if(":"===d)return d=L(),G(S,d,a);if("~"===d)return G(W,a);if("@"===d)return d=L(),G(S,G(Q,[1,a,T],T),d);if("?"===d)return G(S,Q,G(W,a));if("/"===d){for(a=[a];;){d=L(!0);a.push(d);if(b())break;d=c();if("/"!==d){e(d);break}}return G(rb,D(a))}e(d);return a}function mb(){if(b())return!1;var a=c();if("&"===a){V(!b());a=c();if("+"===a)return a=L(),G(P,G(C,a));e(a);a=L();return G(P,a)}if(":"===a){V(!b());
a=c();if("&"===a)return ja(">"),a=L(),G(S,G(P,G(Q,T,a)),X);if(">"===a)return a=L(),G(S,G(Q,T,a),X);e(a);a=L();return G(S,a,X)}if("+"===a)return a=L(),G(C,a);if("["===a)return a=L(),ja("]"),nb(a);if("_"===a)return ja(":"),a=L(),G(S,a,T);e(a);a=k();return!1===a?!1:nb(a)}function Hb(){var a=mb();return!1===a?!1:q(a)?a:[3,N,[1,C,[1,a,B]]]}var Va=a,oa=0,Wa=F("$",function(a,b){var c=db(a);return!1===c?d():[5,c,b]}),Xa=F("%",function(a,b){var c=va(b,function(a){return a},function(){return d()});return[6,
a,c]}),Ya=function(a,f){return function(){if(b())return!1;var g=c();if(g!==a)return e(g),!1;g=p();if(!1===g||!u(g))return d();var k=g[2];if(!u(k))return d();var l=k[2];return u(l)&&x(l[2])?f(g[1],k[1],l[1]):d()}}("@",function(a,b,c){c=va(c,function(a){return a},function(){return d()});a=db(a);return!1===a?d():[7,a,b,c]}),Za=F("^",function(a,b){var c=va(b,function(a){return a},function(){return d()});return[8,a,c]}),$a=F(";",function(a,b){return[10,a,b]});return U()}
function Y(a){function b(a,c){function e(a){return c?"["+a+"]":a}if(q(a))return a[1];var d=E(a);if(!1!==d&&3===d.length&&R(d[0],S)){var f=E(d[1]);if(!1!==f&&3===f.length&&R(f[0],Q)){var l=f[1],F=E(l);if(!1!==F&&1===F.length&&R(f[2],T))return e(b(F[0],!0)+"."+b(d[2],!0));if(u(l)&&R(l[2],T)&&R(f[2],T))return e(b(l[1],!0)+"@"+b(d[2],!0));if(R(l,T)&&R(d[2],X))return e(":>"+b(f[2],!0))}l=E(d[2]);if(R(d[1],Q)&&!1!==l&&2===l.length&&R(l[0],W))return e(b(l[1],!0)+"?");if(!1!==f&&2===f.length&&R(d[2],X)&&
R(f[0],P)&&(f=E(f[1]),!1!==f&&3===f.length&&R(f[0],Q)&&R(f[1],T)))return e(":&>"+b(f[2],!0));f=void 0;f=R(d[2],T)?"_":R(d[2],X)?"":b(d[2],!0);return e(f+":"+b(d[1],!0))}if(!1!==d&&2===d.length){if(R(d[0],P))return f=E(d[1]),!1!==f&&2===f.length&&R(f[0],C)?e("&+"+b(f[1],!0)):e("&"+b(d[1],!0));if(R(d[0],W))return e(b(d[1],!0)+"~");if(R(d[0],C))return e("+"+b(d[1],!0));if(R(d[0],rb)&&(d=E(d[1]),!1!==d&&1<d.length)){f=b(d[0],!0);for(l=1;l<d.length;l++)f+="/"+b(d[l],!0);return e(f)}}return c?K(a):K([3,
N,[1,C,[1,a,B]]])}a=qb(K(a));var c="",e="";if(x(a))return"()";if(u(a)){c="(";for(e="";u(a);)c+=e+Y(a[1]),e=" ",a=a[2];return c=x(a)?c+")":c+(" . "+Y(a)+")")}return y(a)?(c=a[1],a=a[2],e=E(a),!1!==e&&2===e.length&&R(c,N)&&R(e[0],C)?b(e[1],!1):"#"+Y([1,c,a])):q(a)?a[1]:n(a)?";("+Y(a[1])+" "+Y(a[2])+")":5===a[0]?"$("+Y(O(a[1]))+" "+Y(a[2])+")":6===a[0]?"%("+Y(a[1])+" "+Y(D(a[2]))+")":7===a[0]?"@("+Y(O(a[1]))+" "+Y(a[2])+" "+Y(D(a[3]))+")":8===a[0]?"^("+Y(a[1])+" "+Y(D(a[2]))+")":h()}
function sb(a,b,c,e,d){void 0===d&&(d=!1);c=A(c);if(y(c)){var f=c[1],g=c[2];if(M(f,tb)){if(g=A(g),u(g)&&(f=g[1],g=A(g[2]),x(g))){if(!1===d){var k=f;f=function(){return a(k,e)}}else{var p=f;f=function(){return sb(a,b,[8,d,p],e)}}return m(f)}}else if(M(f,ub)&&(g=A(g),u(g)&&(f=g[1],g=A(g[2]),u(g)))){var l=g[1];g=A(g[2]);if(x(g)){if(!1===d){var F=f;f=function(){return sb(a,b,F,e,l)}}else f=function(){throw"WIP";};return m(f)}}}return!1===d?m(function(){return b(c,e,a)}):m(function(){return b(c,e,function(c,
e){return m(function(){return sb(a,b,na(d,[c]),e)})})})}function vb(a,b,c){c=J(c);return I(c)?z(a,[c]):b(c)?wb:Z}function xb(a,b,c,e,d){e=J(e);return I(e)?z(a,[e]):b(e)?c(e):d()}
var B=[2],ua=[0,"\u8b2c\u8aa4"],C=[0,"\u592a\u59cb\u521d\u6838"],T=[0,"\u7701\u7565\u4e00\u7269"],za=[3,ua,[1,C,[1,[1,[0,"\u5b87\u5b99\u4ea1\u77e3"],[1,T,B]],B]]],N=[0,"\u7b26\u540d"],P=[0,"\u5f0f\u5f62"],Q=[0,"\u5316\u6ec5"],eb=[3,N,[1,C,[1,[1,P,[1,[1,C,[1,Q,B]],B]],B]]],S=[0,"\u4e00\u985e\u4f55\u7269"],Ka=[3,N,[1,C,[1,[1,S,[1,Q,[1,[0,"\u89e3\u7b97"],B]]],B]]],bb=[0,"\u6620\u8868"],fb=[3,N,[1,C,[1,[1,P,[1,[1,C,[1,P,B]],B]],B]]],gb=[3,N,[1,C,[1,[1,P,[1,P,B]],B]]],jb=[3,N,[1,C,[1,[1,S,[1,P,[1,[0,"\u5f15\u7528"],
B]]],B]]],X=[0,"\u7279\u5b9a\u5176\u7269"],kb=[3,N,[1,C,[1,[1,S,[1,[1,P,[1,[1,Q,[1,T,[1,Q,B]]],B]],[1,X,B]]],B]]],yb=[0,"\u8a3b\u758f"],ob=[3,N,[1,C,[1,[1,S,[1,P,[1,yb,B]]],B]]],W=[0,"\u662f\u975e"],zb=[0,"\u69cb\u7269"],Ca=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,zb,[1,T,B]]],B]],B]]],B]]],Ab=[0,"\u723b\u967d"],wb=[3,Ab,B],Bb=[0,"\u723b\u9670"],Z=[3,Bb,B],Aa=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,zb,B],[1,T,B]]],[1,N,B]]],B]]],Cb=[0,"\u5217\u5e8f"],Ba=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,zb,B],[1,T,B]]],[1,
Cb,B]]],B]]],Ha=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,[0,"\u9593\u7a7a"],[1,T,B]]],B]],B]]],B]]],Db=[0,"\u9023\u9838"],Da=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,Db,[1,T,B]]],B]],B]]],B]]],Ea=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,Db,B],[1,T,B]]],[1,[0,"\u9996\u59cb"],B]]],B]]],Fa=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,Db,B],[1,T,B]]],[1,[0,"\u5c3e\u672b"],B]]],B]]],Ia=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[0,"\u7b49\u540c"],B]],B]]],B]]],La=[3,N,[1,C,[1,[1,S,[1,Q,[1,[0,"\u5982\u82e5"],B]]],B]]],Ja=[3,N,[1,C,
[1,[1,S,[1,[1,Q,[1,[1,Q,T],[1,T,B]]],[1,[0,"\u61c9\u7528"],B]]],B]]],Ga=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,[0,"\u8a5e\u7d20"],[1,T,B]]],B]],B]]],B]]],Eb=[0,"\u4e4b\u7269"],Fb=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,Cb,B],[1,T,B]]],[1,[1,S,[1,Eb,[1,T,B]]],B]]],B]]],ib=[[Ca,1,function(a){return vb.call(this,Ca,y,a)}],[[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,T,[1,zb,B]]],[1,X,B]]],B]]],2,ha],[Aa,1,function(a,b){return xb.call(this,Aa,y,ia,a,b)}],[Ba,1,function(a,b){return xb.call(this,Ba,y,ka,a,b)}],[Ha,1,function(a){return vb.call(this,
Ha,x,a)}],[[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,T,[1,Db,B]]],[1,X,B]]],B]]],2,fa],[Da,1,function(a){return vb.call(this,Da,u,a)}],[Ea,1,function(a,b){return xb.call(this,Ea,u,v,a,b)}],[Fa,1,function(a,b){return xb.call(this,Fa,u,w,a,b)}],[Ia,2,function(a,b){function c(a,b,c,g){c=z(Ia,[c(a),c(b)]);a=z(Ia,[g(a),g(b)]);return z(La,[c,a,Z])}if(a===b)return wb;a=J(a);b=J(b);if(I(a)||I(b))return z(Ia,[a,b]);if(a===b)return wb;!I(a)||h();return x(a)?x(a)?wb:Z:q(a)?q(b)?r(a,b)?wb:Z:Z:y(a)?y(b)?c(a,b,ia,ka):Z:u(a)?
u(b)?c(a,b,v,w):Z:h()}],[Ja,2,function(a,b,c){var e=[];for(b=A(b);u(b);)e.push(b[1]),b=A(b[2]);return x(b)?[8,a,e]:c()}],[Ka,2,function(a,b,c){a=db(a);return!1===a?c():[5,a,b]}],[Ga,1,function(a){return vb.call(this,Ga,q,a)}],[Fb,1,function(a,b){a=J(a);return I(a)?z(Fb,[a]):u(a)?a[1]:b()}],[La,3,function(a,b,c,e){a=J(a);if(I(a))return z(La,[a,b,c]);if(!y(a))return e();a=A(a[1]);return q(a)?r(a,Ab)?b:r(a,Bb)?c:e():e()}],[[3,N,[1,C,[1,[1,S,[1,Q,[1,yb,B]]],B]]],2,ca]],hb=[],rb=[0,"\u5176\u5b50"],Gb=
[0,"\u6548\u61c9"],tb=[3,N,[1,C,[1,[1,rb,[1,[1,Gb,[1,[1,S,[1,Eb,[1,T,B]]],B]],B]],B]]],ub=[3,N,[1,C,[1,[1,rb,[1,[1,Gb,[1,Db,B]],B]],B]]];
module.exports={a:function(){},trampoline_return:aa,trampoline_delay:m,run_trampoline:ba,new_comment:ca,comment_p:n,comment_comment:function(a){return a[1]},comment_x:function(a){return a[2]},un_comment_all:da,atom_p:q,new_atom:function(a){return[0,a]},un_atom:function(a){return a[1]},atom_equal_p:r,new_construction:fa,construction_p:u,construction_head:v,construction_tail:w,null_v:B,null_p:x,new_data:ha,data_p:y,data_name:ia,data_list:ka,just_p:la,evaluate:function(a,b){return[5,a,b]},apply:na,force_all_rec:pa,
force_uncomment_all_rec:qa,unlazy_all_rec:qa,jsArray_to_list:D,maybe_list_to_jsArray:E,new_list:G,un_just_all:H,un_just_comment_all:function(a){for(;la(a)||n(a);)a=H(da(a));return a},delay_p:wa,delay_just_p:I,lazy_p:xa,delay_env:function(a){return ya(a)[1]},delay_x:function(a){return ya(a)[2]},force1:J,force_all:function(a){return A(a)},force_uncomment_all:ra,force_uncomment1:function(a){return n(a)?a[2]:J(a)},unlazy1:Qa,env_null_v:hb,env_set:Ta,env_get:Ua,env2val:O,env_foreach:cb,val2env:db,equal_p:M,
simple_print:K,complex_parse:qb,complex_print:Y,machinetext_parse:function(a){function b(a){void 0===a&&(a="");throw"MT parse ERROR "+a;}function c(a){if(!a)return b()}function e(){c(0!==f);f--;return a[f]}function d(a){var c=g.pop(),d=g.pop();return void 0===d||void 0===c?b():g.unshift(a(d,c))}for(var f=a.length,g=[];0!==f;){var k=e();if("^"===k){for(k="";;){var p=e();if("^"===p)break;k=p+k}g.unshift([0,k])}else if("."===k)d(fa);else if("#"===k)d(ha);else if("$"===k)d(function(a,c){var d=db(a);return!1===
d?b():[5,d,c]});else if("_"===k)g.unshift(B);else return b()}c(0===f);c(1===g.length);return g[0]},machinetext_print:function(a){function b(){for(var a=[],b=0,g=c;b<g.length;b++){var k=g[b];k=H(k);var p=function(b,c,d,f){e+=c;return a.push(d(b),f(b))};if(q(k))e+="^"+k[1]+"^";else if(u(k))p(k,".",v,w);else if(x(k))e+="_";else if(y(k))p(k,"#",ia,ka);else if(wa(k))k=ya(k),p(k,"$",function(a){return O(a[1])},ma);else return{value:h()}}c=a}for(var c=[a],e="";0!==c.length;)if(a=b(),"object"===typeof a)return a.value;
return e},return_effect_systemName:tb,bind_effect_systemName:ub,new_effect_bind:function(a,b){return[3,ub,G(a,b)]},new_effect_return:function(a){return[3,tb,a]},run_monad_trampoline:function(a,b,c,e){return sb(a,b,c,e)},run_monad_stackoverflow:function(a,b,c,e){return ba(sb(function(b,c){return aa(a(b,c))},function(a,c,e){return aa(b(a,c,function(a,b){return ba(e(a,b))}))},c,e))}};
