function g(){throw"TheLanguage PANIC";}function aa(a,b){return[11,a,b]}exports.new_comment=aa;exports.comment_p=function(a){return 11===a[0]};exports.comment_comment=function(a){return a[1]};exports.comment_x=function(a){return a[2]};function q(a){a in ba||g();return[0,ba[a]]}exports.new_symbol=q;function u(a){return 0===a[0]}exports.symbol_p=u;function ca(a){return da[a[1]]}exports.un_symbol=ca;function ea(a,b){return[1,a,b]}exports.new_construction=ea;function w(a){return 1===a[0]}
exports.construction_p=w;function fa(a){return a[1]}exports.construction_head=fa;function ha(a){return a[2]}exports.construction_tail=ha;var x=[2];exports.null_v=x;function y(a){return 2===a[0]}exports.null_p=y;function ia(a,b){return[3,a,b]}exports.new_data=ia;function z(a){return 3===a[0]}exports.data_p=z;function ja(a){return a[1]}exports.data_name=ja;function ka(a){return a[2]}exports.data_list=ka;function la(a,b){return[4,a,b]}exports.new_error=la;function B(a){return 4===a[0]}
exports.error_p=B;function ma(a){return a[1]}exports.error_name=ma;function na(a){return a[2]}exports.error_list=na;function oa(a){return 5===a[0]}exports.just_p=oa;exports.evaluate=function(a,b){return[6,a,b]};function pa(a){return a[2]}function C(a,b){return[7,a,b]}exports.apply=function(a,b){return[9,a,b]};function qa(a){a=D(a);if(z(a)||B(a)||w(a)){var b=a[2];a[1]=qa(a[1]);a[2]=qa(b)}return a}exports.force_all_rec=qa;function F(a,b){a!==b&&(a[0]=5,a[1]=b,a[2]=!1,a[3]=!1)}
function ua(a,b){10===a[0]||g();a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3]}
var ba={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z",a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z","\u4e00\u985e\u4f55\u7269":"\u3749","\u4e4b\u7269":"\ud86d\ude66","\u5176\u5b50":"\ud85a\udfaa","\u51fa\u5165\u6539\u6ec5":"\ud849\udc9f",
"\u5217\u5e8f":"\ud841\udf3a","\u5316\u6ec5":"\ud840\udfc1","\u53c3\u5f62":"\ud842\udef0","\u543e\u81ea":"\ud85a\udcf9","\u592a\u59cb\u521d\u6838":"\ud84d\udf57","\u5982\u82e5":"\ud85b\udc61","\u5b87\u5b99\u4ea1\u77e3":"\ud863\ude79","\u5c3e\u672b":"\ud847\udcb5","\u5e8f\u4e01":"\ud840\udda4","\u5e8f\u4e19":"\ud840\uddee","\u5e8f\u4e59":"\u3408","\u5e8f\u7532":"\ud840\uddda","\u5f0f\u5f62":"\u4f71","\u5f15\u7528":"\u39c8","\u61c9\u7528":"\ud853\udc06","\u6548\u61c9":"\u52b9","\u6620\u8868":"\ud850\udd54",
"\u662f\u975e":"\u6b24","\u69cb\u7269":"\ud845\udcab","\u70ba\u7b26\u540d\u9023":"\u2010","\u7279\u5b9a\u5176\u7269":"\u4e93","\u7701\u7565\u4e00\u7269":"\u7567","\u7b26\u540d":"\u8b3c","\u7b49\u540c":"\u5f0c","\u89e3\u7b97":"\u7b6d","\u8a3b\u758f":"\u758e","\u8a5e\u7d20":"\ud85e\udd5d","\u8b2c\u8aa4":"\u4958","\u9023\u9838":"\u4e29","\u9593\u7a7a":"\ud84e\udcd3","\u9670":"\u4f8c","\u967d":"\ud84c\udd84","\u9996\u59cb":"\ud866\udc10"},da={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",
A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z",a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z","\u3749":"\u4e00\u985e\u4f55\u7269","\ud86d\ude66":"\u4e4b\u7269","\ud85a\udfaa":"\u5176\u5b50","\ud849\udc9f":"\u51fa\u5165\u6539\u6ec5","\ud841\udf3a":"\u5217\u5e8f","\ud840\udfc1":"\u5316\u6ec5",
"\ud842\udef0":"\u53c3\u5f62","\ud85a\udcf9":"\u543e\u81ea","\ud84d\udf57":"\u592a\u59cb\u521d\u6838","\ud85b\udc61":"\u5982\u82e5","\ud863\ude79":"\u5b87\u5b99\u4ea1\u77e3","\ud847\udcb5":"\u5c3e\u672b","\ud840\udda4":"\u5e8f\u4e01","\ud840\uddee":"\u5e8f\u4e19","\u3408":"\u5e8f\u4e59","\ud840\uddda":"\u5e8f\u7532","\u4f71":"\u5f0f\u5f62","\u39c8":"\u5f15\u7528","\ud853\udc06":"\u61c9\u7528","\u52b9":"\u6548\u61c9","\ud850\udd54":"\u6620\u8868","\u6b24":"\u662f\u975e","\ud845\udcab":"\u69cb\u7269",
"\u2010":"\u70ba\u7b26\u540d\u9023","\u4e93":"\u7279\u5b9a\u5176\u7269","\u7567":"\u7701\u7565\u4e00\u7269","\u8b3c":"\u7b26\u540d","\u5f0c":"\u7b49\u540c","\u7b6d":"\u89e3\u7b97","\u758e":"\u8a3b\u758f","\ud85e\udd5d":"\u8a5e\u7d20","\u4958":"\u8b2c\u8aa4","\u4e29":"\u9023\u9838","\ud84e\udcd3":"\u9593\u7a7a","\u4f8c":"\u9670","\ud84c\udd84":"\u967d","\ud866\udc10":"\u9996\u59cb"},G=q("\u592a\u59cb\u521d\u6838"),va=q("\u7b26\u540d"),H=q("\u5316\u6ec5"),I=q("\u5f0f\u5f62"),wa=q("\u7b49\u540c"),xa=
q("\u89e3\u7b97"),ya=q("\u7279\u5b9a\u5176\u7269"),J=q("\u7701\u7565\u4e00\u7269"),za=q("\u6620\u8868"),Aa=q("\u5982\u82e5"),L=q("\u4e00\u985e\u4f55\u7269"),Ca=q("\u662f\u975e"),Da=q("\u5176\u5b50"),Ea=q("\u967d"),Fa=q("\u9670"),Ga=q("\u5f15\u7528"),Ha=q("\u61c9\u7528"),Ia=q("\u9593\u7a7a"),Ja=q("\u9023\u9838"),Ka=q("\u69cb\u7269"),La=q("\u8b2c\u8aa4"),Ma=q("\u8a5e\u7d20"),Na=q("\u5217\u5e8f"),Oa=q("\u9996\u59cb"),Pa=q("\u5c3e\u672b"),Qa=q("\u4e4b\u7269"),Ra=q("\u5b87\u5b99\u4ea1\u77e3"),Sa=q("\u8a3b\u758f"),
Ta=[4,G,M(Ra,J)];function N(a){return[3,va,M(G,a)]}function Ua(a){return N(M(L,M(H,J,a),ya))}function Va(a,b){return N(M(L,M(H,M(a),J),b))}function Wa(a){return N(M(L,H,M(Ca,M(L,a,J))))}
var bb=Ua(Ka),cb=Va(Ka,va),db=Va(Ka,Na),eb=Wa(Ka),fb=Ua(La),gb=Va(La,va),hb=Va(La,Na),ib=Wa(La),jb=Ua(Ja),kb=Wa(Ja),lb=Va(Ja,Oa),mb=Va(Ja,Pa),nb=Wa(Ma),ob=Wa(Ia),pb=N(M(L,H,M(Ca,wa))),qb=N(M(L,M(H,[1,H,J],J),Ha)),rb=N(M(L,H,xa)),sb=Va(Na,M(L,Qa,J)),tb=N(M(L,H,Aa)),ub=N(M(L,I,Ga)),vb=N(M(L,M(I,M(H,J,H)),ya)),wb=N(M(I,M(G,H))),yb=N(M(I,M(G,I))),zb=N(M(I,I)),Ab=N(M(L,H,Sa)),Bb=N(M(L,I,Sa)),Cb=[3,Fa,M()],Db=[3,Ea,M()];function Eb(a,b){return a===b?!0:a[1]===b[1]?(F(a,b),!0):!1}
function O(a){for(var b=x,c=a.length-1;0<=c;c--)b=[1,a[c],b];return b}exports.jsArray_to_list=O;function Fb(a,b,c){for(var d=[];w(a);)d.push(a[1]),a=a[2];return y(a)?b(d):c(d,a)}function P(a){return Fb(a,function(b){return b},function(){return!1})}exports.maybe_list_to_jsArray=P;function M(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return O(a)}exports.new_list=M;function Gb(a){for(var b=[];oa(a);)b.push(a),a=a[1];for(var c=0;c<b.length;c++)F(b[c],a);return a}exports.un_just=Gb;
function Hb(a){return 6===a[0]||8===a[0]||7===a[0]||9===a[0]}exports.delay_p=Hb;function Q(a){return oa(a)||Hb(a)}exports.delay_just_p=Q;function Ib(a){if(6===a[0])return a;if(8===a[0])throw"WIP";if(7===a[0])throw"WIP";if(9===a[0])throw"WIP";return g()}exports.delay_env=function(a){return Ib(a)[1]};exports.delay_x=function(a){return Ib(a)[2]};
function D(a,b,c,d){function e(v){F(p,v);for(var K=0;K<d.length;K++)F(d[K],v);return v}function l(){c[1]=!0;return m(Ta)}function m(v){e(v);return Q(v)?(d.push(p),D(v,b,[!1,!1],d)):v}function h(){var v={},K;for(K in n)v[K]=!0;for(K in b)v[K]=!0;return v}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);void 0===d&&(d=[]);var n={},p=a;for(a=0;Q(p)&&32>a;a++)d.push(p),p=S(p);for(;Q(p);){a=U(p);if(!0===b[a])return l();if(!0===n[a]){c[0]=!0;if(6===p[0])return l();if(7===p[0]){a=p[1];for(var E=p[2],R=!1,T=0,
W=[cb,db,eb,gb,hb,ib,kb,lb,mb,nb,ob];T<W.length;T++)if(V(W[T],a)){R=!0;break}if(R)return 1===E.length||g(),!1===c[1]||g(),E=D(E[0],h(),c),c[1]?m(C(a,[E])):g();if(V(a,pb)||V(a,qb)||V(a,rb))return l();if(V(a,tb)&&(3===E.length||g(),!1===c[1]||g(),a=D(E[0],h(),c),c[1]))return m(C(tb,[a,E[1],E[2]]))}else if(8===p[0]||9===p[0])return l();return g()}n[a]=!0;d.push(p);p=S(p)}return e(p)}
function S(a){var b=Gb(a);!oa(b)||g();if(6===b[0])a=Jb(b[1],b[2],a);else if(8===b[0]){a=b[1];var c=b[2],d=b[3],e=[4,G,M(yb,M(X(a),c,O(d)))];a=V(c,ub)?1!==d.length?e:d[0]:V(c,vb)?2!==d.length?e:Kb(a,d[0],d[1],e):V(c,Bb)?2!==d.length?e:[11,d[0],[6,a,d[1]]]:e}else if(7===b[0])a:{e=b[1];a=b[2];c=[4,G,M(wb,M(e,O(a)))];for(d=0;d<Lb.length;d++)if(V(e,Lb[d][0])){e=Lb[d][1];if(a.length!==e)break;d=Lb[d][2];a=1===e?d(a[0],c):2===e?d(a[0],a[1],c):3===e?d(a[0],a[1],a[2],c):g();break a}a=c}else a=9===b[0]?Mb(b[1],
b[2],a):b;a=Gb(a);F(b,a);return a}exports.force1=S;exports.force_all=function(a){return D(a)};var Nb=[];exports.env_null_v=Nb;function Ob(a,b,c){for(var d=[],e=0;e<a.length;e+=2){if(V(a[e+0],b)){d[e+0]=b;d[e+1]=c;for(e+=2;e<a.length;e+=2)d[e+0]=a[e+0],d[e+1]=a[e+1];return d}d[e+0]=a[e+0];d[e+1]=a[e+1]}d[a.length+0]=b;d[a.length+1]=c;return d}exports.env_set=Ob;function Pb(a,b,c){for(var d=0;d<a.length;d+=2)if(V(a[d+0],b))return a[d+1];return c}exports.env_get=Pb;
function Qb(a,b){for(var c=0;c<a.length;c+=2)if(V(a[c+0],b))return a[c+1];return g()}function X(a){for(var b=x,c=0;c<a.length;c+=2)b=[1,M(a[c+0],a[c+1]),b];return[3,za,M(b)]}exports.env2val=X;function Rb(a,b){for(var c=0;c<a.length;c+=2)b(a[c+0],a[c+1])}exports.env_foreach=Rb;
function Sb(a){a=D(a);if(!z(a))return!1;var b=D(a[1]);if(!u(b)||!Eb(b,za))return!1;b=D(a[2]);if(!w(b)||!y(D(b[2])))return!1;a=[];for(b=D(b[1]);!y(b);){if(!w(b))return!1;var c=D(b[1]);b=D(b[2]);if(!w(c))return!1;var d=c[1];c=D(c[2]);if(!w(c))return!1;var e=c[1];if(!y(D(c[2])))return!1;c=!0;for(var l=0;l<a.length;l+=2)if(V(a[l+0],d)){a[l+1]=e;c=!1;break}c&&(a.push(d),a.push(e))}return a}exports.val2env=Sb;
function Jb(a,b,c){var d=S(b);if(Q(d))return c;var e=[4,G,M(wb,M(rb,M(X(a),d)))];if(w(d)){for(b=[];!y(d);){if(Q(d))return c;if(w(d))b.push(d[1]),d=S(d[2]);else return e}if(V(b[0],yb)){if(1===b.length)return e;d=b[1];c=[];for(e=2;e<b.length;e++)c.push(b[e]);return[8,a,d,c]}if(V(b[0],zb)){if(1===b.length)return e;d=D([6,a,b[1]]);if(!z(d))return e;var l=S(d[1]);if(Q(l))return c;if(!u(l)||!Eb(l,I))return e;l=S(d[2]);if(Q(l))return c;if(!w(l))return e;d=l[1];l=S(l[2]);if(Q(l))return c;if(!y(l))return e;
c=[X(a)];for(e=2;e<b.length;e++)c.push(b[e]);return[9,d,c]}if(V(b[0],wb)){if(1===b.length)return e;d=b[1];c=[];for(e=2;e<b.length;e++)c.push([6,a,b[e]]);return[7,d,c]}d=[6,a,b[0]];c=[];for(e=1;e<b.length;e++)c.push([6,a,b[e]]);return[9,d,c]}return y(d)?d:u(d)||z(d)?Pb(a,d,e):B(d)?e:g()}function Tb(a,b){return[a,1,function(c){c=S(c);return Q(c)?C(a,[c]):b(c)?Db:Cb}]}function Ub(a,b,c){return[a,1,function(d,e){d=S(d);return Q(d)?C(a,[d]):b(d)?c(d):e}]}
var Lb=[Tb(eb,z),[bb,2,ia],Ub(cb,z,ja),Ub(db,z,ka),Tb(ib,B),[fb,2,la],Ub(gb,B,ma),Ub(hb,B,na),Tb(ob,y),[jb,2,ea],Tb(kb,w),Ub(lb,w,fa),Ub(mb,w,ha),[pb,2,function(a,b){function c(d,e,l,m){l=C(pb,[l(d),l(e)]);d=C(pb,[m(d),m(e)]);return C(tb,[l,d,Cb])}if(a===b)return Db;a=S(a);b=S(b);if(Q(a)||Q(b))return C(pb,[a,b]);if(a===b)return Db;!Q(a)||g();return y(a)?y(a)?Db:Cb:u(a)?u(b)?Eb(a,b)?Db:Cb:Cb:z(a)?z(b)?c(a,b,ja,ka):Cb:w(a)?w(b)?c(a,b,fa,ha):Cb:B(a)?B(b)?c(a,b,ma,na):Cb:g()}],[qb,2,function(a,b,c){var d=
[];for(b=D(b);w(b);)d.push(b[1]),b=D(b[2]);return y(b)?[9,a,d]:c}],[rb,2,function(a,b,c){a=Sb(a);return!1===a?c:[6,a,b]}],Tb(nb,u),[sb,1,function(a,b){a=S(a);return Q(a)?C(sb,[a]):w(a)?a[1]:b}],[tb,3,function(a,b,c,d){a=S(a);if(Q(a))return C(tb,[a,b,c]);if(!z(a))return d;a=D(a[1]);return u(a)?Eb(a,Ea)?b:Eb(a,Fa)?c:d:d}],[Ab,2,aa]];
function Mb(a,b,c){function d(){return[4,G,M(wb,M(qb,M(a,O(b))))]}a=S(a);if(Q(a))return c;if(!z(a))return d();c=D(a[1]);if(!u(c)||!Eb(c,H))return d();var e=D(a[2]);if(!w(e))return d();c=qa(e[1]);e=D(e[2]);if(!w(e)||!y(D(e[2])))return d();e=e[1];for(var l=Nb,m=0;!y(c);)if(u(c)||z(c)){for(var h=x,n=b.length-1;n>=m;n--)h=[1,b[n],h];l=Ob(l,c,h);m=b.length;c=x}else if(w(c))if(m<b.length)h=b[m],m++,l=Ob(l,c[1],h),c=c[2];else return d();else return d();return b.length!==m?d():[6,l,e]}
function Kb(a,b,c,d){void 0===d&&(d=!1);b=qa(b);for(var e=[],l=!1,m=b;!y(m);)if(u(m)||z(m))e.push(m),l=!0,m=x;else if(w(m))e.push(m[1]),m=m[2];else return!1===d?la(G,M(yb,M(X(a),vb,O([b,c])))):d;d=b;l&&(d=O(e));var h=[];Rb(a,function(n){for(var p=0;p<e.length;p++)if(V(e[p],n))return;h.push(n)});l=d;for(m=h.length-1;0<=m;m--)l=[1,h[m],l];for(m=h.length-1;0<=m;m--)d=ea(M(yb,ub,Qb(a,h[m])),d);return[3,H,M(b,[1,M(yb,ub,[3,H,M(l,c)]),d])]}
function V(a,b){function c(d,e,l,m){return V(l(d),l(e))&&V(m(d),m(e))?(F(d,e),!0):!1}if(a===b)return!0;a=D(a);b=D(b);if(a===b)return!0;if(y(a)){if(!y(b))return!1;F(a,x);F(b,x);return!0}return u(a)?u(b)?Eb(a,b):!1:w(a)?w(b)?c(a,b,fa,ha):!1:B(a)?B(b)?c(a,b,ma,na):!1:z(a)?z(b)?c(a,b,ja,ka):!1:g()}exports.equal_p=V;
function Y(a,b){function c(d,e,l,m){return Y(l(d),l(e))&&Y(m(d),m(e))?(F(d,e),!0):!1}if(a===b)return!0;a=Gb(a);b=Gb(b);if(a===b)return!0;if(y(a)){if(!y(b))return!1;F(a,x);F(b,x);return!0}if(u(a))return u(b)?Eb(a,b):!1;if(w(a))return w(b)?c(a,b,fa,ha):!1;if(B(a))return B(b)?c(a,b,ma,na):!1;if(z(a))return z(b)?c(a,b,ja,ka):!1;if(6===a[0])throw"WIP";if(7===a[0])throw"WIP";if(8===a[0])throw"WIP";if(9===a[0])throw"WIP";return g()}
function U(a){a=Gb(a);var b;if(y(a))return"()";if(w(a)){var c="(";for(b="";w(a);)c+=b+U(a[1]),b=" ",a=Gb(a[2]);return c=y(a)?c+")":c+(" . "+U(a)+")")}return z(a)?"#"+U([1,a[1],a[2]]):B(a)?"!"+U([1,a[1],a[2]]):u(a)?ca(a):6===a[0]?"$("+U(X(a[1]))+" "+U(a[2])+")":7===a[0]?"%("+U(a[1])+" "+U(O(a[2]))+")":8===a[0]?"@("+U(X(a[1]))+" "+U(a[2])+" "+U(O(a[3]))+")":9===a[0]?"^("+U(a[1])+" "+U(O(a[2]))+")":g()}exports.simple_print=U;exports.simple_print_force_all_rec=function(a){return U(qa(a))};
function Vb(a){function b(){return ra.length===Ba}function c(){!b()||g();var f=ra[Ba];Ba++;return f}function d(f){ra[Ba-1]===f||g();Ba--}function e(f){void 0===f&&(f="");throw"TheLanguage parse ERROR!"+f;}function l(f){return" "===f||"\n"===f||"\t"===f||"\r"===f}function m(){if(b())return!1;var f=c();if(!l(f))return d(f),!1;for(;l(f)&&!b();)f=c();l(f)||d(f);return!0}function h(){if(b())return!1;var f=c(),t="";if(!T(f))return d(f),!1;for(;T(f)&&!b();)t+=f,f=c();T(f)?t+=f:d(f);t in ba||e("Not Symbol"+
t);return q(t)}function n(){if(b())return!1;var f=c();if("("!==f)return d(f),!1;for(var t=[10],k=t;;){m();if(b())return e();f=c();if(")"===f)return ua(t,x),k;if("."===f){m();f=W();ua(t,f);m();if(b())return e();f=c();return")"!==f?e():k}d(f);f=W();var r=[10];ua(t,[1,f,r]);t=r}}function p(){if(b())return!1;var f=c();if("#"!==f)return d(f),!1;f=n();return!1!==f&&w(f)?[3,f[1],f[2]]:e()}function E(){if(b())return!1;var f=c();if("!"!==f)return d(f),!1;f=n();return!1!==f&&w(f)?[4,f[1],f[2]]:e()}function R(f,
t){return function(){if(b())return!1;var k=c();if(k!==f)return d(k),!1;k=n();if(!1===k||!w(k))return e();var r=k[2];return w(r)&&y(r[2])?t(k[1],r[1]):e()}}function T(f){if(l(f))return!1;for(var t="()!#.$%^@~/->_:?[]&".split(""),k=0;k<t.length;k++)if(f===t[k])return!1;return!0}function W(){m();for(var f=[n,sa,p,E,Xa,Ya,Za,$a],t=0;t<f.length;t++){var k=f[t]();if(!1!==k)return k}return e()}function v(f){return!1===f?e():f}function K(f){v(!b());v(c()===f)}function ta(){function f(r){function A(){K("[");
var Wb=f();K("]");return Wb}void 0===r&&(r=!1);r=r?[n,h,A,p,E,Xa,Ya,Za,$a]:[n,ta,p,E,Xa,Ya,Za,$a];for(var ab=0;ab<r.length;ab++){var xb=r[ab]();if(!1!==xb)return xb}return e()}function t(r){if(b())return r;var A=c();if("."===A)return A=f(),M(L,M(H,M(r),J),A);if(":"===A)return A=f(),M(L,A,r);if("~"===A)return M(Ca,r);if("@"===A)return A=f(),M(L,M(H,[1,r,J],J),A);if("?"===A)return M(L,H,M(Ca,r));if("/"===A){for(r=[r];;){A=f(!0);r.push(A);if(b())break;A=c();if("/"!==A){d(A);break}}return M(Da,O(r))}d(A);
return r}if(b())return!1;var k=c();if("&"===k){v(!b());k=c();if("+"===k)return k=f(),M(I,M(G,k));d(k);k=f();return M(I,k)}if(":"===k){v(!b());k=c();if("&"===k)return K(">"),k=f(),M(L,M(I,M(H,J,k)),ya);if(">"===k)return k=f(),M(L,M(H,J,k),ya);d(k);k=f();return M(L,k,ya)}if("+"===k)return k=f(),M(G,k);if("["===k)return k=f(),K("]"),t(k);if("_"===k)return K(":"),k=f(),M(L,k,J);d(k);k=h();return!1===k?!1:t(k)}function sa(){var f=ta();return!1===f?!1:u(f)?f:N(f)}var ra=a,Ba=0,Xa=R("$",function(f,t){var k=
Sb(f);return!1===k?e():[6,k,t]}),Ya=R("%",function(f,t){var k=Fb(t,function(r){return r},function(){return e()});return[7,f,k]}),Za=function(f,t){return function(){if(b())return!1;var k=c();if(k!==f)return d(k),!1;k=n();if(!1===k||!w(k))return e();var r=k[2];if(!w(r))return e();var A=r[2];return w(A)&&y(A[2])?t(k[1],r[1],A[1]):e()}}("@",function(f,t,k){k=Fb(k,function(r){return r},function(){return e()});f=Sb(f);return!1===f?e():[8,f,t,k]}),$a=R("^",function(f,t){var k=Fb(t,function(r){return r},
function(){return e()});return[9,f,k]});return W()}exports.complex_parse=Vb;
function Z(a){function b(e,l){function m(R){return"inner"===l?"["+R+"]":"top"===l?R:g()}if(u(e))return ca(e);var h=P(e);if(!1!==h&&3===h.length&&Y(h[0],L)){var n=P(h[1]);if(!1!==n&&3===n.length&&Y(n[0],H)){var p=n[1],E=P(p);if(!1!==E&&1===E.length&&Y(n[2],J))return m(b(E[0],"inner")+"."+b(h[2],"inner"));if(w(p)&&Y(p[2],J)&&Y(n[2],J))return m(b(p[1],"inner")+"@"+b(h[2],"inner"));if(Y(p,J)&&Y(h[2],ya))return m(":>"+b(n[2],"inner"))}p=P(h[2]);if(Y(h[1],H)&&!1!==p&&2===p.length&&Y(p[0],Ca))return m(b(p[1],
"inner")+"?");if(!1!==n&&2===n.length&&Y(h[2],ya)&&Y(n[0],I)&&(n=P(n[1]),!1!==n&&3===n.length&&Y(n[0],H)&&Y(n[1],J)))return m(":&>"+b(n[2],"inner"));n=Y(h[2],J)?"_":Y(h[2],ya)?"":b(h[2],"inner");return m(n+":"+b(h[1],"inner"))}if(!1!==h&&2===h.length){if(Y(h[0],I))return n=P(h[1]),!1!==n&&2===n.length&&Y(n[0],G)?m("&+"+b(n[1],"inner")):m("&"+b(h[1],"inner"));if(Y(h[0],Ca))return m(b(h[1],"inner")+"~");if(Y(h[0],G))return m("+"+b(h[1],"inner"));if(Y(h[0],Da)&&(h=P(h[1]),!1!==h&&1<h.length)){n=b(h[0],
"inner");for(p=1;p<h.length;p++)n+="/"+b(h[p],"inner");return m(n)}}return"inner"===l?U(e):"top"===l?U(N(e)):g()}a=Vb(U(a));var c="",d="";if(y(a))return"()";if(w(a)){c="(";for(d="";w(a);)c+=d+Z(a[1]),d=" ",a=a[2];return c=y(a)?c+")":c+(" . "+Z(a)+")")}return z(a)?(c=a[1],a=a[2],d=P(a),!1!==d&&2===d.length&&Y(c,va)&&Y(d[0],G)?b(d[1],"top"):"#"+Z([1,c,a])):B(a)?"!"+Z([1,a[1],a[2]]):u(a)?ca(a):6===a[0]?"$("+Z(X(a[1]))+" "+Z(a[2])+")":7===a[0]?"%("+Z(a[1])+" "+Z(O(a[2]))+")":8===a[0]?"@("+Z(X(a[1]))+
" "+Z(a[2])+" "+Z(O(a[3]))+")":9===a[0]?"^("+Z(a[1])+" "+Z(O(a[2]))+")":g()}exports.complex_print=Z;
exports.machinetext_parse=function(a){function b(){function h(T){function W(ta){var sa=[10],ra=[10];n.push(sa);n.push(ra);ua(T,ta(sa,ra))}var v=c();if("^"===v){for(v="";;){var K=c();if("^"===K)break;v+=K}ua(T,[0,v])}else if("."===v)W(ea);else if("#"===v)W(ia);else if("!"===v)W(la);else if("$"===v)W(function(ta,sa){return[6,Nb,M(wb,rb,M(yb,ub,ta),M(yb,ub,sa))]});else if("_"===v)ua(T,x);else throw"MT parse ERROR";}for(var n=[],p=0,E=e;p<E.length;p++){var R=h(E[p]);if("object"===typeof R)return R}e=
n}function c(){if(!(a.length>l))throw"MT parse ERROR";var h=a[l];l++;return h}for(var d=[10],e=[d],l=0;0!==e.length;){var m=b();if("object"===typeof m)return m.value}if(l!=a.length)throw"MT parse ERROR";return d};
exports.machinetext_print=function(a){function b(){for(var e=[],l=0,m=c;l<m.length;l++){var h=m[l];h=Gb(h);var n=function(p,E,R,T){d+=E;e.push(R(p));e.push(T(p))};if(u(h))d+="^",d+=h[1],d+="^";else if(w(h))n(h,".",fa,ha);else if(y(h))d+="_";else if(z(h))n(h,"#",ja,ka);else if(B(h))n(h,"!",ma,na);else if(Hb(h))h=Ib(h),n(h,"$",function(p){return X(p[1])},pa);else return{value:g()}}c=e}for(var c=[a],d="";0!==c.length;)if(a=b(),"object"===typeof a)return a.value;return d};
