function g(){throw"TheLanguage PANIC";}function aa(a,b){return[11,a,b]}exports.new_comment=aa;exports.comment_p=function(a){return 11===a[0]};exports.comment_comment=function(a){return a[1]};exports.comment_x=function(a){return a[2]};
var ba={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z",a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z","\u4e00\u985e\u4f55\u7269":"\u3749","\u4e4b\u7269":"\ud86d\ude66","\u5176\u5b50":"\ud85a\udfaa","\u51fa\u5165\u6539\u6ec5":"\ud849\udc9f",
"\u5217\u5e8f":"\ud841\udf3a","\u5316\u6ec5":"\ud840\udfc1","\u53c3\u5f62":"\ud842\udef0","\u543e\u81ea":"\ud85a\udcf9","\u592a\u59cb\u521d\u6838":"\ud84d\udf57","\u5982\u82e5":"\ud85b\udc61","\u5b87\u5b99\u4ea1\u77e3":"\ud863\ude79","\u5c3e\u672b":"\ud847\udcb5","\u5e8f\u4e01":"\ud840\udda4","\u5e8f\u4e19":"\ud840\uddee","\u5e8f\u4e59":"\u3408","\u5e8f\u7532":"\ud840\uddda","\u5f0f\u5f62":"\u4f71","\u5f15\u7528":"\u39c8","\u61c9\u7528":"\ud853\udc06","\u6548\u61c9":"\u52b9","\u6620\u8868":"\ud850\udd54",
"\u662f\u975e":"\u6b24","\u69cb\u7269":"\ud845\udcab","\u70ba\u7b26\u540d\u9023":"\u2010","\u7279\u5b9a\u5176\u7269":"\u4e93","\u7701\u7565\u4e00\u7269":"\u7567","\u7b26\u540d":"\u8b3c","\u7b49\u540c":"\u5f0c","\u89e3\u7b97":"\u7b6d","\u8a3b\u758f":"\u758e","\u8a5e\u7d20":"\ud85e\udd5d","\u8b2c\u8aa4":"\u4958","\u9023\u9838":"\u4e29","\u9593\u7a7a":"\ud84e\udcd3","\u9670":"\u4f8c","\u967d":"\ud84c\udd84","\u9996\u59cb":"\ud866\udc10"},ca={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",
A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z",a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z","\u3749":"\u4e00\u985e\u4f55\u7269","\ud86d\ude66":"\u4e4b\u7269","\ud85a\udfaa":"\u5176\u5b50","\ud849\udc9f":"\u51fa\u5165\u6539\u6ec5","\ud841\udf3a":"\u5217\u5e8f","\ud840\udfc1":"\u5316\u6ec5",
"\ud842\udef0":"\u53c3\u5f62","\ud85a\udcf9":"\u543e\u81ea","\ud84d\udf57":"\u592a\u59cb\u521d\u6838","\ud85b\udc61":"\u5982\u82e5","\ud863\ude79":"\u5b87\u5b99\u4ea1\u77e3","\ud847\udcb5":"\u5c3e\u672b","\ud840\udda4":"\u5e8f\u4e01","\ud840\uddee":"\u5e8f\u4e19","\u3408":"\u5e8f\u4e59","\ud840\uddda":"\u5e8f\u7532","\u4f71":"\u5f0f\u5f62","\u39c8":"\u5f15\u7528","\ud853\udc06":"\u61c9\u7528","\u52b9":"\u6548\u61c9","\ud850\udd54":"\u6620\u8868","\u6b24":"\u662f\u975e","\ud845\udcab":"\u69cb\u7269",
"\u2010":"\u70ba\u7b26\u540d\u9023","\u4e93":"\u7279\u5b9a\u5176\u7269","\u7567":"\u7701\u7565\u4e00\u7269","\u8b3c":"\u7b26\u540d","\u5f0c":"\u7b49\u540c","\u7b6d":"\u89e3\u7b97","\u758e":"\u8a3b\u758f","\ud85e\udd5d":"\u8a5e\u7d20","\u4958":"\u8b2c\u8aa4","\u4e29":"\u9023\u9838","\ud84e\udcd3":"\u9593\u7a7a","\u4f8c":"\u9670","\ud84c\udd84":"\u967d","\ud866\udc10":"\u9996\u59cb"};function q(a){return 0===a[0]}exports.symbol_p=q;function da(a){return a in ba}exports.can_new_symbol_p=da;
function t(a){return[0,ba[a]]}exports.new_symbol=t;function ea(a){return ca[a[1]]}exports.un_symbol=ea;function fa(a,b){return[1,a,b]}exports.new_construction=fa;function u(a){return 1===a[0]}exports.construction_p=u;function ha(a){return a[1]}exports.construction_head=ha;function ia(a){return a[2]}exports.construction_tail=ia;var v=[2];exports.null_v=v;function x(a){return 2===a[0]}exports.null_p=x;function ja(a,b){return[3,a,b]}exports.new_data=ja;function z(a){return 3===a[0]}exports.data_p=z;
function ka(a){return a[1]}exports.data_name=ka;function la(a){return a[2]}exports.data_list=la;function ma(a,b){return[4,a,b]}exports.new_error=ma;function A(a){return 4===a[0]}exports.error_p=A;function na(a){return a[1]}exports.error_name=na;function oa(a){return a[2]}exports.error_list=oa;function pa(a){return 5===a[0]}exports.just_p=pa;exports.evaluate=function(a,b){return[6,a,b]};function qa(a){return a[2]}function B(a,b){return[7,a,b]}function ua(a,b){return[9,a,b]}exports.apply=ua;
function va(a){a=C(a);if(z(a)||A(a)||u(a))a[1]=va(a[1]),a[2]=va(a[2]);return a}exports.force_all_rec=va;function D(a,b){a!==b&&(a[0]=5,a[1]=b,a[2]=!1,a[3]=!1)}function wa(a,b){10===a[0]||g();a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3]}
var E=t("\u592a\u59cb\u521d\u6838"),xa=t("\u7b26\u540d"),G=t("\u5316\u6ec5"),I=t("\u5f0f\u5f62"),ya=t("\u7279\u5b9a\u5176\u7269"),K=t("\u7701\u7565\u4e00\u7269"),za=t("\u6620\u8868"),L=t("\u4e00\u985e\u4f55\u7269"),Aa=t("\u662f\u975e"),Ba=t("\u5176\u5b50"),Fa=t("\u967d"),Ga=t("\u9670"),Ha=t("\u9023\u9838"),Ia=t("\u69cb\u7269"),Ja=t("\u8b2c\u8aa4"),Ka=t("\u5217\u5e8f"),La=t("\u4e4b\u7269"),Ma=t("\u6548\u61c9"),Na=t("\u8a3b\u758f"),Oa=[4,E,M(t("\u5b87\u5b99\u4ea1\u77e3"),K)];
function N(a){return[3,xa,[1,E,[1,a,v]]]}function Pa(a){return N(M(L,M(G,K,a),ya))}function Qa(a,b){return N(M(L,M(G,M(a),K),b))}function Ra(a){return N(M(L,G,M(Aa,M(L,a,K))))}
var Sa=Pa(Ia),Ta=Qa(Ia,xa),Ua=Qa(Ia,Ka),Va=Ra(Ia),Wa=Pa(Ja),Xa=Qa(Ja,xa),Ya=Qa(Ja,Ka),Za=Ra(Ja),db=Pa(Ha),eb=Ra(Ha),fb=Qa(Ha,t("\u9996\u59cb")),gb=Qa(Ha,t("\u5c3e\u672b")),hb=Ra(t("\u8a5e\u7d20")),ib=Ra(t("\u9593\u7a7a")),jb=N(M(L,G,M(Aa,t("\u7b49\u540c")))),kb=N(M(L,M(G,[1,G,K],K),t("\u61c9\u7528"))),lb=N(M(L,G,t("\u89e3\u7b97"))),mb=Qa(Ka,M(L,La,K)),nb=N(M(L,G,t("\u5982\u82e5"))),ob=N(M(L,I,t("\u5f15\u7528"))),pb=N(M(L,M(I,M(G,K,G)),ya)),qb=N(M(I,M(E,G))),rb=N(M(I,M(E,I))),sb=N(M(I,I)),tb=N(M(L,
G,Na)),ub=N(M(L,I,Na)),vb=[3,Ga,M()],wb=[3,Fa,M()];function xb(a,b){return a===b?!0:a[1]===b[1]?(D(a,b),!0):!1}function O(a){for(var b=v,c=a.length-1;0<=c;c--)b=[1,a[c],b];return b}exports.jsArray_to_list=O;function yb(a,b,c){for(var d=[];u(a);)d.push(a[1]),a=a[2];return x(a)?b(d):c(d,a)}function Q(a){return yb(a,function(b){return b},function(){return!1})}exports.maybe_list_to_jsArray=Q;function M(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return O(a)}exports.new_list=M;
function zb(a){for(var b=[];pa(a);)b.push(a),a=a[1];for(var c=0;c<b.length;c++)D(b[c],a);return a}exports.un_just=zb;function Ab(a){return 6===a[0]||8===a[0]||7===a[0]||9===a[0]}exports.delay_p=Ab;function R(a){return pa(a)||Ab(a)}exports.delay_just_p=R;function Bb(a){if(6===a[0])return a;if(8===a[0])throw"WIP";if(7===a[0])throw"WIP";if(9===a[0])throw"WIP";return g()}exports.delay_env=function(a){return Bb(a)[1]};exports.delay_x=function(a){return Bb(a)[2]};
function C(a,b,c,d){function f(F){D(n,F);for(var H=0;H<d.length;H++)D(d[H],F);return F}function l(){c[1]=!0;return h(Oa)}function h(F){f(F);return R(F)?(d.push(n),C(F,b,[!1,!1],d)):F}function k(){var F={},H;for(H in m)F[H]=!0;for(H in b)F[H]=!0;return F}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);void 0===d&&(d=[]);var m={},n=a;for(a=0;R(n)&&32>a;a++)d.push(n),n=S(n);for(;R(n);){a=T(n);if(!0===b[a])return l();if(!0===m[a]){c[0]=!0;if(6===n[0])return l();if(7===n[0]){a=n[1];for(var w=n[2],P=!1,U=0,
Z=[Ta,Ua,Va,Xa,Ya,Za,eb,fb,gb,hb,ib];U<Z.length;U++)if(V(Z[U],a)){P=!0;break}if(P)return 1===w.length||g(),!1===c[1]||g(),w=C(w[0],k(),c),c[1]?h(B(a,[w])):g();if(V(a,jb)||V(a,kb)||V(a,lb))return l();if(V(a,nb)&&(3===w.length||g(),!1===c[1]||g(),a=C(w[0],k(),c),c[1]))return h(B(nb,[a,w[1],w[2]]))}else if(8===n[0]||9===n[0])return l();return g()}m[a]=!0;d.push(n);n=S(n)}return f(n)}
function S(a){var b=zb(a);!pa(b)||g();if(6===b[0])a=Cb(b[1],b[2],a);else if(8===b[0]){a=b[1];var c=b[2],d=b[3],f=[4,E,M(rb,M(W(a),c,O(d)))];a=V(c,ob)?1!==d.length?f:d[0]:V(c,pb)?2!==d.length?f:Db(a,d[0],d[1],f):V(c,ub)?2!==d.length?f:[11,d[0],[6,a,d[1]]]:f}else if(7===b[0])a:{f=b[1];a=b[2];c=[4,E,M(qb,M(f,O(a)))];for(d=0;d<Eb.length;d++)if(V(f,Eb[d][0])){f=Eb[d][1];if(a.length!==f)break;d=Eb[d][2];a=1===f?d(a[0],c):2===f?d(a[0],a[1],c):3===f?d(a[0],a[1],a[2],c):g();break a}a=c}else a=9===b[0]?Fb(b[1],
b[2],a):b;a=zb(a);D(b,a);return a}exports.force1=S;exports.force_all=function(a){return C(a)};var Gb=[];exports.env_null_v=Gb;function Hb(a,b,c){for(var d=[],f=0;f<a.length;f+=2){if(V(a[f],b)){d[f]=b;d[f+1]=c;for(f+=2;f<a.length;f+=2)d[f]=a[f],d[f+1]=a[f+1];return d}d[f]=a[f];d[f+1]=a[f+1]}d[a.length]=b;d[a.length+1]=c;return d}exports.env_set=Hb;function Ib(a,b,c){for(var d=0;d<a.length;d+=2)if(V(a[d],b))return a[d+1];return c}exports.env_get=Ib;
function Jb(a,b){for(var c=0;c<a.length;c+=2)if(V(a[c],b))return a[c+1];return g()}function W(a){for(var b=v,c=0;c<a.length;c+=2)b=[1,M(a[c],a[c+1]),b];return[3,za,M(b)]}exports.env2val=W;function Kb(a,b){for(var c=0;c<a.length;c+=2)b(a[c],a[c+1])}exports.env_foreach=Kb;
function Lb(a){a=C(a);if(!z(a))return!1;var b=C(a[1]);if(!q(b)||!xb(b,za))return!1;b=C(a[2]);if(!u(b)||!x(C(b[2])))return!1;a=[];for(b=C(b[1]);!x(b);){if(!u(b))return!1;var c=C(b[1]);b=C(b[2]);if(!u(c))return!1;var d=c[1];c=C(c[2]);if(!u(c))return!1;var f=c[1];if(!x(C(c[2])))return!1;c=!0;for(var l=0;l<a.length;l+=2)if(V(a[l],d)){a[l+1]=f;c=!1;break}c&&(a.push(d),a.push(f))}return a}exports.val2env=Lb;
function Cb(a,b,c){var d=S(b);if(R(d))return c;var f=[4,E,M(qb,M(lb,M(W(a),d)))];if(u(d)){for(b=[];!x(d);){if(R(d))return c;if(u(d))b.push(d[1]),d=S(d[2]);else return f}if(V(b[0],rb)){if(1===b.length)return f;d=b[1];c=[];for(f=2;f<b.length;f++)c.push(b[f]);return[8,a,d,c]}if(V(b[0],sb)){if(1===b.length)return f;d=C([6,a,b[1]]);if(!z(d))return f;var l=S(d[1]);if(R(l))return c;if(!q(l)||!xb(l,I))return f;l=S(d[2]);if(R(l))return c;if(!u(l))return f;d=l[1];l=S(l[2]);if(R(l))return c;if(!x(l))return f;
c=[W(a)];for(f=2;f<b.length;f++)c.push(b[f]);return[9,d,c]}if(V(b[0],qb)){if(1===b.length)return f;d=b[1];c=[];for(f=2;f<b.length;f++)c.push([6,a,b[f]]);return[7,d,c]}d=[6,a,b[0]];c=[];for(f=1;f<b.length;f++)c.push([6,a,b[f]]);return[9,d,c]}return x(d)?d:q(d)||z(d)?Ib(a,d,f):A(d)?f:g()}function Mb(a,b){return[a,1,function(c){c=S(c);return R(c)?B(a,[c]):b(c)?wb:vb}]}function Nb(a,b,c){return[a,1,function(d,f){d=S(d);return R(d)?B(a,[d]):b(d)?c(d):f}]}
var Eb=[Mb(Va,z),[Sa,2,ja],Nb(Ta,z,ka),Nb(Ua,z,la),Mb(Za,A),[Wa,2,ma],Nb(Xa,A,na),Nb(Ya,A,oa),Mb(ib,x),[db,2,fa],Mb(eb,u),Nb(fb,u,ha),Nb(gb,u,ia),[jb,2,function(a,b){function c(d,f,l,h){l=B(jb,[l(d),l(f)]);d=B(jb,[h(d),h(f)]);return B(nb,[l,d,vb])}if(a===b)return wb;a=S(a);b=S(b);if(R(a)||R(b))return B(jb,[a,b]);if(a===b)return wb;!R(a)||g();return x(a)?x(a)?wb:vb:q(a)?q(b)?xb(a,b)?wb:vb:vb:z(a)?z(b)?c(a,b,ka,la):vb:u(a)?u(b)?c(a,b,ha,ia):vb:A(a)?A(b)?c(a,b,na,oa):vb:g()}],[kb,2,function(a,b,c){var d=
[];for(b=C(b);u(b);)d.push(b[1]),b=C(b[2]);return x(b)?[9,a,d]:c}],[lb,2,function(a,b,c){a=Lb(a);return!1===a?c:[6,a,b]}],Mb(hb,q),[mb,1,function(a,b){a=S(a);return R(a)?B(mb,[a]):u(a)?a[1]:b}],[nb,3,function(a,b,c,d){a=S(a);if(R(a))return B(nb,[a,b,c]);if(!z(a))return d;a=C(a[1]);return q(a)?xb(a,Fa)?b:xb(a,Ga)?c:d:d}],[tb,2,aa]];
function Fb(a,b,c){function d(){return[4,E,M(qb,M(kb,M(a,O(b))))]}a=S(a);if(R(a))return c;if(!z(a))return d();c=C(a[1]);if(!q(c)||!xb(c,G))return d();var f=C(a[2]);if(!u(f))return d();c=va(f[1]);f=C(f[2]);if(!u(f)||!x(C(f[2])))return d();f=f[1];for(var l=Gb,h=0;!x(c);)if(q(c)||z(c)){for(var k=v,m=b.length-1;m>=h;m--)k=[1,b[m],k];l=Hb(l,c,k);h=b.length;c=v}else if(u(c))if(h<b.length)k=b[h],h++,l=Hb(l,c[1],k),c=c[2];else return d();else return d();return b.length!==h?d():[6,l,f]}
function Db(a,b,c,d){void 0===d&&(d=!1);b=va(b);for(var f=[],l=!1,h=b;!x(h);)if(q(h)||z(h))f.push(h),l=!0,h=v;else if(u(h))f.push(h[1]),h=h[2];else return!1===d?ma(E,M(rb,M(W(a),pb,O([b,c])))):d;d=b;l&&(d=O(f));var k=[];Kb(a,function(m){for(var n=0;n<f.length;n++)if(V(f[n],m))return;k.push(m)});l=d;for(h=k.length-1;0<=h;h--)l=[1,k[h],l];for(h=k.length-1;0<=h;h--)d=fa(M(rb,ob,Jb(a,k[h])),d);return[3,G,M(b,[1,M(rb,ob,[3,G,M(l,c)]),d])]}
function V(a,b){function c(d,f,l,h){return V(l(d),l(f))&&V(h(d),h(f))?(D(d,f),!0):!1}if(a===b)return!0;a=C(a);b=C(b);if(a===b)return!0;if(x(a)){if(!x(b))return!1;D(a,v);D(b,v);return!0}return q(a)?q(b)?xb(a,b):!1:u(a)?u(b)?c(a,b,ha,ia):!1:A(a)?A(b)?c(a,b,na,oa):!1:z(a)?z(b)?c(a,b,ka,la):!1:g()}exports.equal_p=V;
function X(a,b){function c(d,f,l,h){return X(l(d),l(f))&&X(h(d),h(f))?(D(d,f),!0):!1}if(a===b)return!0;a=zb(a);b=zb(b);if(a===b)return!0;if(x(a)){if(!x(b))return!1;D(a,v);D(b,v);return!0}if(q(a))return q(b)?xb(a,b):!1;if(u(a))return u(b)?c(a,b,ha,ia):!1;if(A(a))return A(b)?c(a,b,na,oa):!1;if(z(a))return z(b)?c(a,b,ka,la):!1;if(6===a[0])throw"WIP";if(7===a[0])throw"WIP";if(8===a[0])throw"WIP";if(9===a[0])throw"WIP";return g()}
function T(a){a=zb(a);var b;if(x(a))return"()";if(u(a)){var c="(";for(b="";u(a);)c+=b+T(a[1]),b=" ",a=zb(a[2]);return c=x(a)?c+")":c+(" . "+T(a)+")")}return z(a)?"#"+T([1,a[1],a[2]]):A(a)?"!"+T([1,a[1],a[2]]):q(a)?ea(a):6===a[0]?"$("+T(W(a[1]))+" "+T(a[2])+")":7===a[0]?"%("+T(a[1])+" "+T(O(a[2]))+")":8===a[0]?"@("+T(W(a[1]))+" "+T(a[2])+" "+T(O(a[3]))+")":9===a[0]?"^("+T(a[1])+" "+T(O(a[2]))+")":g()}exports.simple_print=T;exports.simple_print_force_all_rec=function(a){return T(va(a))};
function Ob(a){function b(){return ra.length===Ca}function c(){!b()||g();var e=ra[Ca];Ca++;return e}function d(e){ra[Ca-1]===e||g();Ca--}function f(e){void 0===e&&(e="");throw"TheLanguage parse ERROR!"+e;}function l(e){return" "===e||"\n"===e||"\t"===e||"\r"===e}function h(){if(b())return!1;var e=c();if(!l(e))return d(e),!1;for(;l(e)&&!b();)e=c();l(e)||d(e);return!0}function k(){if(b())return!1;var e=c(),p="";if(!U(e))return d(e),!1;for(;U(e)&&!b();)p+=e,e=c();U(e)?p+=e:d(e);return da(p)?t(p):f("Not Symbol"+
p)}function m(){if(b())return!1;var e=c();if("("!==e)return d(e),!1;for(var p=[10],r=p;;){h();if(b())return f();e=c();if(")"===e)return wa(p,v),r;if("."===e){h();e=Z();wa(p,e);h();if(b())return f();e=c();return")"!==e?f():r}d(e);e=Z();var J=[10];wa(p,[1,e,J]);p=J}}function n(){if(b())return!1;var e=c();if("#"!==e)return d(e),!1;e=m();return!1!==e&&u(e)?[3,e[1],e[2]]:f()}function w(){if(b())return!1;var e=c();if("!"!==e)return d(e),!1;e=m();return!1!==e&&u(e)?[4,e[1],e[2]]:f()}function P(e,p){return function(){if(b())return!1;
var r=c();if(r!==e)return d(r),!1;r=m();if(!1===r||!u(r))return f();var J=r[2];return u(J)&&x(J[2])?p(r[1],J[1]):f()}}function U(e){if(l(e))return!1;for(var p=0,r="()!#.$%^@~/->_:?[]&".split("");p<r.length;p++)if(r[p]===e)return!1;return!0}function Z(){h();for(var e=[m,sa,n,w,$a,ab,bb,cb],p=0;p<e.length;p++){var r=e[p]();if(!1!==r)return r}return f()}function F(e){return!1===e?f():e}function H(e){F(!b());F(c()===e)}function y(e){function p(){H("[");var Da=y();H("]");return Da}void 0===e&&(e=!1);e=
e?[m,k,p,n,w,$a,ab,bb,cb]:[m,ta,n,w,$a,ab,bb,cb];for(var r=0;r<e.length;r++){var J=e[r]();if(!1!==J)return J}return f()}function Ea(e){if(b())return e;var p=c();if("."===p)return p=y(),M(L,M(G,M(e),K),p);if(":"===p)return p=y(),M(L,p,e);if("~"===p)return M(Aa,e);if("@"===p)return p=y(),M(L,M(G,[1,e,K],K),p);if("?"===p)return M(L,G,M(Aa,e));if("/"===p){for(e=[e];;){p=y(!0);e.push(p);if(b())break;p=c();if("/"!==p){d(p);break}}return M(Ba,O(e))}d(p);return e}function ta(){if(b())return!1;var e=c();if("&"===
e){F(!b());e=c();if("+"===e)return e=y(),M(I,M(E,e));d(e);e=y();return M(I,e)}if(":"===e){F(!b());e=c();if("&"===e)return H(">"),e=y(),M(L,M(I,M(G,K,e)),ya);if(">"===e)return e=y(),M(L,M(G,K,e),ya);d(e);e=y();return M(L,e,ya)}if("+"===e)return e=y(),M(E,e);if("["===e)return e=y(),H("]"),Ea(e);if("_"===e)return H(":"),e=y(),M(L,e,K);d(e);e=k();return!1===e?!1:Ea(e)}function sa(){var e=ta();return!1===e?!1:q(e)?e:N(e)}var ra=a,Ca=0,$a=P("$",function(e,p){var r=Lb(e);return!1===r?f():[6,r,p]}),ab=P("%",
function(e,p){var r=yb(p,function(J){return J},function(){return f()});return[7,e,r]}),bb=function(e,p){return function(){if(b())return!1;var r=c();if(r!==e)return d(r),!1;r=m();if(!1===r||!u(r))return f();var J=r[2];if(!u(J))return f();var Da=J[2];return u(Da)&&x(Da[2])?p(r[1],J[1],Da[1]):f()}}("@",function(e,p,r){r=yb(r,function(J){return J},function(){return f()});e=Lb(e);return!1===e?f():[8,e,p,r]}),cb=P("^",function(e,p){var r=yb(p,function(J){return J},function(){return f()});return[9,e,r]});
return Z()}exports.complex_parse=Ob;
function Y(a){function b(f,l){function h(P){return"inner"===l?"["+P+"]":P}if(q(f))return ea(f);var k=Q(f);if(!1!==k&&3===k.length&&X(k[0],L)){var m=Q(k[1]);if(!1!==m&&3===m.length&&X(m[0],G)){var n=m[1],w=Q(n);if(!1!==w&&1===w.length&&X(m[2],K))return h(b(w[0],"inner")+"."+b(k[2],"inner"));if(u(n)&&X(n[2],K)&&X(m[2],K))return h(b(n[1],"inner")+"@"+b(k[2],"inner"));if(X(n,K)&&X(k[2],ya))return h(":>"+b(m[2],"inner"))}n=Q(k[2]);if(X(k[1],G)&&!1!==n&&2===n.length&&X(n[0],Aa))return h(b(n[1],"inner")+
"?");if(!1!==m&&2===m.length&&X(k[2],ya)&&X(m[0],I)&&(m=Q(m[1]),!1!==m&&3===m.length&&X(m[0],G)&&X(m[1],K)))return h(":&>"+b(m[2],"inner"));m=X(k[2],K)?"_":X(k[2],ya)?"":b(k[2],"inner");return h(m+":"+b(k[1],"inner"))}if(!1!==k&&2===k.length){if(X(k[0],I))return m=Q(k[1]),!1!==m&&2===m.length&&X(m[0],E)?h("&+"+b(m[1],"inner")):h("&"+b(k[1],"inner"));if(X(k[0],Aa))return h(b(k[1],"inner")+"~");if(X(k[0],E))return h("+"+b(k[1],"inner"));if(X(k[0],Ba)&&(k=Q(k[1]),!1!==k&&1<k.length)){m=b(k[0],"inner");
for(n=1;n<k.length;n++)m+="/"+b(k[n],"inner");return h(m)}}return"inner"===l?T(f):"top"===l?T(N(f)):g()}a=Ob(T(a));var c="",d="";if(x(a))return"()";if(u(a)){c="(";for(d="";u(a);)c+=d+Y(a[1]),d=" ",a=a[2];return c=x(a)?c+")":c+(" . "+Y(a)+")")}return z(a)?(c=a[1],a=a[2],d=Q(a),!1!==d&&2===d.length&&X(c,xa)&&X(d[0],E)?b(d[1],"top"):"#"+Y([1,c,a])):A(a)?"!"+Y([1,a[1],a[2]]):q(a)?ea(a):6===a[0]?"$("+Y(W(a[1]))+" "+Y(a[2])+")":7===a[0]?"%("+Y(a[1])+" "+Y(O(a[2]))+")":8===a[0]?"@("+Y(W(a[1]))+" "+Y(a[2])+
" "+Y(O(a[3]))+")":9===a[0]?"^("+Y(a[1])+" "+Y(O(a[2]))+")":g()}exports.complex_print=Y;
exports.machinetext_parse=function(a){function b(){function n(F){function H(ta){var sa=[10],ra=[10];w.push(sa);w.push(ra);wa(F,ta(sa,ra))}var y=f();if("^"===y){for(y="";;){var Ea=f();if("^"===Ea)break;y+=Ea}if(y in ca)wa(F,[0,y]);else return{value:c()}}else if("."===y)H(fa);else if("#"===y)H(ja);else if("!"===y)H(ma);else if("$"===y)H(function(ta,sa){return[6,Gb,M(qb,lb,M(rb,ob,ta),M(rb,ob,sa))]});else if("_"===y)wa(F,v);else return{value:c()}}for(var w=[],P=0,U=h;P<U.length;P++){var Z=n(U[P]);if("object"===
typeof Z)return Z}h=w}function c(){throw"MT parse ERROR";}function d(n){if(!n)return c()}function f(){d(a.length>k);var n=a[k];k++;return n}for(var l=[10],h=[l],k=0;0!==h.length;){var m=b();if("object"===typeof m)return m.value}d(k==a.length);return l};
exports.machinetext_print=function(a){function b(){for(var f=[],l=0,h=c;l<h.length;l++){var k=h[l];k=zb(k);var m=function(n,w,P,U){d+=w;f.push(P(n));f.push(U(n))};if(q(k))d+="^",d+=k[1],d+="^";else if(u(k))m(k,".",ha,ia);else if(x(k))d+="_";else if(z(k))m(k,"#",ka,la);else if(A(k))m(k,"!",na,oa);else if(Ab(k))k=Bb(k),m(k,"$",function(n){return W(n[1])},qa);else return{value:g()}}c=f}for(var c=[a],d="";0!==c.length;)if(a=b(),"object"===typeof a)return a.value;return d};
var Pb=N([1,Ba,[1,[1,Ma,[1,[1,L,[1,La,[1,K,v]]],v]],v]]);exports.return_effect_systemName=Pb;var Qb=N([1,Ba,[1,[1,Ma,[1,Ha,v]],v]]);exports.bind_effect_systemName=Qb;exports.new_effect_bind=function(a,b){return[3,Qb,M(a,b)]};exports.new_effect_return=function(a){return[3,Pb,M(a)]};exports.run_monad=function(a,b,c,d){return Rb(a,b,c,d)()};
function Rb(a,b,c,d){var f;void 0===f&&(f=!1);c=C(c);if(z(c)){var l=c[1],h=c[2];if(V(l,Pb)){if(h=C(h),u(h)){var k=h[1],m=C(h[2]);if(x(m))return!1===f?function(){return a(k,d)}:Rb(a,b,[9,f,k],d)}}else if(V(l,Qb)&&(h=C(h),u(h)&&(l=h[1],m=C(h[2]),u(m)&&(h=m[1],m=C(m[2]),x(m))))){if(!1===f)return Rb(a,b,l,h);throw"WIP";}}return!1===f?function(){return b(c,d,a)}:function(){return b(c,d,function(n,w){return Rb(a,b,ua(f,[n]),w)()})}};
