function h(){throw"TheLanguage PANIC";}function aa(a,b){return[10,a,b]}function m(a){return 10===a[0]}function ba(a){for(;m(a);)a=a[2];return a}function n(a){return 0===a[0]}function q(a,b){return a===b?!0:a[1]===b[1]?(r(a,b),!0):!1}function ca(a,b){return[1,a,b]}function t(a){return 1===a[0]}function u(a){return a[1]}function v(a){return a[2]}function w(a){return 2===a[0]}function ea(a,b){return[3,a,b]}function x(a){return 3===a[0]}function y(a){return a[1]}function fa(a){return a[2]}
function ha(a){return 4===a[0]}function ia(a){return a[2]}function z(a,b){return[6,a,b]}function ka(a,b){return[8,a,b]}function la(a){a=A(a);if(x(a)||t(a)||m(a))a[1]=la(a[1]),a[2]=la(a[2]);return a}function ma(a){var b=na(a);if(x(b)||t(b))if(b[1]=la(b[1]),b[2]=la(b[2]),m(b[1])||m(b[2])){a=[9];pa(a,b);var c=b[2];b=ma(b[1]);c=ma(c);a[1]=b;a[2]=c}else a=b;else a=b;return a}function r(a,b){a!==b&&(a===B&&(a=b,b=B),a[0]=4,a[1]=b,a[2]=!1,a[3]=!1)}
function pa(a,b){9===a[0]||h();9!==b[0]||h();a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3]}function qa(a){return[3,ra,[1,C,[1,a,B]]]}function D(a){for(var b=B,c=a.length-1;0<=c;c--)b=[1,a[c],b];return b}function sa(a,b,c){for(var e=[];t(a);)e.push(a[1]),a=a[2];return w(a)?b(e):c(e,a)}function E(a){return sa(a,function(a){return a},function(){return!1})}function G(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return D(a)}
function H(a){if(!ha(a))return a;for(var b=[];ha(a);)b.push(a),a=a[1];for(var c=0;c<b.length;c++)r(b[c],a);return a}function ta(a){return 5===a[0]||7===a[0]||6===a[0]||8===a[0]}function I(a){return ha(a)||ta(a)}function ua(a){return I(a)||m(a)}function va(a){if(5===a[0])return a;if(7===a[0])throw"WIP";if(6===a[0])throw"WIP";if(8===a[0])throw"WIP";return h()}
function A(a,b,c,e){function d(a){r(l,a);for(var b=0;b<e.length;b++)r(e[b],a);return a}function f(){c[1]=!0;return g(wa)}function g(a){d(a);return I(a)?(e.push(l),A(a,b,[!1,!1],e)):a}function k(){var a={},c;for(c in p)a[c]=!0;for(c in b)a[c]=!0;return a}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);void 0===e&&(e=[]);var p={},l=a;for(a=0;I(l)&&32>a;a++)e.push(l),l=J(l);for(;I(l);){a=K(l);if(!0===b[a])return f();if(!0===p[a]){c[0]=!0;if(5===l[0])return f();if(6===l[0]){a=l[1];for(var F=l[2],da=!1,U=0,
V=[xa,ya,za,Aa,Ba,Ca,Da,Ea];U<V.length;U++)if(M(V[U],a)){da=!0;break}if(da)return 1===F.length||h(),!1===c[1]||h(),F=A(F[0],k(),c),c[1]?g(z(a,[F])):h();if(M(a,Fa)||M(a,Ga)||M(a,Ha))return f();if(M(a,Ia)&&(3===F.length||h(),!1===c[1]||h(),a=A(F[0],k(),c),c[1]))return g(z(Ia,[a,F[1],F[2]]))}else if(7===l[0]||8===l[0])return f();return h()}p[a]=!0;e.push(l);l=J(l)}return d(l)}
function J(a){var b=H(a);!ha(b)||h();a=5===b[0]?Ja(b[1],b[2],a):7===b[0]?Ka(b[1],b[2],b[3]):6===b[0]?La(b[1],b[2],a):8===b[0]?Ma(b[1],b[2],a):b;a=H(a);r(b,a);return a}function na(a){for(;I(a)||m(a);)a=A(ba(a));return a}function Na(a){for(;m(a);)a=a[2];for(a=J(a);m(a);)a=a[2];return a}function Oa(a,b,c,e){var d=[],f=[];a=H(a);for(var g=!0;;){if(w(a))return e(f,d);if(m(a))f.push(a[1]),a=a[2];else if(t(a))d.push(a[1]),a=a[2];else if(I(a))if(g)g=!1,a=J(a);else return c();else return b()}}
function Pa(a){ua(a)&&(a=Na(a));if(ua(a))return null;if(n(a))return!0;if(!x(a))return!1;a=a[1];ua(a)&&(a=Na(a));return ua(a)?null:n(a)?q(a,N):!1}function Qa(a,b,c){for(var e=[],d=0;d<a.length;d+=2){if(M(a[d],b)){e[d]=b;e[d+1]=c;for(d+=2;d<a.length;d+=2)e[d]=a[d],e[d+1]=a[d+1];return e}e[d]=a[d];e[d+1]=a[d+1]}e[a.length]=b;e[a.length+1]=c;return e}function Ra(a,b,c){for(var e=0;e<a.length;e+=2)if(M(a[e],b))return a[e+1];return c}
function Sa(a,b){for(var c=0;c<a.length;c+=2)if(M(a[c],b))return a[c+1];return h()}function O(a){for(var b=B,c=0;c<a.length;c+=2)b=[1,G(a[c],a[c+1]),b];return[3,Za,G(b)]}function $a(a,b){for(var c=0;c<a.length;c+=2)b(a[c],a[c+1])}
function ab(a){a=A(a);if(!x(a))return!1;var b=A(a[1]);if(!n(b)||!q(b,Za))return!1;b=A(a[2]);if(!t(b)||!w(A(b[2])))return!1;a=[];for(b=A(b[1]);!w(b);){if(!t(b))return!1;var c=A(b[1]);b=A(b[2]);if(!t(c))return!1;var e=c[1];c=A(c[2]);if(!t(c))return!1;var d=c[1];if(!w(A(c[2])))return!1;c=!0;for(var f=0;f<a.length;f+=2)if(M(a[f],e)){a[f+1]=d;c=!1;break}c&&a.push(e,d)}return a}
function Ja(a,b,c){function e(){return qa(G(bb,G(Ha,G(O(a),d))))}var d=J(b);if(I(d))return c;if(t(d))return Oa(d,e,function(){return c},function(b,d){if(0!==b.length)throw"WIP";if(M(d[0],cb)){if(1===d.length)return e();for(var k=d[1],f=[],g=2;g<d.length;g++)f.push(d[g]);return[7,a,k,f]}if(M(d[0],db)){if(1===d.length)return e();k=A([5,a,d[1]]);if(!x(k))return e();f=J(k[1]);if(I(f))return c;if(!n(f)||!q(f,P))return e();f=J(k[2]);if(I(f))return c;if(!t(f))return e();k=f[1];f=J(f[2]);if(I(f))return c;
if(!w(f))return e();f=[O(a)];for(g=2;g<d.length;g++)f.push(d[g]);return[8,k,f]}if(M(d[0],bb)){if(1===d.length)return e();k=d[1];f=[];for(g=2;g<d.length;g++)f.push([5,a,d[g]]);return[6,k,f]}k=[5,a,d[0]];f=[];for(g=1;g<d.length;g++)f.push([5,a,d[g]]);return[8,k,f]});if(w(d))return d;b=Pa(d);return null===b?c:!0===b?Ra(a,d,e()):e()}
function Ma(a,b,c){function e(){return qa(G(bb,G(Ga,G(a,D(b)))))}a=J(a);if(I(a))return c;if(!x(a))return e();var d=A(a[1]);if(!n(d)||!q(d,Q))return e();var f=A(a[2]);if(!t(f))return e();d=la(f[1]);f=A(f[2]);if(!t(f)||!w(A(f[2])))return e();f=f[1];for(var g=eb,k=0;!w(d);){var p=Pa(d);if(null===p)return c;if(!0===p){p=B;for(var l=b.length-1;l>=k;l--)p=[1,b[l],p];g=Qa(g,d,p);k=b.length;d=B}else if(t(d))if(k<b.length)p=b[k],k++,g=Qa(g,d[1],p),d=d[2];else return e();else return e()}return b.length!==k?
e():[5,g,f]}function La(a,b,c){function e(){return qa(G(bb,G(a,D(b))))}for(var d=0;d<fb.length;d++){var f=fb[d];if(M(a,f[0])){if(b.length!==f[1])break;return 1===f[1]?f[2](b[0],e,c):2===f[1]?f[2](b[0],b[1],e,c):3===f[1]?f[2](b[0],b[1],b[2],e,c):h()}}return e()}function Ka(a,b,c){function e(){return qa(G(cb,G(O(a),b,D(c))))}return M(b,gb)?1!==c.length?e():c[0]:M(b,hb)?2!==c.length?e():ib(a,c[0],c[1],e):M(b,jb)?2!==c.length?e():[10,c[0],[5,a,c[1]]]:e()}
function ib(a,b,c,e){b=ma(b);for(var d=[],f=!1,g=b;!w(g);){var k=Pa(g);null!==k||h();if(k)d.push(g),f=!0,g=B;else if(t(g))d.push(g[1]),g=g[2];else return e()}g=f?D(d):b;var p=[];$a(a,function(a){for(var b=0;b<d.length;b++)if(M(d[b],a))return;p.push(a)});e=g;for(f=p.length-1;0<=f;f--)e=[1,p[f],e];for(f=p.length-1;0<=f;f--)g=ca(G(cb,gb,Sa(a,p[f])),g);return[3,Q,G(b,[1,G(cb,gb,[3,Q,G(e,c)]),g])]}
function kb(a,b){function c(a,b,c,e){c=kb(c(a),c(b));e=kb(e(a),e(b));return!0===c&&!0===e?(r(a,b),!0):!1!==c&&!1!==e?null:!1}if(a===b)return!0;a=A(a);b=A(b);if(a===b)return!0;if(m(a)){var e=kb(ba(a),b);!0===e&&(e=null);return e}if(m(b))return e=kb(a,ba(b)),!0===e&&(e=null),e;if(w(a)){if(!w(b))return!1;r(a,b);return!0}return n(a)?n(b)?q(a,b):!1:t(a)?t(b)?c(a,b,u,v):!1:x(a)?x(b)?c(a,b,y,fa):!1:h()}function M(a,b){return!1!==kb(a,b)}
function R(a,b){function c(a,b,c,g){return R(c(a),c(b))&&R(g(a),g(b))?(r(a,b),!0):!1}if(a===b)return!0;a=H(a);b=H(b);if(a===b)return!0;if(w(a)){if(!w(b))return!1;r(a,B);r(b,B);return!0}return n(a)?n(b)?q(a,b):!1:t(a)?t(b)?c(a,b,u,v):!1:x(a)?x(b)?c(a,b,y,fa):!1:ta(a)?!1:h()}
function K(a){a=H(a);var b;if(w(a))return"()";if(t(a)){var c="(";for(b="";t(a);)c+=b+K(a[1]),b=" ",a=H(a[2]);return w(a)?c+")":c+(" . "+K(a)+")")}return x(a)?"#"+K([1,a[1],a[2]]):n(a)?a[1]:m(a)?";("+K(a[1])+" "+K(a[2])+")":5===a[0]?"$("+K(O(a[1]))+" "+K(a[2])+")":6===a[0]?"%("+K(a[1])+" "+K(D(a[2]))+")":7===a[0]?"@("+K(O(a[1]))+" "+K(a[2])+" "+K(D(a[3]))+")":8===a[0]?"^("+K(a[1])+" "+K(D(a[2]))+")":h()}
function lb(a){function b(){return Ta.length===oa}function c(){!b()||h();var a=Ta[oa];oa++;return a}function e(a){Ta[oa-1]===a||h();oa--}function d(a){void 0===a&&(a="");throw"TheLanguage parse ERROR!"+a;}function f(a){return" "===a||"\n"===a||"\t"===a||"\r"===a}function g(){if(b())return!1;var a=c();if(!f(a))return e(a),!1;for(;f(a)&&!b();)a=c();f(a)||e(a);return!0}function k(){if(b())return!1;var a=c(),d="";if(!da(a))return e(a),!1;for(;da(a)&&!b();)d+=a,a=c();da(a)?d+=a:e(a);return[0,d]}function p(){if(b())return!1;
var a=c();if("("!==a)return e(a),!1;for(var f=[9],k=f;;){g();if(b())return d();a=c();if(")"===a)return pa(f,B),k;if("."===a){g();a=U();pa(f,a);g();if(b())return d();a=c();return")"!==a?d():k}e(a);a=U();var p=[9];pa(f,[1,a,p]);f=p}}function l(){if(b())return!1;var a=c();if("#"!==a)return e(a),!1;a=p();return!1!==a&&t(a)?[3,a[1],a[2]]:d()}function F(a,f){return function(){if(b())return!1;var g=c();if(g!==a)return e(g),!1;g=p();if(!1===g||!t(g))return d();var k=g[2];return t(k)&&w(k[2])?f(g[1],k[1]):
d()}}function da(a){if(f(a))return!1;for(var b=0,c="()!#.$%^@~/->_:?[]&;".split("");b<c.length;b++)if(c[b]===a)return!1;return!0}function U(){g();for(var a=0,b=[p,Hb,l,Ua,Va,Wa,Xa,Ya];a<b.length;a++){var c=(0,b[a])();if(!1!==c)return c}return d()}function V(a){return!1===a?d():a}function ja(a){V(!b());V(c()===a)}function L(a){function b(){ja("[");var a=L();ja("]");return a}void 0===a&&(a=!1);var c=0;for(a=a?[p,k,b,l,Ua,Va,Wa,Xa,Ya]:[p,mb,l,Ua,Va,Wa,Xa,Ya];c<a.length;c++){var e=(0,a[c])();if(!1!==
e)return e}return d()}function nb(a){if(b())return a;var d=c();if("."===d)return d=L(),G(S,G(Q,G(a),T),d);if(":"===d)return d=L(),G(S,d,a);if("~"===d)return G(W,a);if("@"===d)return d=L(),G(S,G(Q,[1,a,T],T),d);if("?"===d)return G(S,Q,G(W,a));if("/"===d){for(a=[a];;){d=L(!0);a.push(d);if(b())break;d=c();if("/"!==d){e(d);break}}return G(ob,D(a))}e(d);return a}function mb(){if(b())return!1;var a=c();if("&"===a){V(!b());a=c();if("+"===a)return a=L(),G(P,G(C,a));e(a);a=L();return G(P,a)}if(":"===a){V(!b());
a=c();if("&"===a)return ja(">"),a=L(),G(S,G(P,G(Q,T,a)),X);if(">"===a)return a=L(),G(S,G(Q,T,a),X);e(a);a=L();return G(S,a,X)}if("+"===a)return a=L(),G(C,a);if("["===a)return a=L(),ja("]"),nb(a);if("_"===a)return ja(":"),a=L(),G(S,a,T);e(a);a=k();return!1===a?!1:nb(a)}function Hb(){var a=mb();return!1===a?!1:n(a)?a:[3,N,[1,C,[1,a,B]]]}var Ta=a,oa=0,Ua=F("$",function(a,b){var c=ab(a);return!1===c?d():[5,c,b]}),Va=F("%",function(a,b){var c=sa(b,function(a){return a},function(){return d()});return[6,
a,c]}),Wa=function(a,f){return function(){if(b())return!1;var g=c();if(g!==a)return e(g),!1;g=p();if(!1===g||!t(g))return d();var k=g[2];if(!t(k))return d();var l=k[2];return t(l)&&w(l[2])?f(g[1],k[1],l[1]):d()}}("@",function(a,b,c){c=sa(c,function(a){return a},function(){return d()});a=ab(a);return!1===a?d():[7,a,b,c]}),Xa=F("^",function(a,b){var c=sa(b,function(a){return a},function(){return d()});return[8,a,c]}),Ya=F(";",function(a,b){return[10,a,b]});return U()}
function Y(a){function b(a,c){function e(a){return c?"["+a+"]":a}if(n(a))return a[1];var d=E(a);if(!1!==d&&3===d.length&&R(d[0],S)){var f=E(d[1]);if(!1!==f&&3===f.length&&R(f[0],Q)){var l=f[1],F=E(l);if(!1!==F&&1===F.length&&R(f[2],T))return e(b(F[0],!0)+"."+b(d[2],!0));if(t(l)&&R(l[2],T)&&R(f[2],T))return e(b(l[1],!0)+"@"+b(d[2],!0));if(R(l,T)&&R(d[2],X))return e(":>"+b(f[2],!0))}l=E(d[2]);if(R(d[1],Q)&&!1!==l&&2===l.length&&R(l[0],W))return e(b(l[1],!0)+"?");if(!1!==f&&2===f.length&&R(d[2],X)&&
R(f[0],P)&&(f=E(f[1]),!1!==f&&3===f.length&&R(f[0],Q)&&R(f[1],T)))return e(":&>"+b(f[2],!0));f=void 0;f=R(d[2],T)?"_":R(d[2],X)?"":b(d[2],!0);return e(f+":"+b(d[1],!0))}if(!1!==d&&2===d.length){if(R(d[0],P))return f=E(d[1]),!1!==f&&2===f.length&&R(f[0],C)?e("&+"+b(f[1],!0)):e("&"+b(d[1],!0));if(R(d[0],W))return e(b(d[1],!0)+"~");if(R(d[0],C))return e("+"+b(d[1],!0));if(R(d[0],ob)&&(d=E(d[1]),!1!==d&&1<d.length)){f=b(d[0],!0);for(l=1;l<d.length;l++)f+="/"+b(d[l],!0);return e(f)}}return c?K(a):K([3,
N,[1,C,[1,a,B]]])}a=lb(K(a));var c="",e="";if(w(a))return"()";if(t(a)){c="(";for(e="";t(a);)c+=e+Y(a[1]),e=" ",a=a[2];return c=w(a)?c+")":c+(" . "+Y(a)+")")}return x(a)?(c=a[1],a=a[2],e=E(a),!1!==e&&2===e.length&&R(c,N)&&R(e[0],C)?b(e[1],!1):"#"+Y([1,c,a])):n(a)?a[1]:m(a)?";("+Y(a[1])+" "+Y(a[2])+")":5===a[0]?"$("+Y(O(a[1]))+" "+Y(a[2])+")":6===a[0]?"%("+Y(a[1])+" "+Y(D(a[2]))+")":7===a[0]?"@("+Y(O(a[1]))+" "+Y(a[2])+" "+Y(D(a[3]))+")":8===a[0]?"^("+Y(a[1])+" "+Y(D(a[2]))+")":h()}
function pb(a){return function(){return[!1,a]}}function qb(a){return function(){return[!0,a()]}}function rb(a){for(a=a();a[0];)a=a[1]();return a[1]}
function sb(a,b,c,e,d){void 0===d&&(d=!1);c=A(c);if(x(c)){var f=c[1],g=c[2];if(M(f,tb)){if(g=A(g),t(g)&&(f=g[1],g=A(g[2]),w(g))){if(!1===d){var k=f;f=function(){return a(k,e)}}else{var p=f;f=function(){return sb(a,b,[8,d,p],e)}}return qb(f)}}else if(M(f,ub)&&(g=A(g),t(g)&&(f=g[1],g=A(g[2]),t(g)))){var l=g[1];g=A(g[2]);if(w(g)){if(!1===d){var F=f;f=function(){return sb(a,b,F,e,l)}}else f=function(){throw"WIP";};return qb(f)}}}return!1===d?qb(function(){return b(c,e,a)}):qb(function(){return b(c,e,
function(c,e){return qb(function(){return sb(a,b,ka(d,[c]),e)})})})}function vb(a,b,c){c=J(c);return I(c)?z(a,[c]):b(c)?wb:Z}function xb(a,b,c,e,d){e=J(e);return I(e)?z(a,[e]):b(e)?c(e):d()}
var B=[2],ra=[0,"\u8b2c\u8aa4"],C=[0,"\u592a\u59cb\u521d\u6838"],T=[0,"\u7701\u7565\u4e00\u7269"],wa=[3,ra,[1,C,[1,[1,[0,"\u5b87\u5b99\u4ea1\u77e3"],[1,T,B]],B]]],N=[0,"\u7b26\u540d"],P=[0,"\u5f0f\u5f62"],Q=[0,"\u5316\u6ec5"],bb=[3,N,[1,C,[1,[1,P,[1,[1,C,[1,Q,B]],B]],B]]],S=[0,"\u4e00\u985e\u4f55\u7269"],Ha=[3,N,[1,C,[1,[1,S,[1,Q,[1,[0,"\u89e3\u7b97"],B]]],B]]],Za=[0,"\u6620\u8868"],cb=[3,N,[1,C,[1,[1,P,[1,[1,C,[1,P,B]],B]],B]]],db=[3,N,[1,C,[1,[1,P,[1,P,B]],B]]],gb=[3,N,[1,C,[1,[1,S,[1,P,[1,[0,"\u5f15\u7528"],
B]]],B]]],X=[0,"\u7279\u5b9a\u5176\u7269"],hb=[3,N,[1,C,[1,[1,S,[1,[1,P,[1,[1,Q,[1,T,[1,Q,B]]],B]],[1,X,B]]],B]]],yb=[0,"\u8a3b\u758f"],jb=[3,N,[1,C,[1,[1,S,[1,P,[1,yb,B]]],B]]],W=[0,"\u662f\u975e"],zb=[0,"\u69cb\u7269"],za=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,zb,[1,T,B]]],B]],B]]],B]]],Ab=[0,"\u723b\u967d"],wb=[3,Ab,B],Bb=[0,"\u723b\u9670"],Z=[3,Bb,B],xa=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,zb,B],[1,T,B]]],[1,N,B]]],B]]],Cb=[0,"\u5217\u5e8f"],ya=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,zb,B],[1,T,B]]],[1,
Cb,B]]],B]]],Ea=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,[0,"\u9593\u7a7a"],[1,T,B]]],B]],B]]],B]]],Db=[0,"\u9023\u9838"],Aa=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,Db,[1,T,B]]],B]],B]]],B]]],Ba=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,Db,B],[1,T,B]]],[1,[0,"\u9996\u59cb"],B]]],B]]],Ca=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,Db,B],[1,T,B]]],[1,[0,"\u5c3e\u672b"],B]]],B]]],Fa=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[0,"\u7b49\u540c"],B]],B]]],B]]],Ia=[3,N,[1,C,[1,[1,S,[1,Q,[1,[0,"\u5982\u82e5"],B]]],B]]],Ga=[3,N,[1,C,
[1,[1,S,[1,[1,Q,[1,[1,Q,T],[1,T,B]]],[1,[0,"\u61c9\u7528"],B]]],B]]],Da=[3,N,[1,C,[1,[1,S,[1,Q,[1,[1,W,[1,[1,S,[1,[0,"\u8a5e\u7d20"],[1,T,B]]],B]],B]]],B]]],Eb=[0,"\u4e4b\u7269"],Fb=[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,[1,Cb,B],[1,T,B]]],[1,[1,S,[1,Eb,[1,T,B]]],B]]],B]]],fb=[[za,1,function(a){return vb.call(this,za,x,a)}],[[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,T,[1,zb,B]]],[1,X,B]]],B]]],2,ea],[xa,1,function(a,b){return xb.call(this,xa,x,y,a,b)}],[ya,1,function(a,b){return xb.call(this,ya,x,fa,a,b)}],[Ea,1,function(a){return vb.call(this,
Ea,w,a)}],[[3,N,[1,C,[1,[1,S,[1,[1,Q,[1,T,[1,Db,B]]],[1,X,B]]],B]]],2,ca],[Aa,1,function(a){return vb.call(this,Aa,t,a)}],[Ba,1,function(a,b){return xb.call(this,Ba,t,u,a,b)}],[Ca,1,function(a,b){return xb.call(this,Ca,t,v,a,b)}],[Fa,2,function(a,b){function c(a,b,c,g){c=z(Fa,[c(a),c(b)]);a=z(Fa,[g(a),g(b)]);return z(Ia,[c,a,Z])}if(a===b)return wb;a=J(a);b=J(b);if(I(a)||I(b))return z(Fa,[a,b]);if(a===b)return wb;!I(a)||h();return w(a)?w(a)?wb:Z:n(a)?n(b)?q(a,b)?wb:Z:Z:x(a)?x(b)?c(a,b,y,fa):Z:t(a)?
t(b)?c(a,b,u,v):Z:h()}],[Ga,2,function(a,b,c){var e=[];for(b=A(b);t(b);)e.push(b[1]),b=A(b[2]);return w(b)?[8,a,e]:c()}],[Ha,2,function(a,b,c){a=ab(a);return!1===a?c():[5,a,b]}],[Da,1,function(a){return vb.call(this,Da,n,a)}],[Fb,1,function(a,b){a=J(a);return I(a)?z(Fb,[a]):t(a)?a[1]:b()}],[Ia,3,function(a,b,c,e){a=J(a);if(I(a))return z(Ia,[a,b,c]);if(!x(a))return e();a=A(a[1]);return n(a)?q(a,Ab)?b:q(a,Bb)?c:e():e()}],[[3,N,[1,C,[1,[1,S,[1,Q,[1,yb,B]]],B]]],2,aa]],eb=[],ob=[0,"\u5176\u5b50"],Gb=
[0,"\u6548\u61c9"],tb=[3,N,[1,C,[1,[1,ob,[1,[1,Gb,[1,[1,S,[1,Eb,[1,T,B]]],B]],B]],B]]],ub=[3,N,[1,C,[1,[1,ob,[1,[1,Gb,[1,Db,B]],B]],B]]];
module.exports={new_comment:aa,comment_p:m,comment_comment:function(a){return a[1]},comment_x:function(a){return a[2]},un_comment_all:ba,atom_p:n,new_atom:function(a){return[0,a]},un_atom:function(a){return a[1]},atom_equal_p:q,new_construction:ca,construction_p:t,construction_head:u,construction_tail:v,null_v:B,null_p:w,new_data:ea,data_p:x,data_name:y,data_list:fa,just_p:ha,evaluate:function(a,b){return[5,a,b]},apply:ka,force_all_rec:la,force_uncomment_all_rec:ma,unlazy_all_rec:ma,jsArray_to_list:D,
maybe_list_to_jsArray:E,new_list:G,un_just_all:H,un_just_comment_all:function(a){for(;ha(a)||m(a);)a=H(ba(a));return a},delay_p:ta,delay_just_p:I,lazy_p:ua,delay_env:function(a){return va(a)[1]},delay_x:function(a){return va(a)[2]},force1:J,force_all:function(a){return A(a)},force_uncomment_all:na,force_uncomment1:function(a){return m(a)?a[2]:J(a)},unlazy1:Na,env_null_v:eb,env_set:Qa,env_get:Ra,env2val:O,env_foreach:$a,val2env:ab,equal_p:M,simple_print:K,complex_parse:lb,complex_print:Y,machinetext_parse:function(a){function b(a){void 0===
a&&(a="");throw"MT parse ERROR "+a;}function c(a){if(!a)return b()}function e(){c(0!==f);f--;return a[f]}function d(a){var c=g.pop(),d=g.pop();return void 0===d||void 0===c?b():g.unshift(a(d,c))}for(var f=a.length,g=[];0!==f;){var k=e();if("^"===k){for(k="";;){var p=e();if("^"===p)break;k=p+k}g.unshift([0,k])}else if("."===k)d(ca);else if("#"===k)d(ea);else if("$"===k)d(function(a,c){var d=ab(a);return!1===d?b():[5,d,c]});else if("_"===k)g.unshift(B);else return b()}c(0===f);c(1===g.length);return g[0]},
machinetext_print:function(a){function b(){for(var a=[],b=0,g=c;b<g.length;b++){var k=g[b];k=H(k);var p=function(b,c,d,f){e+=c;return a.push(d(b),f(b))};if(n(k))e+="^"+k[1]+"^";else if(t(k))p(k,".",u,v);else if(w(k))e+="_";else if(x(k))p(k,"#",y,fa);else if(ta(k))k=va(k),p(k,"$",function(a){return O(a[1])},ia);else return{value:h()}}c=a}for(var c=[a],e="";0!==c.length;)if(a=b(),"object"===typeof a)return a.value;return e},Trampoline:function(){},trampoline_return:pb,trampoline_delay:qb,run_trampoline:rb,
return_effect_systemName:tb,bind_effect_systemName:ub,new_effect_bind:function(a,b){return[3,ub,G(a,b)]},new_effect_return:function(a){return[3,tb,a]},run_monad_trampoline:function(a,b,c,e){return sb(a,b,c,e)},run_monad_stackoverflow:function(a,b,c,e){return rb(sb(function(b,c){return pb(a(b,c))},function(a,c,e){return pb(b(a,c,function(a,b){return rb(e(a,b))}))},c,e))}};
