function g(){throw"TheLanguage PANIC";}var q=[];exports.comment_null_v=q;function aa(a,b){if(a===q)return b;if(b===q)return a;for(var c=[],d=0;d<a.length;d++){var e=a[d];c.push(e)}for(d=0;d<b.length;d++)e=b[d],c.push(e);return c}exports.comment_append=aa;exports.get_comment_1=function(a){return a[0]};function u(a){a in ba||g();return[q,0,ba[a]]}exports.new_symbol=u;function w(a){return 0===a[1]}exports.symbol_p=w;function ca(a){return da[a[2]]}exports.un_symbol=ca;
function x(a,b){return[q,1,a,b]}exports.new_construction=x;function y(a){return 1===a[1]}exports.construction_p=y;function ea(a){return a[2]}exports.construction_head=ea;function fa(a){return a[3]}exports.construction_tail=fa;var z=[q,2];exports.null_v=z;function B(a){return 2===a[1]}exports.null_p=B;function ha(a,b){return[q,3,a,b]}exports.new_data=ha;function C(a){return 3===a[1]}exports.data_p=C;function ia(a){return a[2]}exports.data_name=ia;function ja(a){return a[3]}exports.data_list=ja;
function ka(a,b){return[q,4,a,b]}exports.new_error=ka;function D(a){return 4===a[1]}exports.error_p=D;function la(a){return a[2]}exports.error_name=la;function ma(a){return a[3]}exports.error_list=ma;function na(a){return 5===a[1]}exports.just_p=na;function oa(a,b){return[q,6,a,b]}exports.evaluate=oa;function pa(a){return a[3]}function F(a,b){return[q,7,a,b]}function qa(a,b){return[q,9,a,b]}exports.apply=qa;function ra(a){a=G(a);if(C(a)||D(a)||y(a)){var b=a[3];a[2]=ra(a[2]);a[3]=ra(b)}return a}
exports.force_all_rec=ra;function H(a,b){a!==b&&(a[0]=q,a[1]=5,a[2]=b,a[3]=!1,a[4]=!1)}function sa(a,b){10===a[0]||g();a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4]}
var ba={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z",a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z","\u4e00\u985e\u4f55\u7269":"\u3749","\u4e4b\u7269":"\ud86d\ude66","\u5176\u5b50":"\ud85a\udfaa","\u51fa\u5165\u6539\u6ec5":"\ud849\udc9f",
"\u5217\u5e8f":"\ud841\udf3a","\u5316\u6ec5":"\ud840\udfc1","\u53c3\u5f62":"\ud842\udef0","\u543e\u81ea":"\ud85a\udcf9","\u592a\u59cb\u521d\u6838":"\ud84d\udf57","\u5982\u82e5":"\ud85b\udc61","\u5b87\u5b99\u4ea1\u77e3":"\ud863\ude79","\u5c3e\u672b":"\ud847\udcb5","\u5e8f\u4e01":"\ud840\udda4","\u5e8f\u4e19":"\ud840\uddee","\u5e8f\u4e59":"\u3408","\u5e8f\u7532":"\ud840\uddda","\u5f0f\u5f62":"\u4f71","\u5f15\u7528":"\u39c8","\u61c9\u7528":"\ud853\udc06","\u6548\u61c9":"\u52b9","\u6620\u8868":"\ud850\udd54",
"\u662f\u975e":"\u6b24","\u69cb\u7269":"\ud845\udcab","\u70ba\u7b26\u540d\u9023":"\u2010","\u7279\u5b9a\u5176\u7269":"\u4e93","\u7701\u7565\u4e00\u7269":"\u7567","\u7b26\u540d":"\u8b3c","\u7b49\u540c":"\u5f0c","\u89e3\u7b97":"\u7b6d","\u8a3b\u758f":"\u758e","\u8a5e\u7d20":"\ud85e\udd5d","\u8b2c\u8aa4":"\u4958","\u9023\u9838":"\u4e29","\u9593\u7a7a":"\ud84e\udcd3","\u9670":"\u4f8c","\u967d":"\ud84c\udd84","\u9996\u59cb":"\ud866\udc10"},da={0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",
A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z",a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z","\u3749":"\u4e00\u985e\u4f55\u7269","\ud86d\ude66":"\u4e4b\u7269","\ud85a\udfaa":"\u5176\u5b50","\ud849\udc9f":"\u51fa\u5165\u6539\u6ec5","\ud841\udf3a":"\u5217\u5e8f","\ud840\udfc1":"\u5316\u6ec5",
"\ud842\udef0":"\u53c3\u5f62","\ud85a\udcf9":"\u543e\u81ea","\ud84d\udf57":"\u592a\u59cb\u521d\u6838","\ud85b\udc61":"\u5982\u82e5","\ud863\ude79":"\u5b87\u5b99\u4ea1\u77e3","\ud847\udcb5":"\u5c3e\u672b","\ud840\udda4":"\u5e8f\u4e01","\ud840\uddee":"\u5e8f\u4e19","\u3408":"\u5e8f\u4e59","\ud840\uddda":"\u5e8f\u7532","\u4f71":"\u5f0f\u5f62","\u39c8":"\u5f15\u7528","\ud853\udc06":"\u61c9\u7528","\u52b9":"\u6548\u61c9","\ud850\udd54":"\u6620\u8868","\u6b24":"\u662f\u975e","\ud845\udcab":"\u69cb\u7269",
"\u2010":"\u70ba\u7b26\u540d\u9023","\u4e93":"\u7279\u5b9a\u5176\u7269","\u7567":"\u7701\u7565\u4e00\u7269","\u8b3c":"\u7b26\u540d","\u5f0c":"\u7b49\u540c","\u7b6d":"\u89e3\u7b97","\u758e":"\u8a3b\u758f","\ud85e\udd5d":"\u8a5e\u7d20","\u4958":"\u8b2c\u8aa4","\u4e29":"\u9023\u9838","\ud84e\udcd3":"\u9593\u7a7a","\u4f8c":"\u9670","\ud84c\udd84":"\u967d","\ud866\udc10":"\u9996\u59cb"},I=u("\u592a\u59cb\u521d\u6838"),ta=u("\u7b26\u540d"),J=u("\u5316\u6ec5"),L=u("\u5f0f\u5f62"),ua=u("\u7b49\u540c"),va=
u("\u89e3\u7b97"),za=u("\u7279\u5b9a\u5176\u7269"),M=u("\u7701\u7565\u4e00\u7269"),Aa=u("\u6620\u8868"),Ba=u("\u5982\u82e5"),N=u("\u4e00\u985e\u4f55\u7269"),Ca=u("\u662f\u975e"),Da=u("\u5176\u5b50"),Ea=u("\u967d"),Fa=u("\u9670"),Ga=u("\u5f15\u7528"),Ia=u("\u61c9\u7528"),Ja=u("\u9593\u7a7a"),Ka=u("\u9023\u9838"),La=u("\u69cb\u7269"),Ma=u("\u8b2c\u8aa4"),Na=u("\u8a5e\u7d20"),Oa=u("\u5217\u5e8f"),Pa=u("\u9996\u59cb"),Qa=u("\u5c3e\u672b"),Ra=u("\u4e4b\u7269"),Sa=u("\u5b87\u5b99\u4ea1\u77e3"),Ta=u("\u8a3b\u758f"),
Ua=ka(I,O(Sa,M));function P(a){return ha(ta,O(I,a))}function Va(a){return P(O(N,O(J,M,a),za))}function Wa(a,b){return P(O(N,O(J,O(a),M),b))}function Xa(a){return P(O(N,J,O(Ca,O(N,a,M))))}
var Ya=Va(La),Za=Wa(La,ta),eb=Wa(La,Oa),fb=Xa(La),gb=Va(Ma),hb=Wa(Ma,ta),ib=Wa(Ma,Oa),jb=Xa(Ma),kb=Va(Ka),lb=Xa(Ka),mb=Wa(Ka,Pa),nb=Wa(Ka,Qa),ob=Xa(Na),pb=Xa(Ja),qb=P(O(N,J,O(Ca,ua))),rb=P(O(N,O(J,x(J,M),M),Ia)),sb=P(O(N,J,va)),tb=Wa(Oa,O(N,Ra,M)),ub=P(O(N,J,Ba)),vb=P(O(N,L,Ga)),wb=P(O(N,O(L,O(J,M,J)),za)),xb=P(O(L,O(I,J))),yb=P(O(L,O(I,L))),zb=P(O(L,L)),Bb=P(O(N,J,Ta)),Cb=P(O(N,L,Ta)),Db=ha(Fa,O()),Eb=ha(Ea,O());function Fb(a,b){return a===b?!0:a[2]===b[2]?(H(a,b),!0):!1}
function Q(a){for(var b=z,c=a.length-1;0<=c;c--)b=x(a[c],b);return b}exports.jsArray_to_list=Q;function Gb(a,b,c){for(var d=[];y(a);)d.push(a[2]),a=a[3];return B(a)?b(d):c(d,a)}function Hb(a){return Gb(a,function(b){return b},function(){return!1})}exports.maybe_list_to_jsArray=Hb;function O(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return Q(a)}exports.new_list=O;function Ib(a){for(var b=[],c=q;na(a);)b.push(a),c=aa(c,a[0]),a=a[2];for(c=0;c<b.length;c++)H(b[c],a);return a}
exports.un_just=Ib;function Jb(a){return 6===a[1]||8===a[1]||7===a[1]||9===a[1]}exports.delay_p=Jb;function R(a){return na(a)||Jb(a)}exports.delay_just_p=R;function Kb(a){if(6===a[1])return a;if(8===a[1])throw"WIP";if(7===a[1])throw"WIP";if(9===a[1])throw"WIP";return g()}exports.delay_env=function(a){return Kb(a)[2]};exports.delay_x=function(a){return Kb(a)[3]};
function G(a,b,c,d){function e(v){H(p,v);for(var K=0;K<d.length;K++)H(d[K],v);return v}function l(){c[1]=!0;return m(Ua)}function m(v){e(v);return R(v)?(d.push(p),G(v,b,[!1,!1],d)):v}function h(){var v={},K;for(K in n)v[K]=!0;for(K in b)v[K]=!0;return v}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);void 0===d&&(d=[]);var n={},p=a;for(a=0;R(p)&&32>a;a++)d.push(p),p=S(p);for(;R(p);){a=U(p);if(!0===b[a])return l();if(!0===n[a]){c[0]=!0;if(6===p[1])return l();if(7===p[1]){a=p[2];for(var E=p[3],T=!1,V=0,
Z=[Za,eb,fb,hb,ib,jb,lb,mb,nb,ob,pb];V<Z.length;V++)if(W(Z[V],a)){T=!0;break}if(T)return 1===E.length||g(),!1===c[1]||g(),E=G(E[0],h(),c),c[1]?m(F(a,[E])):g();if(W(a,qb)||W(a,rb)||W(a,sb))return l();if(W(a,ub)&&(3===E.length||g(),!1===c[1]||g(),a=G(E[0],h(),c),c[1]))return m(F(ub,[a,E[1],E[2]]))}else if(8===p[1]||9===p[1])return l();return g()}n[a]=!0;d.push(p);p=S(p)}return e(p)}
function S(a){var b=Ib(a);!na(b)||g();if(6===b[1])a=Lb(b[2],b[3],a);else if(8===b[1])a:{a=b[2];var c=b[3],d=b[4],e=ka(I,O(yb,O(Mb(a),c,Q(d))));if(W(c,vb))a=1!==d.length?e:d[0];else if(W(c,wb))a=2!==d.length?e:Nb(a,d[0],d[1],e);else{if(W(c,Cb)){if(2!==d.length){a=e;break a}throw"WIP";}a=e}}else if(7===b[1])a:{e=b[2];a=b[3];c=ka(I,O(xb,O(e,Q(a))));for(d=0;d<Ob.length;d++)if(W(e,Ob[d][0])){e=Ob[d][1];if(a.length!==e)break;d=Ob[d][2];a=1===e?d(a[0],c):2===e?d(a[0],a[1],c):3===e?d(a[0],a[1],a[2],c):g();
break a}a=c}else a=9===b[1]?Pb(b[2],b[3],a):b;a=Ib(a);H(b,a);return a}exports.force1=S;exports.force_all=function(a){return G(a)};var Qb=[];exports.env_null_v=Qb;function Rb(a,b,c){for(var d=[],e=0;e<a.length;e+=2){if(W(a[e+0],b)){d[e+0]=b;d[e+1]=c;for(e+=2;e<a.length;e+=2)d[e+0]=a[e+0],d[e+1]=a[e+1];return d}d[e+0]=a[e+0];d[e+1]=a[e+1]}d[a.length+0]=b;d[a.length+1]=c;return d}exports.env_set=Rb;function Sb(a,b,c){for(var d=0;d<a.length;d+=2)if(W(a[d+0],b))return a[d+1];return c}exports.env_get=Sb;
function Tb(a,b){for(var c=0;c<a.length;c+=2)if(W(a[c+0],b))return a[c+1];return g()}function Mb(a){for(var b=z,c=0;c<a.length;c+=2)b=x(O(a[c+0],a[c+1]),b);return ha(Aa,O(b))}exports.env2val=Mb;function Ub(a,b){for(var c=0;c<a.length;c+=2)b(a[c+0],a[c+1])}exports.env_foreach=Ub;
function Vb(a){a=G(a);if(!C(a))return!1;var b=G(a[2]);if(!w(b)||!Fb(b,Aa))return!1;b=G(a[3]);if(!y(b)||!B(G(b[3])))return!1;a=[];for(b=G(b[2]);!B(b);){if(!y(b))return!1;var c=G(b[2]);b=G(b[3]);if(!y(c))return!1;var d=c[2];c=G(c[3]);if(!y(c))return!1;var e=c[2];if(!B(G(c[3])))return!1;c=!0;for(var l=0;l<a.length;l+=2)if(W(a[l+0],d)){a[l+1]=e;c=!1;break}c&&(a.push(d),a.push(e))}return a}exports.val2env=Vb;
function Lb(a,b,c){var d=S(b);if(R(d))return c;var e=ka(I,O(xb,O(sb,O(Mb(a),d))));if(y(d)){for(b=[];!B(d);){if(R(d))return c;if(y(d))b.push(d[2]),d=S(d[3]);else return e}if(W(b[0],yb)){if(1===b.length)return e;d=b[1];c=[];for(e=2;e<b.length;e++)c.push(b[e]);return[q,8,a,d,c]}if(W(b[0],zb)){if(1===b.length)return e;d=G(oa(a,b[1]));if(!C(d))return e;var l=S(d[2]);if(R(l))return c;if(!w(l)||!Fb(l,L))return e;l=S(d[3]);if(R(l))return c;if(!y(l))return e;d=l[2];l=S(l[3]);if(R(l))return c;if(!B(l))return e;
c=[Mb(a)];for(e=2;e<b.length;e++)c.push(b[e]);return qa(d,c)}if(W(b[0],xb)){if(1===b.length)return e;d=b[1];c=[];for(e=2;e<b.length;e++)c.push(oa(a,b[e]));return F(d,c)}d=oa(a,b[0]);c=[];for(e=1;e<b.length;e++)c.push(oa(a,b[e]));return qa(d,c)}return B(d)?d:w(d)||C(d)?Sb(a,d,e):D(d)?e:g()}function Wb(a,b){return[a,1,function(c){c=S(c);return R(c)?F(a,[c]):b(c)?Eb:Db}]}function Xb(a,b,c){return[a,1,function(d,e){d=S(d);return R(d)?F(a,[d]):b(d)?c(d):e}]}
var Ob=[Wb(fb,C),[Ya,2,ha],Xb(Za,C,ia),Xb(eb,C,ja),Wb(jb,D),[gb,2,ka],Xb(hb,D,la),Xb(ib,D,ma),Wb(pb,B),[kb,2,x],Wb(lb,y),Xb(mb,y,ea),Xb(nb,y,fa),[qb,2,function(a,b){function c(d,e,l,m){l=F(qb,[l(d),l(e)]);d=F(qb,[m(d),m(e)]);return F(ub,[l,d,Db])}if(a===b)return Eb;a=S(a);b=S(b);if(R(a)||R(b))return F(qb,[a,b]);if(a===b)return Eb;!R(a)||g();return B(a)?B(a)?Eb:Db:w(a)?w(b)?Fb(a,b)?Eb:Db:Db:C(a)?C(b)?c(a,b,ia,ja):Db:y(a)?y(b)?c(a,b,ea,fa):Db:D(a)?D(b)?c(a,b,la,ma):Db:g()}],[rb,2,function(a,b,c){var d=
[];for(b=G(b);y(b);)d.push(b[2]),b=G(b[3]);return B(b)?qa(a,d):c}],[sb,2,function(a,b,c){a=Vb(a);return!1===a?c:oa(a,b)}],Wb(ob,w),[tb,1,function(a,b){a=S(a);return R(a)?F(tb,[a]):y(a)?a[2]:b}],[ub,3,function(a,b,c,d){a=S(a);if(R(a))return F(ub,[a,b,c]);if(!C(a))return d;a=G(a[2]);return w(a)?Fb(a,Ea)?b:Fb(a,Fa)?c:d:d}],[Bb,2,function(){throw"WIP";}]];
function Pb(a,b,c){function d(){return ka(I,O(xb,O(rb,O(a,Q(b)))))}a=S(a);if(R(a))return c;if(!C(a))return d();c=G(a[2]);if(!w(c)||!Fb(c,J))return d();var e=G(a[3]);if(!y(e))return d();c=ra(e[2]);e=G(e[3]);if(!y(e)||!B(G(e[3])))return d();e=e[2];for(var l=Qb,m=0;!B(c);)if(w(c)||C(c)){for(var h=z,n=b.length-1;n>=m;n--)h=x(b[n],h);l=Rb(l,c,h);m=b.length;c=z}else if(y(c))if(m<b.length)h=b[m],m++,l=Rb(l,c[2],h),c=c[3];else return d();else return d();return b.length!==m?d():oa(l,e)}
function Nb(a,b,c,d){void 0===d&&(d=!1);b=ra(b);for(var e=[],l=!1,m=b;!B(m);)if(w(m)||C(m))e.push(m),l=!0,m=z;else if(y(m))e.push(m[2]),m=m[3];else return!1===d?ka(I,O(yb,O(Mb(a),wb,Q([b,c])))):d;d=b;l&&(d=Q(e));var h=[];Ub(a,function(n){for(var p=0;p<e.length;p++)if(W(e[p],n))return;h.push(n)});l=d;for(m=h.length-1;0<=m;m--)l=x(h[m],l);for(m=h.length-1;0<=m;m--)d=x(O(yb,vb,Tb(a,h[m])),d);return ha(J,O(b,x(O(yb,vb,ha(J,O(l,c))),d)))}
function W(a,b){function c(d,e,l,m){return W(l(d),l(e))&&W(m(d),m(e))?(H(d,e),!0):!1}if(a===b)return!0;a=G(a);b=G(b);if(a===b)return!0;if(B(a)){if(!B(b))return!1;H(a,z);H(b,z);return!0}return w(a)?w(b)?Fb(a,b):!1:y(a)?y(b)?c(a,b,ea,fa):!1:D(a)?D(b)?c(a,b,la,ma):!1:C(a)?C(b)?c(a,b,ia,ja):!1:g()}exports.equal_p=W;
function X(a,b){function c(d,e,l,m){return X(l(d),l(e))&&X(m(d),m(e))?(H(d,e),!0):!1}if(a===b)return!0;a=Ib(a);b=Ib(b);if(a===b)return!0;if(B(a)){if(!B(b))return!1;H(a,z);H(b,z);return!0}if(w(a))return w(b)?Fb(a,b):!1;if(y(a))return y(b)?c(a,b,ea,fa):!1;if(D(a))return D(b)?c(a,b,la,ma):!1;if(C(a))return C(b)?c(a,b,ia,ja):!1;if(6===a[1])throw"WIP";if(7===a[1])throw"WIP";if(8===a[1])throw"WIP";if(9===a[1])throw"WIP";return g()}
function U(a){a=Ib(a);var b;if(B(a))return"()";if(y(a)){var c="(";for(b="";y(a);)c+=b+U(a[2]),b=" ",a=Ib(a[3]);return c=B(a)?c+")":c+(" . "+U(a)+")")}return C(a)?"#"+U(x(a[2],a[3])):D(a)?"!"+U(x(a[2],a[3])):w(a)?ca(a):6===a[1]?"$("+U(Mb(a[2]))+" "+U(a[3])+")":7===a[1]?"%("+U(a[2])+" "+U(Q(a[3]))+")":8===a[1]?"@("+U(Mb(a[2]))+" "+U(a[3])+" "+U(Q(a[4]))+")":9===a[1]?"^("+U(a[2])+" "+U(Q(a[3]))+")":g()}exports.simple_print=U;exports.simple_print_force_all_rec=function(a){return U(ra(a))};
function Yb(a){function b(){return wa.length===Ha}function c(){!b()||g();var f=wa[Ha];Ha++;return f}function d(f){wa[Ha-1]===f||g();Ha--}function e(f){void 0===f&&(f="");throw"TheLanguage parse ERROR!"+f;}function l(f){return" "===f||"\n"===f||"\t"===f||"\r"===f}function m(){if(b())return!1;var f=c();if(!l(f))return d(f),!1;for(;l(f)&&!b();)f=c();l(f)||d(f);return!0}function h(){if(b())return!1;var f=c(),t="";if(!V(f))return d(f),!1;for(;V(f)&&!b();)t+=f,f=c();V(f)?t+=f:d(f);t in ba||e("Not Symbol"+
t);return u(t)}function n(){if(b())return!1;var f=c();if("("!==f)return d(f),!1;for(var t=[10],k=t;;){m();if(b())return e();f=c();if(")"===f)return sa(t,z),k;if("."===f){m();f=Z();sa(t,f);m();if(b())return e();f=c();return")"!==f?e():k}d(f);f=Z();var r=[10];sa(t,x(f,r));t=r}}function p(){if(b())return!1;var f=c();if("#"!==f)return d(f),!1;f=n();return!1!==f&&y(f)?ha(f[2],f[3]):e()}function E(){if(b())return!1;var f=c();if("!"!==f)return d(f),!1;f=n();return!1!==f&&y(f)?ka(f[2],f[3]):e()}function T(f,
t){return function(){if(b())return!1;var k=c();if(k!==f)return d(k),!1;k=n();if(!1===k||!y(k))return e();var r=k[3];return y(r)&&B(r[3])?t(k[2],r[2]):e()}}function V(f){if(l(f))return!1;for(var t="()!#.$%^@~/->_:?[]&".split(""),k=0;k<t.length;k++)if(f===t[k])return!1;return!0}function Z(){m();for(var f=[n,xa,p,E,$a,ab,bb,cb],t=0;t<f.length;t++){var k=f[t]();if(!1!==k)return k}return e()}function v(f){return!1===f?e():f}function K(f){v(!b());v(c()===f)}function ya(){function f(r){function A(){K("[");
var Zb=f();K("]");return Zb}void 0===r&&(r=!1);r=r?[n,h,A,p,E,$a,ab,bb,cb]:[n,ya,p,E,$a,ab,bb,cb];for(var db=0;db<r.length;db++){var Ab=r[db]();if(!1!==Ab)return Ab}return e()}function t(r){if(b())return r;var A=c();if("."===A)return A=f(),O(N,O(J,O(r),M),A);if(":"===A)return A=f(),O(N,A,r);if("~"===A)return O(Ca,r);if("@"===A)return A=f(),O(N,O(J,x(r,M),M),A);if("?"===A)return O(N,J,O(Ca,r));if("/"===A){for(r=[r];;){A=f(!0);r.push(A);if(b())break;A=c();if("/"!==A){d(A);break}}return O(Da,Q(r))}d(A);
return r}if(b())return!1;var k=c();if("&"===k){v(!b());k=c();if("+"===k)return k=f(),O(L,O(I,k));d(k);k=f();return O(L,k)}if(":"===k){v(!b());k=c();if("&"===k)return K(">"),k=f(),O(N,O(L,O(J,M,k)),za);if(">"===k)return k=f(),O(N,O(J,M,k),za);d(k);k=f();return O(N,k,za)}if("+"===k)return k=f(),O(I,k);if("["===k)return k=f(),K("]"),t(k);if("_"===k)return K(":"),k=f(),O(N,k,M);d(k);k=h();return!1===k?!1:t(k)}function xa(){var f=ya();return!1===f?!1:w(f)?f:P(f)}var wa=a,Ha=0,$a=T("$",function(f,t){var k=
Vb(f);return!1===k?e():oa(k,t)}),ab=T("%",function(f,t){var k=Gb(t,function(r){return r},function(){return e()});return F(f,k)}),bb=function(f,t){return function(){if(b())return!1;var k=c();if(k!==f)return d(k),!1;k=n();if(!1===k||!y(k))return e();var r=k[3];if(!y(r))return e();var A=r[3];return y(A)&&B(A[3])?t(k[2],r[2],A[2]):e()}}("@",function(f,t,k){k=Gb(k,function(r){return r},function(){return e()});f=Vb(f);return!1===f?e():[q,8,f,t,k]}),cb=T("^",function(f,t){var k=Gb(t,function(r){return r},
function(){return e()});return qa(f,k)});return Z()}exports.complex_parse=Yb;
function Y(a){function b(e,l){function m(T){return"inner"===l?"["+T+"]":"top"===l?T:g()}if(w(e))return ca(e);var h=Hb(e);if(!1!==h&&3===h.length&&X(h[0],N)){var n=Hb(h[1]);if(!1!==n&&3===n.length&&X(n[0],J)){var p=n[1],E=Hb(p);if(!1!==E&&1===E.length&&X(n[2],M))return m(b(E[0],"inner")+"."+b(h[2],"inner"));if(y(p)&&X(p[3],M)&&X(n[2],M))return m(b(p[2],"inner")+"@"+b(h[2],"inner"));if(X(p,M)&&X(h[2],za))return m(":>"+b(n[2],"inner"))}p=Hb(h[2]);if(X(h[1],J)&&!1!==p&&2===p.length&&X(p[0],Ca))return m(b(p[1],
"inner")+"?");if(!1!==n&&2===n.length&&X(h[2],za)&&X(n[0],L)&&(n=Hb(n[1]),!1!==n&&3===n.length&&X(n[0],J)&&X(n[1],M)))return m(":&>"+b(n[2],"inner"));n=X(h[2],M)?"_":X(h[2],za)?"":b(h[2],"inner");return m(n+":"+b(h[1],"inner"))}if(!1!==h&&2===h.length){if(X(h[0],L))return n=Hb(h[1]),!1!==n&&2===n.length&&X(n[0],I)?m("&+"+b(n[1],"inner")):m("&"+b(h[1],"inner"));if(X(h[0],Ca))return m(b(h[1],"inner")+"~");if(X(h[0],I))return m("+"+b(h[1],"inner"));if(X(h[0],Da)&&(h=Hb(h[1]),!1!==h&&1<h.length)){n=b(h[0],
"inner");for(p=1;p<h.length;p++)n+="/"+b(h[p],"inner");return m(n)}}return"inner"===l?U(e):"top"===l?U(P(e)):g()}a=Yb(U(a));var c="",d="";if(B(a))return"()";if(y(a)){c="(";for(d="";y(a);)c+=d+Y(a[2]),d=" ",a=a[3];return c=B(a)?c+")":c+(" . "+Y(a)+")")}return C(a)?(c=a[2],a=a[3],d=Hb(a),!1!==d&&2===d.length&&X(c,ta)&&X(d[0],I)?b(d[1],"top"):"#"+Y(x(c,a))):D(a)?"!"+Y(x(a[2],a[3])):w(a)?ca(a):6===a[1]?"$("+Y(Mb(a[2]))+" "+Y(a[3])+")":7===a[1]?"%("+Y(a[2])+" "+Y(Q(a[3]))+")":8===a[1]?"@("+Y(Mb(a[2]))+
" "+Y(a[3])+" "+Y(Q(a[4]))+")":9===a[1]?"^("+Y(a[2])+" "+Y(Q(a[3]))+")":g()}exports.complex_print=Y;
exports.machinetext_parse=function(a){function b(){function h(V){function Z(ya){var xa=[10],wa=[10];n.push(xa);n.push(wa);sa(V,ya(xa,wa))}var v=c();if("^"===v){for(v="";;){var K=c();if("^"===K)break;v+=K}sa(V,[q,0,v])}else if("."===v)Z(x);else if("#"===v)Z(ha);else if("!"===v)Z(ka);else if("$"===v)Z(function(ya,xa){return oa(Qb,O(xb,sb,O(yb,vb,ya),O(yb,vb,xa)))});else if("_"===v)sa(V,z);else throw"MT parse ERROR";}for(var n=[],p=0,E=e;p<E.length;p++){var T=h(E[p]);if("object"===typeof T)return T}e=
n}function c(){if(!(a.length>l))throw"MT parse ERROR";var h=a[l];l++;return h}for(var d=[10],e=[d],l=0;0!==e.length;){var m=b();if("object"===typeof m)return m.value}if(l!=a.length)throw"MT parse ERROR";return d};
exports.machinetext_print=function(a){function b(){for(var e=[],l=0,m=c;l<m.length;l++){var h=m[l];h=Ib(h);var n=function(p,E,T,V){d+=E;e.push(T(p));e.push(V(p))};if(w(h))d+="^",d+=h[2],d+="^";else if(y(h))n(h,".",ea,fa);else if(B(h))d+="_";else if(C(h))n(h,"#",ia,ja);else if(D(h))n(h,"!",la,ma);else if(Jb(h))h=Kb(h),n(h,"$",function(p){return Mb(p[2])},pa);else return{value:g()}}c=e}for(var c=[a],d="";0!==c.length;)if(a=b(),"object"===typeof a)return a.value;return d};
