/*
    The Language
    Copyright (C) 2018, 2019  Zaoqi <zaomir@outlook.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

*/

// {{{ 相對獨立的部分。UUC
/* !!!Racket Code Generator!!!
(require (prefix-in uuc: "../../../ununicode/ununicode.rkt"))
((lambda ()

;; 字符串(`(symbol->string k)`)在不同平臺中排序是相同的。
(define all-char (make-immutable-hash (hash-map (uuc:all-char) (lambda (k v) (cons (symbol->string k) v)))))
(define symbols-set-v (string-append "{ " (apply string-append (add-between (hash-map all-char (lambda (xa xd) (string-append "\"" xa "\": \"" (string xd) "\"")) #t) ", ")) " }"))
(define symbols-set-neg-v (string-append "{ " (apply string-append (add-between (hash-map all-char (lambda (xa xd) (string-append "\"" (string xd) "\": \"" xa "\"")) #t) ", ")) " }"))

(define (v->t x) (string-replace x "," "\n"))

(string-append
  (string-append "interface Symbols_Set" (v->t symbols-set-v)) "\n"
  (string-append "function symbols_set_init():Symbols_Set{return " symbols-set-v "}") "\n"
  (string-append "interface Symbols_Set_Neg" (v->t symbols-set-neg-v)) "\n"
  (string-append "function symbols_set_neg_init():Symbols_Set_Neg{return " symbols-set-neg-v "}"))

))
*/
// !!!Generated by Racket!!! !!!BEGIN!!!
interface Symbols_Set {
    "0": "0"
    "1": "1"
    "2": "2"
    "3": "3"
    "4": "4"
    "5": "5"
    "6": "6"
    "7": "7"
    "8": "8"
    "9": "9"
    "A": "A"
    "B": "B"
    "C": "C"
    "D": "D"
    "E": "E"
    "F": "F"
    "G": "G"
    "H": "H"
    "I": "I"
    "J": "J"
    "K": "K"
    "L": "L"
    "M": "M"
    "N": "N"
    "O": "O"
    "P": "P"
    "Q": "Q"
    "R": "R"
    "S": "S"
    "T": "T"
    "U": "U"
    "V": "V"
    "W": "W"
    "X": "X"
    "Y": "Y"
    "Z": "Z"
    "a": "a"
    "b": "b"
    "c": "c"
    "d": "d"
    "e": "e"
    "f": "f"
    "g": "g"
    "h": "h"
    "i": "i"
    "j": "j"
    "k": "k"
    "l": "l"
    "m": "m"
    "n": "n"
    "o": "o"
    "p": "p"
    "q": "q"
    "r": "r"
    "s": "s"
    "t": "t"
    "u": "u"
    "v": "v"
    "w": "w"
    "x": "x"
    "y": "y"
    "z": "z"
    "一類何物": "㝉"
    "之物": "𫙦"
    "其子": "𦮪"
    "出入改滅": "𢒟"
    "列序": "𠜺"
    "化滅": "𠏁"
    "參形": "𠫰"
    "吾自": "𦣹"
    "太始初核": "𣝗"
    "如若": "𦱡"
    "宇宙亡矣": "𨹹"
    "尾末": "𡲵"
    "序丁": "𠆤"
    "序丙": "𠇮"
    "序乙": "㐈"
    "序甲": "𠇚"
    "式形": "佱"
    "引用": "㧈"
    "應用": "𤰆"
    "效應": "効"
    "映表": "𤅔"
    "是非": "欤"
    "構物": "𡒫"
    "為符名連": "‐"
    "爻陰": "侌"
    "爻陽": "𣆄"
    "特定其物": "亓"
    "省略一物": "畧"
    "符名": "謼"
    "等同": "弌"
    "解算": "筭"
    "註疏": "疎"
    "詞素": "𧥝"
    "謬誤": "䥘"
    "連頸": "丩"
    "間空": "𣣓"
    "首始": "𩠐"
}
function symbols_set_init(): Symbols_Set { return { "0": "0", "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "A": "A", "B": "B", "C": "C", "D": "D", "E": "E", "F": "F", "G": "G", "H": "H", "I": "I", "J": "J", "K": "K", "L": "L", "M": "M", "N": "N", "O": "O", "P": "P", "Q": "Q", "R": "R", "S": "S", "T": "T", "U": "U", "V": "V", "W": "W", "X": "X", "Y": "Y", "Z": "Z", "a": "a", "b": "b", "c": "c", "d": "d", "e": "e", "f": "f", "g": "g", "h": "h", "i": "i", "j": "j", "k": "k", "l": "l", "m": "m", "n": "n", "o": "o", "p": "p", "q": "q", "r": "r", "s": "s", "t": "t", "u": "u", "v": "v", "w": "w", "x": "x", "y": "y", "z": "z", "一類何物": "㝉", "之物": "𫙦", "其子": "𦮪", "出入改滅": "𢒟", "列序": "𠜺", "化滅": "𠏁", "參形": "𠫰", "吾自": "𦣹", "太始初核": "𣝗", "如若": "𦱡", "宇宙亡矣": "𨹹", "尾末": "𡲵", "序丁": "𠆤", "序丙": "𠇮", "序乙": "㐈", "序甲": "𠇚", "式形": "佱", "引用": "㧈", "應用": "𤰆", "效應": "効", "映表": "𤅔", "是非": "欤", "構物": "𡒫", "為符名連": "‐", "爻陰": "侌", "爻陽": "𣆄", "特定其物": "亓", "省略一物": "畧", "符名": "謼", "等同": "弌", "解算": "筭", "註疏": "疎", "詞素": "𧥝", "謬誤": "䥘", "連頸": "丩", "間空": "𣣓", "首始": "𩠐" } }
interface Symbols_Set_Neg {
    "0": "0"
    "1": "1"
    "2": "2"
    "3": "3"
    "4": "4"
    "5": "5"
    "6": "6"
    "7": "7"
    "8": "8"
    "9": "9"
    "A": "A"
    "B": "B"
    "C": "C"
    "D": "D"
    "E": "E"
    "F": "F"
    "G": "G"
    "H": "H"
    "I": "I"
    "J": "J"
    "K": "K"
    "L": "L"
    "M": "M"
    "N": "N"
    "O": "O"
    "P": "P"
    "Q": "Q"
    "R": "R"
    "S": "S"
    "T": "T"
    "U": "U"
    "V": "V"
    "W": "W"
    "X": "X"
    "Y": "Y"
    "Z": "Z"
    "a": "a"
    "b": "b"
    "c": "c"
    "d": "d"
    "e": "e"
    "f": "f"
    "g": "g"
    "h": "h"
    "i": "i"
    "j": "j"
    "k": "k"
    "l": "l"
    "m": "m"
    "n": "n"
    "o": "o"
    "p": "p"
    "q": "q"
    "r": "r"
    "s": "s"
    "t": "t"
    "u": "u"
    "v": "v"
    "w": "w"
    "x": "x"
    "y": "y"
    "z": "z"
    "㝉": "一類何物"
    "𫙦": "之物"
    "𦮪": "其子"
    "𢒟": "出入改滅"
    "𠜺": "列序"
    "𠏁": "化滅"
    "𠫰": "參形"
    "𦣹": "吾自"
    "𣝗": "太始初核"
    "𦱡": "如若"
    "𨹹": "宇宙亡矣"
    "𡲵": "尾末"
    "𠆤": "序丁"
    "𠇮": "序丙"
    "㐈": "序乙"
    "𠇚": "序甲"
    "佱": "式形"
    "㧈": "引用"
    "𤰆": "應用"
    "効": "效應"
    "𤅔": "映表"
    "欤": "是非"
    "𡒫": "構物"
    "‐": "為符名連"
    "侌": "爻陰"
    "𣆄": "爻陽"
    "亓": "特定其物"
    "畧": "省略一物"
    "謼": "符名"
    "弌": "等同"
    "筭": "解算"
    "疎": "註疏"
    "𧥝": "詞素"
    "䥘": "謬誤"
    "丩": "連頸"
    "𣣓": "間空"
    "𩠐": "首始"
}
function symbols_set_neg_init(): Symbols_Set_Neg { return { "0": "0", "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "A": "A", "B": "B", "C": "C", "D": "D", "E": "E", "F": "F", "G": "G", "H": "H", "I": "I", "J": "J", "K": "K", "L": "L", "M": "M", "N": "N", "O": "O", "P": "P", "Q": "Q", "R": "R", "S": "S", "T": "T", "U": "U", "V": "V", "W": "W", "X": "X", "Y": "Y", "Z": "Z", "a": "a", "b": "b", "c": "c", "d": "d", "e": "e", "f": "f", "g": "g", "h": "h", "i": "i", "j": "j", "k": "k", "l": "l", "m": "m", "n": "n", "o": "o", "p": "p", "q": "q", "r": "r", "s": "s", "t": "t", "u": "u", "v": "v", "w": "w", "x": "x", "y": "y", "z": "z", "㝉": "一類何物", "𫙦": "之物", "𦮪": "其子", "𢒟": "出入改滅", "𠜺": "列序", "𠏁": "化滅", "𠫰": "參形", "𦣹": "吾自", "𣝗": "太始初核", "𦱡": "如若", "𨹹": "宇宙亡矣", "𡲵": "尾末", "𠆤": "序丁", "𠇮": "序丙", "㐈": "序乙", "𠇚": "序甲", "佱": "式形", "㧈": "引用", "𤰆": "應用", "効": "效應", "𤅔": "映表", "欤": "是非", "𡒫": "構物", "‐": "為符名連", "侌": "爻陰", "𣆄": "爻陽", "亓": "特定其物", "畧": "省略一物", "謼": "符名", "弌": "等同", "筭": "解算", "疎": "註疏", "𧥝": "詞素", "䥘": "謬誤", "丩": "連頸", "𣣓": "間空", "𩠐": "首始" } }
// !!!Generated by Racket!!! !!!END!!!

let symbols_set: (() => Symbols_Set) = () => {
    const r = symbols_set_init()
    symbols_set = () => r
    return r
}
let symbols_set_neg: (() => Symbols_Set_Neg) = () => {
    const r = symbols_set_neg_init()
    symbols_set_neg = () => r
    return r
}
// 相對獨立的部分。UUC }}}
