function h(){throw"TheLanguage PANIC";}exports.new_symbol=function(a){return[0,a]};function k(a){return 0===a[0]}exports.symbol_p=k;exports.un_symbol=function(a){return a[1]};function aa(a,b){return[1,a,b]}exports.new_construction=aa;function n(a){return 1===a[0]}exports.construction_p=n;function ca(a){return a[1]}exports.construction_head=ca;function da(a){return a[2]}exports.construction_tail=da;var q=[2];exports.null_v=q;function r(a){return 2===a[0]}exports.null_p=r;
function ea(a,b){return[3,a,b]}exports.new_data=ea;function t(a){return 3===a[0]}exports.data_p=t;function fa(a){return a[1]}exports.data_name=fa;function ha(a){return a[2]}exports.data_list=ha;function ia(a,b){return[4,a,b]}exports.new_error=ia;function u(a){return 4===a[0]}exports.error_p=u;function ja(a){return a[1]}exports.error_name=ja;function ka(a){return a[2]}exports.error_list=ka;function v(a,b){a!==b&&(a[0]=5,a[1]=b,a[2]=!1,a[3]=!1)}exports.evaluate=function(a,b){return[6,a,b]};
function w(a,b){return[7,a,b]}exports.apply=function(a,b){return[9,a,b]};function x(a){a=y(a);if(t(a)){var b=a[1],c=a[2];a[1]=x(b);a[2]=x(c)}else u(a)?(b=a[1],c=a[2],a[1]=x(b),a[2]=x(c)):n(a)&&(b=a[1],c=a[2],a[1]=x(b),a[2]=x(c));return a}exports.force_all_rec=x;var z=[0,"\u592a\u59cb\u521d\u6838"];exports.system_symbol=z;var la=[0,"\u7b26\u540d"];exports.name_symbol=la;var A=[0,"\u5316\u6ec5"];exports.function_symbol=A;var C=[0,"\u5f0f\u5f62"];exports.form_symbol=C;var ma=[0,"\u7b49\u540c"];
exports.equal_symbol=ma;var na=[0,"\u89e3\u7b97"];exports.evaluate_sym=na;var D=[0,"\u7279\u5b9a\u5176\u7269"];exports.theThing_symbol=D;var E=[0,"\u7701\u7565\u4e00\u7269"];exports.something_symbol=E;var oa=[0,"\u6620\u8868"];exports.mapping_symbol=oa;var pa=[0,"\u82e5"];exports.if_symbol=pa;var F=[0,"\u4e00\u985e\u4f55\u7269"];exports.typeAnnotation_symbol=F;var G=[0,"\u662f\u975e"];exports.isOrNot_symbol=G;var qa=[0,"\u5176\u5b50"];exports.sub_symbol=qa;var ra=[0,"\u967d"];
exports.true_symbol=ra;var sa=[0,"\u9670"];exports.false_symbol=sa;var ta=[0,"\u5f15\u7528"];exports.quote_symbol=ta;var ua=[0,"\u61c9\u7528"];exports.apply_symbol=ua;var va=[0,"\u7a7a"];exports.null_symbol=va;var wa=[0,"\u9023"];exports.construction_symbol=wa;var za=[0,"\u69cb"];exports.data_symbol=za;var Aa=[0,"\u8aa4"];exports.error_symbol=Aa;var Ba=[0,"\u8a5e\u7d20"];exports.symbol_symbol=Ba;var Ca=[0,"\u5217"];exports.list_symbol=Ca;var Da=[0,"\u9996"];exports.head_symbol=Da;var Fa=[0,"\u5c3e"];
exports.tail_symbol=Fa;var Ga=[0,"\u7269"];exports.thing_symbol=Ga;var Ha=[0,"\u5b87\u5b99\u4ea1\u77e3"];exports.theWorldStopped_symbol=Ha;exports.effect_symbol=[0,"\u6548\u61c9"];exports.sequentialWordFormation_symbol=[0,"\u70ba\u7b26\u540d\u9023"];exports.inputOutput_symbol=[0,"\u51fa\u5165\u6539\u6ec5"];var Ia=[4,z,H(Ha,E)];function I(a){return[3,la,H(z,a)]}function Ja(a){return I(H(F,H(A,E,a),D))}function J(a,b){return I(H(F,H(A,H(a),E),b))}function Ka(a){return I(H(F,A,H(G,H(F,a,E))))}
var La=Ja(za);exports.new_data_function_builtin_systemName=La;var Ma=J(za,la);exports.data_name_function_builtin_systemName=Ma;var Na=J(za,Ca);exports.data_list_function_builtin_systemName=Na;var Oa=Ka(za);exports.data_p_function_builtin_systemName=Oa;var Pa=Ja(Aa);exports.new_error_function_builtin_systemName=Pa;var Qa=J(Aa,la);exports.error_name_function_builtin_systemName=Qa;var Ra=J(Aa,Ca);exports.error_list_function_builtin_systemName=Ra;var Sa=Ka(Aa);
exports.error_p_function_builtin_systemName=Sa;var Ta=Ja(wa);exports.new_construction_function_builtin_systemName=Ta;var Ua=Ka(wa);exports.construction_p_function_builtin_systemName=Ua;var Va=J(wa,Da);exports.construction_head_function_builtin_systemName=Va;var Wa=J(wa,Fa);exports.construction_tail_function_builtin_systemName=Wa;var Xa=Ka(Ba);exports.symbol_p_function_builtin_systemName=Xa;var Ya=Ka(va);exports.null_p_function_builtin_systemName=Ya;var Za=I(H(F,A,H(G,ma)));
exports.equal_p_function_builtin_systemName=Za;var fb=I(H(F,H(A,[1,A,E],E),ua));exports.apply_function_builtin_systemName=fb;var gb=I(H(F,A,na));exports.evaluate_function_builtin_systemName=gb;var hb=J(Ca,H(F,Ga,E));exports.list_chooseOne_function_builtin_systemName=hb;var ib=I(H(F,A,pa));exports.if_function_builtin_systemName=ib;var jb=I(H(F,C,ta));exports.quote_form_builtin_systemName=jb;var kb=I(H(F,H(C,H(A,E,A)),D));exports.lambda_form_builtin_systemName=kb;var lb=I(H(C,H(z,A)));
exports.function_builtin_use_systemName=lb;var mb=I(H(C,H(z,C)));exports.form_builtin_use_systemName=mb;var nb=I(H(C,C));exports.form_use_systemName=nb;var K=[3,sa,H()],ob=[3,ra,H()];function L(a,b){return a===b?!0:a[1]===b[1]?(v(a,b),!0):!1}function O(a){for(var b=q,c=a.length-1;0<=c;c--)b=[1,a[c],b];return b}exports.jsArray_to_list=O;function pb(a,b,c){for(var d=[];n(a);)d.push(a[1]),a=a[2];return r(a)?b(d):c(d,a)}function P(a){return pb(a,function(a){return a},function(){return!1})}
exports.maybe_list_to_jsArray=P;function H(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return O(a)}exports.new_list=H;function qb(a){for(var b=[];5===a[0];)b.push(a),a=a[1];for(var c=0;c<b.length;c++)v(b[c],a);return a}function S(a){return 5===a[0]||6===a[0]||8===a[0]||7===a[0]||9===a[0]}exports.delay_p=S;
function y(a,b,c,d){function e(a){v(m,a);for(var b=0;b<d.length;b++)v(d[b],a);return a}function f(){c[1]=!0;return g(Ia)}function g(a){e(a);return S(a)?(d.push(m),y(a,b,[!1,!1],d)):a}function l(){var a={},c;for(c in p)a[c]=!0;for(c in b)a[c]=!0;return a}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);void 0===d&&(d=[]);for(var p={},m=a;S(m);){a=T(m);if(!0===b[a])return f();if(!0===p[a]){c[0]=!0;if(6===m[0])return f();if(7===m[0]){a=m[1];for(var B=m[2],Q=[Ma,Na,Oa,Qa,Ra,Sa,Ua,Va,Wa,Xa,Ya],R=!1,N=0;N<Q.length;N++)U(Q[N],
a)&&(R=!0);if(R)return 1===B.length||h(),!1===c[1]||h(),B=y(B[0],l(),c),c[1]?g(w(a,[B])):h();if(U(a,Za)||U(a,fb)||U(a,gb))return f();if(U(a,ib)&&(3===B.length||h(),!1===c[1]||h(),a=y(B[0],l(),c),c[1]))return g(w(ib,[a,B[1],B[2]]))}else if(8===m[0]||9===m[0])return f();return h()}p[a]=!0;d.push(m);m=V(m)}return e(m)}exports.force_all=y;
function V(a){a=qb(a);5!==a[0]||h();if(6===a[0])var b=rb(a[1],a[2]);else if(8===a[0]){b=a[1];var c=a[2],d=a[3],e=[4,z,H(mb,H(W(b),c,O(d)))];b=U(c,jb)?1!==d.length?e:d[0]:U(c,kb)?2!==d.length?e:sb(b,d[0],d[1],e):e}else if(7===a[0])a:{e=a[1];b=a[2];c=[4,z,H(lb,H(e,O(b)))];for(d=0;d<tb.length;d++)if(U(e,tb[d][0])){e=tb[d][1];if(b.length!==e)break;d=tb[d][2];b=1===e?d(b[0],c):2===e?d(b[0],b[1],c):3===e?d(b[0],b[1],b[2],c):h();break a}b=c}else b=9===a[0]?ub(a[1],a[2]):a;b=qb(b);v(a,b);return b}
exports.force1=V;var vb=[];exports.env_null_v=vb;function wb(a,b,c){for(var d=[],e=0;e<a.length;e+=2){if(U(a[e+0],b)){d[e+0]=b;d[e+1]=c;for(e+=2;e<a.length;e+=2)d[e+0]=a[e+0],d[e+1]=a[e+1];return d}d[e+0]=a[e+0];d[e+1]=a[e+1]}d[a.length+0]=b;d[a.length+1]=c;return d}exports.env_set=wb;function xb(a,b,c){for(var d=0;d<a.length;d+=2)if(U(a[d+0],b))return a[d+1];return c}exports.env_get=xb;function yb(a,b){for(var c=0;c<a.length;c+=2)if(U(a[c+0],b))return a[c+1];return h()}
function W(a){for(var b=q,c=0;c<a.length;c+=2)b=[1,H(a[c+0],a[c+1]),b];return[3,oa,H(b)]}exports.env2val=W;function zb(a,b){for(var c=0;c<a.length;c+=2)b(a[c+0],a[c+1])}exports.env_foreach=zb;
function Ab(a){a=y(a);if(!t(a))return!1;var b=y(a[1]);if(!k(b)||!L(b,oa))return!1;b=y(a[2]);if(!n(b)||!r(y(b[2])))return!1;a=[];for(b=y(b[1]);!r(b);){if(!n(b))return!1;var c=y(b[1]);b=y(b[2]);if(!n(c))return!1;var d=c[1];c=y(c[2]);if(!n(c))return!1;var e=c[1];if(!r(y(c[2])))return!1;c=!0;for(var f=0;f<a.length;f+=2)if(U(a[f+0],d)){a[f+1]=e;c=!1;break}c&&(a.push(d),a.push(e))}return a}exports.val2env=Ab;
function rb(a,b){var c=V(b);if(S(c))return[6,a,c];var d=[4,z,H(lb,H(gb,H(W(a),c)))];if(n(c)){for(var e=[],f=c;!r(f);){if(S(f))return[6,a,c];if(n(f))e.push(f[1]),f=V(f[2]);else return d}if(U(e[0],mb)){if(1===e.length)return d;f=e[1];c=[];for(d=2;d<e.length;d++)c[d-2]=e[d];return[8,a,f,c]}if(U(e[0],nb)){if(1===e.length)return d;f=y([6,a,e[1]]);if(!t(f))return d;var g=V(f[1]);if(S(g))return[6,a,c];if(!k(g)||!L(g,C))return d;g=V(f[2]);if(S(g))return[6,a,c];if(!n(g))return d;f=g[1];g=V(g[2]);if(S(g))return[6,
a,c];if(!r(g))return d;c=[W(a)];for(d=2;d<e.length;d++)c[d-1]=e[d];return[9,f,c]}if(U(e[0],lb)){if(1===e.length)return d;f=e[1];c=[];for(d=2;d<e.length;d++)c[d-2]=[6,a,e[d]];return[7,f,c]}f=[6,a,e[0]];c=[];for(d=1;d<e.length;d++)c[d-1]=[6,a,e[d]];return[9,f,c]}return r(c)?c:k(c)||t(c)?xb(a,c,d):u(c)?d:h()}function Bb(a,b){return[a,1,function(c){c=V(c);return S(c)?w(a,[c]):b(c)?ob:K}]}function Cb(a,b,c){return[a,1,function(d,e){d=V(d);return S(d)?w(a,[d]):b(d)?c(d):e}]}
var tb=[Bb(Oa,t),[La,2,ea],Cb(Ma,t,fa),Cb(Na,t,ha),Bb(Sa,u),[Pa,2,ia],Cb(Qa,u,ja),Cb(Ra,u,ka),Bb(Ya,r),[Ta,2,aa],Bb(Ua,n),Cb(Va,n,ca),Cb(Wa,n,da),[Za,2,function(a,b){function c(a,b,c,g){c=w(Za,[c(a),c(b)]);a=w(Za,[g(a),g(b)]);return w(ib,[c,a,K])}if(a===b)return ob;a=V(a);b=V(b);if(S(a)||S(b))return w(Za,[a,b]);if(a===b)return ob;!S(a)||h();return r(a)?r(a)?ob:K:k(a)?k(b)?L(a,b)?ob:K:K:t(a)?t(b)?c(a,b,fa,ha):K:n(a)?n(b)?c(a,b,ca,da):K:u(a)?u(b)?c(a,b,ja,ka):K:h()}],[fb,2,function(a,b,c){var d=[];
for(b=y(b);n(b);)d.push(b[1]),b=y(b[2]);return r(b)?[9,a,d]:c}],[gb,2,function(a,b,c){a=Ab(a);return!1===a?c:[6,a,b]}],Bb(Xa,k),[hb,1,function(a,b){a=V(a);return S(a)?w(hb,[a]):n(a)?a[1]:b}],[ib,3,function(a,b,c,d){a=V(a);if(S(a))return w(ib,[a,b,c]);if(!t(a))return d;a=y(a[1]);return k(a)?L(a,ra)?b:L(a,sa)?c:d:d}]];
function ub(a,b){function c(){return[4,z,H(lb,H(fb,H(a,O(b))))]}a=V(a);if(S(a))return[9,a,b];if(!t(a))return c();var d=y(a[1]);if(!k(d)||!L(d,A))return c();var e=y(a[2]);if(!n(e))return c();d=x(e[1]);e=y(e[2]);if(!n(e)||!r(y(e[2])))return c();e=e[1];for(var f=vb,g=0;!r(d);)if(k(d)||t(d)){for(var l=q,p=b.length-1;p>=g;p--)l=[1,b[p],l];f=wb(f,d,l);g=b.length;d=q}else if(n(d))if(g<b.length)l=b[g],g++,f=wb(f,d[1],l),d=d[2];else return c();else return c();return b.length!==g?c():[6,f,e]}
function sb(a,b,c,d){void 0===d&&(d=!1);b=x(b);for(var e=[],f=!1,g=b;!r(g);)if(k(g)||t(g))e.push(g),f=!0,g=q;else if(n(g))e.push(g[1]),g=g[2];else return!1===d?ia(z,H(mb,H(W(a),kb,O([b,c])))):d;d=b;f&&(d=O(e));var l=[];zb(a,function(a){for(var b=0;b<e.length;b++)if(U(e[b],a))return;l.push(a)});f=d;for(g=l.length-1;0<=g;g--)f=[1,l[g],f];for(g=l.length-1;0<=g;g--)d=aa(H(mb,jb,yb(a,l[g])),d);return[3,A,H(b,[1,H(mb,jb,[3,A,H(f,c)]),d])]}
function U(a,b){function c(a,b,c,g){return U(c(a),c(b))&&U(g(a),g(b))?(v(a,b),!0):!1}if(a===b)return!0;a=y(a);b=y(b);if(a===b)return!0;if(r(a)){if(!r(b))return!1;v(a,q);v(b,q);return!0}return k(a)?k(b)?L(a,b):!1:n(a)?n(b)?c(a,b,ca,da):!1:u(a)?u(b)?c(a,b,ja,ka):!1:t(a)?t(b)?c(a,b,fa,ha):!1:h()}exports.equal_p=U;
function Y(a,b){function c(a,b,c,g){return Y(c(a),c(b))&&Y(g(a),g(b))?(v(a,b),!0):!1}if(a===b)return!0;a=qb(a);b=qb(b);if(a===b)return!0;if(r(a)){if(!r(b))return!1;v(a,q);v(b,q);return!0}return k(a)?k(b)?L(a,b):!1:n(a)?n(b)?c(a,b,ca,da):!1:u(a)?u(b)?c(a,b,ja,ka):!1:t(a)?t(b)?c(a,b,fa,ha):!1:6===a[0]||7===a[0]||8===a[0]||9===a[0]?!1:h()}
function T(a){a=qb(a);var b;if(r(a))return"()";if(n(a)){var c="(";for(b="";n(a);)c+=b+T(a[1]),b=" ",a=qb(a[2]);return c=r(a)?c+")":c+(" . "+T(a)+")")}return t(a)?"#"+T([1,a[1],a[2]]):u(a)?"!"+T([1,a[1],a[2]]):k(a)?a[1]:6===a[0]?"$("+T(W(a[1]))+" "+T(a[2])+")":7===a[0]?"%("+T(a[1])+" "+T(O(a[2]))+")":8===a[0]?"@("+T(W(a[1]))+" "+T(a[2])+" "+T(O(a[3]))+")":9===a[0]?"^("+T(a[1])+" "+T(O(a[2]))+")":h()}exports.simple_print=T;exports.simple_print_force_all_rec=function(a){return T(x(a))};
function Db(a){function b(){return X.length===M}function c(){!b()||h();var a=X[M];M++;return a}function d(a){X[M-1]===a||h();M--}function e(){throw"TheLanguage parse ERROR!";}function f(a){return" "===a||"\n"===a||"\t"===a||"\r"===a}function g(){if(b())return!1;var a=c();if(!f(a))return d(a),!1;for(;f(a)&&!b();)a=c();f(a)||d(a);return!0}function l(){if(b())return!1;var a=c(),e="";if(!R(a))return d(a),!1;for(;R(a)&&!b();)e+=a,a=c();R(a)?e+=a:d(a);return[0,e]}function p(){function a(a){if(p===l)p=a;
else{for(var b=p;;){if(!n(b))return h();if(b[2]===l)break;b=b[2]}if(!n(b)||b[2]!==l)return h();b[2]=a}}if(b())return!1;var f=c();if("("!==f)return d(f),!1;for(var l=[0,"!!@@READ||HOLE@@!!"],p=l;;){g();if(b())return e();f=c();if(")"===f)return a(q),p;if("."===f){g();f=N();a(f);g();if(b())return e();f=c();return")"!==f?e():p}d(f);f=N();a([1,f,l])}}function m(){if(b())return!1;var a=c();if("#"!==a)return d(a),!1;a=p();return!1!==a&&n(a)?[3,a[1],a[2]]:e()}function B(){if(b())return!1;var a=c();if("!"!==
a)return d(a),!1;a=p();return!1!==a&&n(a)?[4,a[1],a[2]]:e()}function Q(a,g){return function(){if(b())return!1;var f=c();if(f!==a)return d(f),!1;f=p();if(!1===f||!n(f))return e();var l=f[2];return n(l)&&r(l[2])?g(f[1],l[1]):e()}}function R(a){if(f(a))return!1;for(var b="()!#.$%^@~/->_:?[]&".split(""),c=0;c<b.length;c++)if(a===b[c])return!1;return!0}function N(){g();for(var a=[p,l,m,B,Ea,eb,xa,ba],b=0;b<a.length;b++){var c=a[b]();if(!1!==c)return c}return e()}var X=a,M=0,Ea=Q("$",function(a,b){var c=
Ab(a);return!1===c?e():[6,c,b]}),eb=Q("%",function(a,b){var c=pb(b,function(a){return a},function(){return e()});return[7,a,c]}),xa=function(a,f){return function(){if(b())return!1;var g=c();if(g!==a)return d(g),!1;g=p();if(!1===g||!n(g))return e();var l=g[2];if(!n(l))return e();var bb=l[2];return n(bb)&&r(bb[2])?f(g[1],l[1],bb[1]):e()}}("@",function(a,b,c){c=pb(c,function(a){return a},function(){return e()});a=Ab(a);return!1===a?e():[8,a,b,c]}),ba=Q("^",function(a,b){var c=pb(b,function(a){return a},
function(){return e()});return[9,a,c]});return N()}exports.simple_parse=Db;
exports.complex_parse=function(a){function b(){return xa.length===ba}function c(){!b()||h();var a=xa[ba];ba++;return a}function d(a){xa[ba-1]===a||h();ba--}function e(){throw"TheLanguage parse ERROR!";}function f(a){return" "===a||"\n"===a||"\t"===a||"\r"===a}function g(){if(b())return!1;var a=c();if(!f(a))return d(a),!1;for(;f(a)&&!b();)a=c();f(a)||d(a);return!0}function l(){if(b())return!1;var a=c(),e="";if(!R(a))return d(a),!1;for(;R(a)&&!b();)e+=a,a=c();R(a)?e+=a:d(a);return[0,e]}function p(){function a(a){if(l===
ya)l=a;else{for(var b=l;;){if(!n(b))return h();if(b[2]===ya)break;b=b[2]}if(!n(b)||b[2]!==ya)return h();b[2]=a}}if(b())return!1;var f=c();if("("!==f)return d(f),!1;for(var ya=[0,"!!@@READ||HOLE@@!!"],l=ya;;){g();if(b())return e();f=c();if(")"===f)return a(q),l;if("."===f){g();f=N();a(f);g();if(b())return e();f=c();return")"!==f?e():l}d(f);f=N();a([1,f,ya])}}function m(){if(b())return!1;var a=c();if("#"!==a)return d(a),!1;a=p();return!1!==a&&n(a)?[3,a[1],a[2]]:e()}function B(){if(b())return!1;var a=
c();if("!"!==a)return d(a),!1;a=p();return!1!==a&&n(a)?[4,a[1],a[2]]:e()}function Q(a,f){return function(){if(b())return!1;var g=c();if(g!==a)return d(g),!1;g=p();if(!1===g||!n(g))return e();var l=g[2];return n(l)&&r(l[2])?f(g[1],l[1]):e()}}function R(a){if(f(a))return!1;for(var b="()!#.$%^@~/->_:?[]&".split(""),c=0;c<b.length;c++)if(a===b[c])return!1;return!0}function N(){g();for(var a=[p,eb,m,B,$a,ab,db,cb],b=0;b<a.length;b++){var c=a[b]();if(!1!==c)return c}return e()}function X(a){return!1===
a?e():a}function M(a){X(!b());X(c()===a)}function Ea(){function a(b){function c(){M("[");var b=a();M("]");return b}void 0===b&&(b=!1);b=b?[p,l,c,m,B,$a,ab,db,cb]:[p,Ea,m,B,$a,ab,db,cb];for(var d=0;d<b.length;d++){var g=b[d]();if(!1!==g)return g}return e()}function f(g){if(b())return g;var e=c();if("."===e)return e=a(),H(F,H(A,H(g),E),e);if(":"===e)return e=a(),H(F,e,g);if("~"===e)return H(G,g);if("@"===e)return e=a(),H(F,H(A,[1,g,E],E),e);if("?"===e)return H(F,A,H(G,g));if("/"===e){for(g=[g];;){e=
a(!0);g.push(e);if(b())break;e=c();if("/"!==e){d(e);break}}return H(qa,O(g))}d(e);return g}if(b())return!1;var g=c();if("&"===g){X(!b());g=c();if("+"===g)return g=a(),H(C,H(z,g));d(g);g=a();return H(C,g)}if(":"===g){X(!b());g=c();if("&"===g)return M(">"),g=a(),H(F,H(C,H(A,E,g)),D);if(">"===g)return g=a(),H(F,H(A,E,g),D);d(g);g=a();return H(F,g,D)}if("+"===g)return g=a(),H(z,g);if("["===g)return g=a(),M("]"),f(g);if("_"===g)return M(":"),g=a(),H(F,g,E);d(g);g=l();return!1===g?!1:f(g)}function eb(){var a=
Ea();return!1===a?!1:k(a)?a:I(a)}var xa=a,ba=0,$a=Q("$",function(a,b){var c=Ab(a);return!1===c?e():[6,c,b]}),ab=Q("%",function(a,b){var c=pb(b,function(a){return a},function(){return e()});return[7,a,c]}),db=function(a,g){return function(){if(b())return!1;var f=c();if(f!==a)return d(f),!1;f=p();if(!1===f||!n(f))return e();var l=f[2];if(!n(l))return e();var m=l[2];return n(m)&&r(m[2])?g(f[1],l[1],m[1]):e()}}("@",function(a,b,c){c=pb(c,function(a){return a},function(){return e()});a=Ab(a);return!1===
a?e():[8,a,b,c]}),cb=Q("^",function(a,b){var c=pb(b,function(a){return a},function(){return e()});return[9,a,c]});return N()};
function Z(a){function b(a,c){function d(a){return"inner"===c?"["+a+"]":"top"===c?a:h()}if(k(a))return a[1];var e=P(a);if(!1!==e&&3===e.length&&Y(e[0],F)){var f=P(e[1]);if(!1!==f&&3===f.length&&Y(f[0],A)){var m=f[1],B=P(m);if(!1!==B&&1===B.length&&Y(f[2],E))return d(b(B[0],"inner")+"."+b(e[2],"inner"));if(n(m)&&Y(m[2],E)&&Y(f[2],E))return d(b(m[1],"inner")+"@"+b(e[2],"inner"));if(Y(m,E)&&Y(e[2],D))return d(":>"+b(f[2],"inner"))}m=P(e[2]);if(Y(e[1],A)&&!1!==m&&2===m.length&&Y(m[0],G))return d(b(m[1],
"inner")+"?");if(!1!==f&&2===f.length&&Y(e[2],D)&&Y(f[0],C)&&(f=P(f[1]),!1!==f&&3===f.length&&Y(f[0],A)&&Y(f[1],E)))return d(":&>"+b(f[2],"inner"));f=Y(e[2],E)?"_":Y(e[2],D)?"":b(e[2],"inner");return d(f+":"+b(e[1],"inner"))}if(!1!==e&&2===e.length){if(Y(e[0],C))return f=P(e[1]),!1!==f&&2===f.length&&Y(f[0],z)?d("&+"+b(f[1],"inner")):d("&"+b(e[1],"inner"));if(Y(e[0],G))return d(b(e[1],"inner")+"~");if(Y(e[0],z))return d("+"+b(e[1],"inner"));if(Y(e[0],qa)&&(e=P(e[1]),!1!==e&&1<e.length)){f=b(e[0],
"inner");for(m=1;m<e.length;m++)f+="/"+b(e[m],"inner");return d(f)}}return"inner"===c?T(a):"top"===c?T(I(a)):h()}a=Db(T(a));var c="",d="";if(r(a))return"()";if(n(a)){c="(";for(d="";n(a);)c+=d+Z(a[1]),d=" ",a=a[2];return c=r(a)?c+")":c+(" . "+Z(a)+")")}return t(a)?(c=a[1],a=a[2],d=P(a),!1!==d&&2===d.length&&Y(c,la)&&Y(d[0],z)?b(d[1],"top"):"#"+Z([1,c,a])):u(a)?"!"+Z([1,a[1],a[2]]):k(a)?a[1]:6===a[0]?"$("+Z(W(a[1]))+" "+Z(a[2])+")":7===a[0]?"%("+Z(a[1])+" "+Z(O(a[2]))+")":8===a[0]?"@("+Z(W(a[1]))+" "+
Z(a[2])+" "+Z(O(a[3]))+")":9===a[0]?"^("+Z(a[1])+" "+Z(O(a[2]))+")":h()}exports.complex_print=Z;
