(function(){function A(){throw"TheLanguage PANIC";}function T(a){if(!a)return A()}function B(a){return 0===a[0]}function xa(a,b){return[1,a,b]}function k(a){return 1===a[0]}function aa(a){return a[1]}function ba(a){return a[2]}function l(a){return 2===a[0]}function Ua(a,b){return[3,a,b]}function w(a){return 3===a[0]}function ca(a){return a[1]}function da(a){return a[2]}function ya(a,b){return[4,a,b]}function G(a){return 4===a[0]}function ea(a){return a[1]}function fa(a){return a[2]}function H(a,b){a!==
b&&(a[0]=5,a[1]=b,a[2]=void 0,a[3]=void 0)}function I(a,b){return[7,a,b]}function J(a){a=n(a);if(w(a)){var b=a[1],c=a[2];a[1]=J(b);a[2]=J(c)}else G(a)?(b=a[1],c=a[2],a[1]=J(b),a[2]=J(c)):k(a)&&(b=a[1],c=a[2],a[1]=J(b),a[2]=J(c));return a}function C(a){return[3,ha,e(E,a)]}function za(a){return C(e(t,e(q,u,a),O))}function Q(a,b){return C(e(t,e(q,e(a),u),b))}function ia(a){return C(e(t,q,e(R,e(t,a,u))))}function P(a,b){return a===b?!0:a[1]===b[1]?(H(a,b),!0):!1}function F(a){for(var b=N,c=a.length-1;0<=
c;c--)b=[1,a[c],b];return b}function S(a,b,c){for(var d=[];k(a);)d.push(a[1]),a=a[2];return l(a)?b(d):c(d,a)}function L(a){return S(a,function(a){return a},function(){return!1})}function e(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];return F(a)}function U(a){for(var b=[];5===a[0];)b.push(a),a=a[1];for(var c=0;c<b.length;c++)H(b[c],a);return a}function x(a){return 5===a[0]||6===a[0]||8===a[0]||7===a[0]||9===a[0]}function n(a,b,c){function d(){c[1]=!0;H(h,Aa);for(var a=0;a<y.length;a++)H(y[a],
Aa);return Aa}function f(){var a={},c;for(c in e)a[c]=!0;for(c in b)a[c]=!0;return a}void 0===b&&(b={});void 0===c&&(c=[!1,!1]);for(var e={},h=a,y=[];x(h);){a=r(h);if(!0===b[a])return d();if(!0===e[a]){c[0]=!0;if(6===h[0])return d();if(7===h[0]){a=h[1];for(var p=h[2],k=[Ba,Ca,Da,Ea,Fa,Ga,Ha,Ia,Ja,Ka,La],m=!1,l=0;l<k.length;l++)v(k[l],a)&&(m=!0);if(m)return T(1===p.length),T(!1===c[1]),p=n(p[0],f(),c),c[1]?n(I(a,[p])):A();if(v(a,V)||v(a,qa)||v(a,ra))return d();if(v(a,W)&&(T(3===p.length),T(!1===c[1]),
a=n(p[0],f(),c),c[1]))return n(I(W,[a,p[1],p[2]]))}else if(8===h[0]||9===h[0])return d();return A()}e[a]=!0;y.push(h);h=z(h)}for(l=0;l<y.length;l++)H(y[l],h);return h}function z(a){a=U(a);T(5!==a[0]);if(6===a[0])var b=nb(a[1],a[2]);else if(8===a[0]){b=a[1];var c=a[2],d=a[3],f=[4,E,e(X,e(M(b),c,F(d)))];b=v(c,sa)?1!==d.length?f:d[0]:v(c,Ma)?2!==d.length?f:ob(b,d[0],d[1],f):f}else b=7===a[0]?pb(a[1],a[2]):9===a[0]?qb(a[1],a[2]):a;b=U(b);H(a,b);return b}function Na(a,b,c){for(var d=[],f=0;f<a.length;f+=
2){if(v(a[f+0],b)){d[f+0]=b;d[f+1]=c;for(f+=2;f<a.length;f+=2)d[f+0]=a[f+0],d[f+1]=a[f+1];return d}d[f+0]=a[f+0];d[f+1]=a[f+1]}d[a.length+0]=b;d[a.length+1]=c;return d}function Va(a,b,c){for(var d=0;d<a.length;d+=2)if(v(a[d+0],b))return a[d+1];return c}function rb(a,b){for(var c=0;c<a.length;c+=2)if(v(a[c+0],b))return a[c+1];return A()}function M(a){for(var b=N,c=0;c<a.length;c+=2)b=[1,e(a[c+0],a[c+1]),b];return[3,Oa,e(b)]}function Wa(a,b){for(var c=0;c<a.length;c+=2)b(a[c+0],a[c+1])}function Y(a){a=
n(a);if(!w(a))return!1;var b=n(a[1]);if(!B(b)||!P(b,Oa))return!1;b=n(a[2]);if(!k(b)||!l(n(b[2])))return!1;a=[];for(b=n(b[1]);!l(b);){if(!k(b))return!1;var c=n(b[1]);b=n(b[2]);if(!k(c))return!1;var d=c[1];c=n(c[2]);if(!k(c))return!1;var f=c[1];if(!l(n(c[2])))return!1;c=!0;for(var e=0;e<a.length;e+=2)if(v(a[e+0],d)){a[e+1]=f;c=!1;break}c&&(a.push(d),a.push(f))}return a}function nb(a,b){var c=z(b);if(x(c))return[6,a,c];var d=[4,E,e(ja,e(ra,e(M(a),c)))];if(k(c)){for(var f=[],g=c;!l(g);){if(x(g))return[6,
a,c];if(k(g))f.push(g[1]),g=z(g[2]);else return d}if(v(f[0],X)){if(1===f.length)return d;g=f[1];c=[];for(d=2;d<f.length;d++)c[d-2]=f[d];return[8,a,g,c]}if(v(f[0],Xa)){if(1===f.length)return d;g=n([6,a,f[1]]);if(!w(g))return d;var h=z(g[1]);if(x(h))return[6,a,c];if(!B(h)||!P(h,K))return d;h=z(g[2]);if(x(h))return[6,a,c];if(!k(h))return d;g=h[1];h=z(h[2]);if(x(h))return[6,a,c];if(!l(h))return d;c=[M(a)];for(d=2;d<f.length;d++)c[d-1]=f[d];return[9,g,c]}if(v(f[0],ja)){if(1===f.length)return d;g=f[1];
c=[];for(d=2;d<f.length;d++)c[d-2]=[6,a,f[d]];return[7,g,c]}g=[6,a,f[0]];c=[];for(d=1;d<f.length;d++)c[d-1]=[6,a,f[d]];return[9,g,c]}return l(c)?c:B(c)||w(c)?Va(a,c,d):G(c)?d:A()}function ka(a,b){return[a,1,function(c){c=z(c);return x(c)?I(a,[c]):b(c)?la:ta}]}function Z(a,b,c){return[a,1,function(d,f){d=z(d);return x(d)?I(a,[d]):b(d)?c(d):f}]}function qb(a,b){function c(){return[4,E,e(ja,e(qa,e(a,F(b))))]}a=z(a);if(x(a))return[9,a,b];if(!w(a))return c();var d=n(a[1]);if(!B(d)||!P(d,q))return c();
var f=n(a[2]);if(!k(f))return c();d=J(f[1]);f=n(f[2]);if(!k(f)||!l(n(f[2])))return c();f=f[1];for(var g=Ya;!l(d);)if(B(d)||w(d))g=Na(g,d,F(b)),b=[],d=N;else if(k(d))if(b.length){var h=b.shift();g=Na(g,d[1],h);d=d[2]}else return c();else return c();return 0!==b.length?c():[6,g,f]}function pb(a,b){for(var c=[4,E,e(ja,e(a,F(b)))],d=0;d<ua.length;d++)if(v(a,ua[d][0])){var f=ua[d][1];if(b.length!==f)break;d=ua[d][2];switch(f){case 1:return d(b[0],c);case 2:return d(b[0],b[1],c);case 3:return d(b[0],b[1],
b[2],c)}return A()}return c}function ob(a,b,c,d){void 0===d&&(d=void 0);b=J(b);for(var f=[],g=!1,h=b;!l(h);)if(B(h)||w(h))f.push(h),g=!0,h=N;else if(k(h))f.push(h[1]),h=h[2];else return void 0===d?ya(E,e(X,e(M(a),Ma,F([b,c])))):d;d=b;g&&(d=F(f));var y=[];Wa(a,function(a){for(var b=0;b<f.length;b++)if(v(f[b],a))return;y.push(a)});g=d;for(h=y.length-1;0<=h;h--)g=[1,y[h],g];for(h=y.length-1;0<=h;h--)d=xa(e(X,sa,rb(a,y[h])),d);return[3,q,e(b,[1,e(X,sa,[3,q,e(g,c)]),d])]}function v(a,b){function c(a,b,
c,e){return v(c(a),c(b))&&v(e(a),e(b))?(H(a,b),!0):!1}if(a===b)return!0;a=n(a);b=n(b);return a===b?!0:a[0]!==b[0]?!1:l(a)?(H(a,N),H(b,N),!0):B(a)?P(a,b):k(a)?c(a,b,aa,ba):G(a)?c(a,b,ea,fa):w(a)?c(a,b,ca,da):A()}function m(a,b){function c(a,b,c,e){return m(c(a),c(b))&&m(e(a),e(b))?(H(a,b),!0):!1}if(a===b)return!0;a=U(a);b=U(b);return a===b?!0:a[0]!==b[0]?!1:l(a)?(H(a,N),H(b,N),!0):B(a)?P(a,b):k(a)?c(a,b,aa,ba):G(a)?c(a,b,ea,fa):w(a)?c(a,b,ca,da):6===a[0]||7===a[0]||8===a[0]||9===a[0]?!1:A()}function r(a){a=
U(a);var b;if(l(a))return"()";if(k(a)){var c="(";for(b="";k(a);)c+=b+r(a[1]),b=" ",a=U(a[2]);return c=l(a)?c+")":c+(" . "+r(a)+")")}return w(a)?"#"+r([1,a[1],a[2]]):G(a)?"!"+r([1,a[1],a[2]]):B(a)?a[1]:6===a[0]?"$("+r(M(a[1]))+" "+r(a[2])+")":7===a[0]?"%("+r(a[1])+" "+r(F(a[2]))+")":8===a[0]?"@("+r(M(a[1]))+" "+r(a[2])+" "+r(F(a[3]))+")":9===a[0]?"^("+r(a[1])+" "+r(F(a[2]))+")":A()}function Za(a){function b(){return 0===r.length}function c(){return r.shift()}function d(a){r.unshift(a)}function f(){throw"TheLanguage parse ERROR!";
}function e(a){return" "===a||"\n"===a||"\t"===a||"\r"===a}function h(){if(b())return!1;var a=c();if(!e(a))return d(a),!1;for(;e(a)&&!b();)a=c();e(a)||d(a);return!0}function y(){if(b())return!1;var a=c(),f="";if(!t(a))return d(a),!1;for(;t(a)&&!b();)f+=a,a=c();t(a)?f+=a:d(a);return[0,f]}function p(){function a(a){if(g===p)g=a;else{for(var b=g;;){if(!k(b))return A();if(b[2]===p)break;b=b[2]}if(!k(b)||b[2]!==p)return A();b[2]=a}}if(b())return!1;var e=c();if("("!==e)return d(e),!1;for(var p=[0,"!!@@READ||HOLE@@!!"],
g=p;;){h();if(b())return f();e=c();if(")"===e)return a(N),g;if("."===e){h();e=u();a(e);h();if(b())return f();e=c();return")"!==e?f():g}d(e);e=u();a([1,e,p])}}function m(){if(b())return!1;var a=c();if("#"!==a)return d(a),!1;a=p();return!1!==a&&k(a)?[3,a[1],a[2]]:f()}function n(){if(b())return!1;var a=c();if("!"!==a)return d(a),!1;a=p();return!1!==a&&k(a)?[4,a[1],a[2]]:f()}function q(a,e){return function(){if(b())return!1;var h=c();if(h!==a)return d(h),!1;h=p();if(!1===h||!k(h))return f();var g=h[2];
return k(g)&&l(g[2])?e(h[1],g[1]):f()}}function t(a){if(e(a))return!1;for(var b="()!#.$%^@~/->_:?[]&".split(""),c=0;c<b.length;c++)if(a===b[c])return!1;return!0}function u(){h();for(var a=[p,y,m,n,v,w,B,C],b=0;b<a.length;b++){var c=a[b]();if(!1!==c)return c}return f()}var r=a.split(""),v=q("$",function(a,b){var c=Y(a);return!1===c?f():[6,c,b]}),w=q("%",function(a,b){var c=S(b,function(a){return a},function(){return f()});return[7,a,c]}),B=function(a,e){return function(){if(b())return!1;var h=c();
if(h!==a)return d(h),!1;h=p();if(!1===h||!k(h))return f();var g=h[2];if(!k(g))return f();var Pa=g[2];return k(Pa)&&l(Pa[2])?e(h[1],g[1],Pa[1]):f()}}("@",function(a,b,c){c=S(c,function(a){return a},function(){return f()});a=Y(a);return!1===a?f():[8,a,b,c]}),C=q("^",function(a,b){var c=S(b,function(a){return a},function(){return f()});return[9,a,c]});return u()}function va(a){function b(){return 0===G.length}function c(){return G.shift()}function d(a){G.unshift(a)}function f(){throw"TheLanguage parse ERROR!";
}function g(a){return" "===a||"\n"===a||"\t"===a||"\r"===a}function h(){if(b())return!1;var a=c();if(!g(a))return d(a),!1;for(;g(a)&&!b();)a=c();g(a)||d(a);return!0}function y(){if(b())return!1;var a=c(),f="";if(!v(a))return d(a),!1;for(;v(a)&&!b();)f+=a,a=c();v(a)?f+=a:d(a);return[0,f]}function p(){function a(a){if(g===ma)g=a;else{for(var b=g;;){if(!k(b))return A();if(b[2]===ma)break;b=b[2]}if(!k(b)||b[2]!==ma)return A();b[2]=a}}if(b())return!1;var e=c();if("("!==e)return d(e),!1;for(var ma=[0,"!!@@READ||HOLE@@!!"],
g=ma;;){h();if(b())return f();e=c();if(")"===e)return a(N),g;if("."===e){h();e=w();a(e);h();if(b())return f();e=c();return")"!==e?f():g}d(e);e=w();a([1,e,ma])}}function m(){if(b())return!1;var a=c();if("#"!==a)return d(a),!1;a=p();return!1!==a&&k(a)?[3,a[1],a[2]]:f()}function n(){if(b())return!1;var a=c();if("!"!==a)return d(a),!1;a=p();return!1!==a&&k(a)?[4,a[1],a[2]]:f()}function r(a,e){return function(){if(b())return!1;var h=c();if(h!==a)return d(h),!1;h=p();if(!1===h||!k(h))return f();var g=h[2];
return k(g)&&l(g[2])?e(h[1],g[1]):f()}}function v(a){if(g(a))return!1;for(var b="()!#.$%^@~/->_:?[]&".split(""),c=0;c<b.length;c++)if(a===b[c])return!1;return!0}function w(){h();for(var a=[p,H,m,n,I,J,L,M],b=0;b<a.length;b++){var c=a[b]();if(!1!==c)return c}return f()}function x(a){return!1===a?f():a}function z(a){x(!b());x(c()===a)}function D(){function a(b){function c(){z("[");var b=a();z("]");return b}void 0===b&&(b=!1);b=b?[p,y,c,m,n,I,J,L,M]:[p,D,m,n,I,J,L,M];for(var d=0;d<b.length;d++){var e=
b[d]();if(!1!==e)return e}return f()}function h(f){if(b())return f;var g=c();switch(g){case ".":var h=a();return e(t,e(q,e(f),u),h);case ":":return h=a(),e(t,h,f);case "~":return e(R,f);case "@":return h=a(),e(t,e(q,[1,f,u],u),h);case "?":return e(t,q,e(R,f));case "/":for(g=[];;){h=a(!0);g.push(h);if(b())break;h=c();if("/"!==h){d(h);break}}return e(Qa,f,F(g));default:return d(g),f}}if(b())return!1;var g=c();switch(g){case "&":x(!b());g=c();if("+"===g)return g=a(),e(K,e(E,g));d(g);g=a();return e(K,
g);case ":":x(!b());g=c();if("&"===g)return z(">"),g=a(),e(t,e(K,e(q,u,g)),O);if(">"===g)return g=a(),e(t,e(q,u,g),O);d(g);g=a();return e(t,g,O);case "+":return g=a(),e(E,g);case "[":return g=a(),z("]"),h(g);case "_":return z(":"),g=a(),e(t,g,u);default:return d(g),g=y(),!1===g?!1:h(g)}}function H(){var a=D();return!1===a?!1:B(a)?a:C(a)}var G=a.split(""),I=r("$",function(a,b){var c=Y(a);return!1===c?f():[6,c,b]}),J=r("%",function(a,b){var c=S(b,function(a){return a},function(){return f()});return[7,
a,c]}),L=function(a,e){return function(){if(b())return!1;var h=c();if(h!==a)return d(h),!1;h=p();if(!1===h||!k(h))return f();var g=h[2];if(!k(g))return f();var y=g[2];return k(y)&&l(y[2])?e(h[1],g[1],y[1]):f()}}("@",function(a,b,c){c=S(c,function(a){return a},function(){return f()});a=Y(a);return!1===a?f():[8,a,b,c]}),M=r("^",function(a,b){var c=S(b,function(a){return a},function(){return f()});return[9,a,c]});return w()}function D(a){function b(a,c){function d(a){return"inner"===c?"["+a+"]":"top"===
c?a:A()}if(B(a))return a[1];var e=L(a);if(!1!==e&&3===e.length&&m(e[0],t)){var f=L(e[1]);if(!1!==f&&3===f.length&&m(f[0],q)){var g=f[1],l=L(g);if(!1!==l&&1===l.length&&m(f[2],u))return d(b(l[0],"inner")+"."+b(e[2],"inner"));if(k(g)&&m(g[2],u)&&m(f[2],u))return d(b(g[1],"inner")+"@"+b(e[2],"inner"));if(m(g,u)&&m(e[2],O))return d(":>"+b(f[2],"inner"))}g=L(e[2]);if(m(e[1],q)&&!1!==g&&2===g.length&&m(g[0],R))return d(b(g[1],"inner")+"?");if(!1!==f&&2===f.length&&m(e[2],O)&&m(f[0],K)&&(f=L(f[1]),!1!==
f&&3===f.length&&m(f[0],q)&&m(f[1],u)))return d(":&>"+b(f[2],"inner"));f=m(e[2],u)?"_":m(e[2],O)?"":b(e[2],"inner");return d(f+":"+b(e[1],"inner"))}if(!1!==e&&2===e.length){if(m(e[0],K))return f=L(e[1]),!1!==f&&2===f.length&&m(f[0],E)?d("&+"+b(f[1],"inner")):d("&"+b(e[1],"inner"));if(m(e[0],R))return d(b(e[1],"inner")+"~");if(m(e[0],E))return d("+"+b(e[1],"inner"))}else if(!1!==e&&3===e.length&&m(e[0],Qa)&&(f=L(e[2]),!1!==f&&0!==f.length)){g="";for(l=0;l<f.length;l++)g+="/"+b(f[l],"inner");return d(b(e[1],
"inner")+g)}return"inner"===c?r(a):"top"===c?r(C(a)):A()}a=Za(r(a));var c="",d="";if(l(a))return"()";if(k(a)){c="(";for(d="";k(a);)c+=d+D(a[1]),d=" ",a=a[2];return c=l(a)?c+")":c+(" . "+D(a)+")")}return w(a)?(c=a[1],a=a[2],d=L(a),!1!==d&&2===d.length&&m(c,ha)&&m(d[0],E)?b(d[1],"top"):"#"+D([1,c,a])):G(a)?"!"+D([1,a[1],a[2]]):B(a)?a[1]:6===a[0]?"$("+D(M(a[1]))+" "+D(a[2])+")":7===a[0]?"%("+D(a[1])+" "+D(F(a[2]))+")":8===a[0]?"@("+D(M(a[1]))+" "+D(a[2])+" "+D(F(a[3]))+")":9===a[0]?"^("+D(a[1])+" "+
D(F(a[2]))+")":A()}exports.__esModule=!0;exports.new_symbol=function(a){return[0,a]};exports.symbol_p=B;exports.un_symbol=function(a){return a[1]};exports.new_construction=xa;exports.construction_p=k;exports.construction_head=aa;exports.construction_tail=ba;var N=[2];exports.null_v=N;exports.null_p=l;exports.new_data=Ua;exports.data_p=w;exports.data_name=ca;exports.data_list=da;exports.new_error=ya;exports.error_p=G;exports.error_name=ea;exports.error_list=fa;exports.evaluate=function(a,b){return[6,
a,b]};exports.apply=function(a,b){return[9,a,b]};exports.force_all_rec=J;var E=[0,"\u592a\u59cb\u521d\u6838"];exports.system_symbol=E;var ha=[0,"\u7b26\u540d"];exports.name_symbol=ha;var q=[0,"\u5316\u6ec5"];exports.function_symbol=q;var K=[0,"\u5f0f\u5f62"];exports.form_symbol=K;var $a=[0,"\u7b49\u540c"];exports.equal_symbol=$a;var ab=[0,"\u89e3\u7b97"];exports.evaluate_sym=ab;var O=[0,"\u7279\u5b9a\u5176\u7269"];exports.theThing_symbol=O;var u=[0,"\u7701\u7565\u4e00\u7269"];exports.something_symbol=
u;var Oa=[0,"\u6620\u8868"];exports.mapping_symbol=Oa;var bb=[0,"\u82e5"];exports.if_symbol=bb;var t=[0,"\u4e00\u985e\u4f55\u7269"];exports.typeAnnotation_symbol=t;var R=[0,"\u662f\u975e"];exports.isOrNot_symbol=R;var Qa=[0,"\u5176\u5b50"];exports.sub_symbol=Qa;var Ra=[0,"\u967d"];exports.true_symbol=Ra;var Sa=[0,"\u9670"];exports.false_symbol=Sa;var cb=[0,"\u5f15\u7528"];exports.quote_symbol=cb;var db=[0,"\u61c9\u7528"];exports.apply_symbol=db;var eb=[0,"\u7a7a"];exports.null_symbol=eb;var na=[0,
"\u9023"];exports.construction_symbol=na;var oa=[0,"\u69cb"];exports.data_symbol=oa;var pa=[0,"\u8aa4"];exports.error_symbol=pa;var fb=[0,"\u8a5e\u7d20"];exports.symbol_symbol=fb;var wa=[0,"\u5217"];exports.list_symbol=wa;var gb=[0,"\u9996"];exports.head_symbol=gb;var hb=[0,"\u5c3e"];exports.tail_symbol=hb;var ib=[0,"\u7269"];exports.thing_symbol=ib;var jb=[0,"\u5b87\u5b99\u4ea1\u77e3"];exports.theWorldStopped_symbol=jb;exports.effect_symbol=[0,"\u6548\u61c9"];exports.sequentialWordFormation_symbol=
[0,"\u70ba\u7b26\u540d\u9023"];exports.inputOutput_symbol=[0,"\u51fa\u5165\u6539\u6ec5"];var Aa=[4,E,e(jb,u)],kb=za(oa);exports.new_data_function_builtin_systemName=kb;var Ba=Q(oa,ha);exports.data_name_function_builtin_systemName=Ba;var Ca=Q(oa,wa);exports.data_list_function_builtin_systemName=Ca;var Da=ia(oa);exports.data_p_function_builtin_systemName=Da;var lb=za(pa);exports.new_error_function_builtin_systemName=lb;var Ea=Q(pa,ha);exports.error_name_function_builtin_systemName=Ea;var Fa=Q(pa,wa);
exports.error_list_function_builtin_systemName=Fa;var Ga=ia(pa);exports.error_p_function_builtin_systemName=Ga;var mb=za(na);exports.new_construction_function_builtin_systemName=mb;var Ha=ia(na);exports.construction_p_function_builtin_systemName=Ha;var Ia=Q(na,gb);exports.construction_head_function_builtin_systemName=Ia;var Ja=Q(na,hb);exports.construction_tail_function_builtin_systemName=Ja;var Ka=ia(fb);exports.symbol_p_function_builtin_systemName=Ka;var La=ia(eb);exports.null_p_function_builtin_systemName=
La;var V=C(e(t,q,e(R,$a)));exports.equal_p_function_builtin_systemName=V;var qa=C(e(t,e(q,[1,q,u],u),db));exports.apply_function_builtin_systemName=qa;var ra=C(e(t,q,ab));exports.evaluate_function_builtin_systemName=ra;var Ta=Q(wa,e(t,ib,u));exports.list_chooseOne_function_builtin_systemName=Ta;var W=C(e(t,q,bb));exports.if_function_builtin_systemName=W;var sa=C(e(t,K,cb));exports.quote_form_builtin_systemName=sa;var Ma=C(e(t,e(K,e(q,u,q)),O));exports.lambda_form_builtin_systemName=Ma;var ja=C(e(K,
e(E,q)));exports.function_builtin_use_systemName=ja;var X=C(e(K,e(E,K)));exports.form_builtin_use_systemName=X;var Xa=C(e(K,K));exports.form_use_systemName=Xa;var ta=[3,Sa,e()],la=[3,Ra,e()];exports.jsArray_to_list=F;exports.maybe_list_to_jsArray=L;exports.new_list=e;exports.delay_p=x;exports.force_all=n;exports.force1=z;var Ya=[];exports.env_null_v=Ya;exports.env_set=Na;exports.env_get=Va;exports.env2val=M;exports.env_foreach=Wa;exports.val2env=Y;var ua=[ka(Da,w),[kb,2,Ua],Z(Ba,w,ca),Z(Ca,w,da),
ka(Ga,G),[lb,2,ya],Z(Ea,G,ea),Z(Fa,G,fa),ka(La,l),[mb,2,xa],ka(Ha,k),Z(Ia,k,aa),Z(Ja,k,ba),[V,2,function(a,b){function c(a,b,c,e){c=I(V,[c(a),c(b)]);a=I(V,[e(a),e(b)]);return I(W,[c,a,ta])}if(a===b)return la;a=z(a);b=z(b);if(x(a)||x(b))return I(V,[a,b]);if(a===b)return la;if(a[0]!==b[0])return ta;T(!x(a));switch(a[0]){case 2:return la;case 0:return P(a,b)?la:ta;case 3:return c(a,b,ca,da);case 1:return c(a,b,aa,ba);case 4:return c(a,b,ea,fa)}return A()}],[qa,2,function(a,b,c){var d=[];for(b=n(b);k(b);)d.push(b[1]),
b=n(b[2]);return l(b)?[9,a,d]:c}],[ra,2,function(a,b,c){a=Y(a);return!1===a?c:[6,a,b]}],ka(Ka,B),[Ta,1,function(a,b){a=z(a);return x(a)?I(Ta,[a]):k(a)?a[1]:b}],[W,3,function(a,b,c,d){a=z(a);if(x(a))return I(W,[a,b,c]);if(!w(a))return d;a=n(a[1]);return B(a)?P(a,Ra)?b:P(a,Sa)?c:d:d}]];exports.equal_p=v;exports.simple_print=r;exports.simple_print_force_all_rec=function(a){return r(J(a))};exports.simple_parse=Za;exports.complex_parse=va;exports.complex_print=D;var sb=va("\u6548\u61c9/[:\u7269]");exports.return_inputOutput_systemName=
sb;var tb=va("\u6548\u61c9/\u9023");exports.bind_inputOutput_systemName=tb;var ub=C(va("(\u70ba\u7b26\u540d\u9023 e c m a s c r i p t)"));exports.ecmascript_systemName=ub})();
