#!/bin/sh
rm lang.js 2> /dev/null
npx tsc --build tsconfig.json || exit
js="$(cat lang.js)"
cat > lang.full.js << EOF
// Generated by compile.sh
(function(){

$js

})();
EOF

echo '// Generated by compile.sh' > lang.externs.js
echo 'var exports = {};' >> lang.externs.js
grep '^exports.' lang.full.js | awk '{print $1}' | sed "s/^\(.*\)$/\1 = 'something';/" >> lang.externs.js
npx google-closure-compiler -W QUIET --assume_function_wrapper --language_out ECMASCRIPT3 --js lang.full.js --externs lang.externs.js -O ADVANCED > lang.js

echo '// Generated by compile.sh' > lang.pretty-print.js
npx js-beautify lang.js >> lang.pretty-print.js
