#!/bin/sh
tsc --build tsconfig.json || exit
js="$(cat lang.js)"
# js="$(google-closure-compiler -W QUIET --language_out ECMASCRIPT3 --js lang.js 2>/dev/null)"

cat > lang.js << EOF
// Generated by compile.sh
$js
EOF
